### ISSUE TITLE
FlashPlayer PPAPI 26.0.0.151

### ISSUE THREAD

**Issue by Blend2** [rzander/ruckzuck#10]
Hi Roger

The correct uninstall string is:

$proc  = (Start-Process -FilePath "$($Env:Windir)\SysWOW64\Macromed\Flash\FlashUtil32_26_0_0_151_pepper.exe" -ArgumentList "-uninstall" -Wait -PassThru);$proc.WaitForExit();$ExitCode = $proc.ExitCode 

Greetings 
Dani

**Comment by rzander** [comment]
THX, fixed...
