### ISSUE TITLE
Paremeter for silent In-Uninstall are missing or unknown ( "/?")

### ISSUE THREAD

**Issue by truthsword** [rzander/ruckzuck#100]
What does this mean... and how would I solve it?

![](https://i.imgur.com/IfwV0Gi.png)

**Comment by rzander** [comment]
When and where do you get that message ?

**Comment by rzander** [comment]
You get the message when you try to upload a software ?
If so, the "Installation script" and "UnInstallation script" must run silent and your current script has a Parameter "/?", which is not a silent parameter...

**Comment by truthsword** [comment]
> You get the message when you try to upload a software ?

Yes ... when I attempt upload. Is there a simple solution to this? Or am I simply "over my head"? This happened with both "Joplin" and "Advanced Renamer".

**Comment by rzander** [comment]
"Advanced Renamer" was fine.. it's approved and available in the public repository.
So let's take "Joplin" as an example, here you have the Installation Script:
```PowerShell
$proc = (Start-Process -FilePath "Joplin-Setup-1.0.233.exe" -ArgumentList "/?" -Wait -PassThru);$proc.WaitForExit();$ExitCode = $proc.ExitCode
```  
which will start `Joplin-Setup-1.0.233.exe /?` , which is not a silent setup. The challenge for you as a packager is the figure out the right parameter for a silent installation...
In your case the installation script should look like
```PowerShell
$proc = (Start-Process -FilePath "Joplin-Setup-1.0.233.exe" -ArgumentList "/AllUsers /S" -Wait -PassThru);$proc.WaitForExit();$ExitCode = $proc.ExitCode
```  

I'm using "Windows Sandbox" to check for silent parameters. It's a bit try and error, sometimes it's "/S", sometimes "/Q" or "/Quiet" , "/VERYSILENT" is also common...
If you click on "Create EXE..." it will generate an EXE File (in the same Directory as RuckZuck.exe). Copy that .EXE to a "Windows Sandbox" or a Test VM to check if the installation is working.
>Packages will only approved if they are working... If you leave your eMail in the "Author" attribute, I can give you an advise to fix it. The email will be removed automatically during the approval process.

As long as a Package is not approved, you can upload a fixed version...  So **Joplin** is waiting for your fixed version :-)

**Comment by truthsword** [comment]
When I run the generated executable, a command window appears, first 
downloading and then installing, then the window closes without error, 
but I do not find an application anywhere. I had the same experience 
yesterday before making the silent setup edits.

I ran this under Sandboxie, and later on my PC (unsandboxed).

Thanks for your help.

**Comment by rzander** [comment]
The important part is the result of the "Detection Script". If you are not sure if the installation was successfull, run the DetectionScript manually. If it's `true` then the SW is installed.... 
>Note: Always run the genereated executable as Admin !
