### ISSUE TITLE
Adobe Digital Editions 4.5 4.5.11 X64_RZ200421120

### ISSUE THREAD

**Issue by Blend2** [rzander/ruckzuck#101]
Hi Roger
New-Item "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\N360" -force -ea SilentlyContinue
im Install.ps1 scheint mir ein Fehler zu sein. Und der Exitcode ist 1223

Set-Location $PSScriptRoot;
$SuccessCodes = 0,1223,3010
$proc = (Start-Process -FilePath "ADE_4.5_Installer.exe" -ArgumentList "/S" -Wait -PassThru);$proc.WaitForExit();$ExitCode = $proc.ExitCode
if($successcodes -contains $ExitCode ) { $ExitCode = 0 }

Gruss Dani

**Comment by rzander** [comment]
Hallo Dani, 
Stimmt, im Pre-Install script war wohl ein Fehler drin... Habs korrigiert.
Was stimmt mit dem ExitCode nicht ? Wenn das EXE 1223 zurück gibt, müsste das Script 0 ausgeben ?!

**Comment by Blend2** [comment]
Hoi Roger
Dein Install.ps1 sieht so aus:

Set-Location $PSScriptRoot;
$proc = (Start-Process -FilePath "ADE_4.5_Installer.exe" -ArgumentList "/S" -Wait -PassThru);$proc.WaitForExit();$ExitCode = $proc.ExitCode
Exit($ExitCode)

Entweder leitest du den Exitcode 1223 auf 0 um, oder er muss in "Return Codes" auf dem Deployment eingetragen werden.

Wünsche dir noch ein erholsames Wochenende

**Comment by rzander** [comment]
Sorry, habe den Change rückgängig gemacht, da es den Key braucht.
Ohne Key erscheint Werbung ...
![image](https://user-images.githubusercontent.com/11909453/92949818-fce09780-f45b-11ea-93c3-983ec868f2ef.png)

**Comment by Blend2** [comment]
Danke Roger, du kannst den case schließen
