### ISSUE TITLE
Question: Device Collection instead of User Collection

### ISSUE THREAD

**Issue by williwill7** [rzander/ruckzuck#102]
Hi,

in RuckZuck for ConfigurationManager is it possible to automatically create a Device Collection instead of creating a User Collection for Deployment?
I didn't found an option in the ini-file.

Thanks for this awesome software and best regards 
Willi

**Comment by rzander** [comment]
https://github.com/rzander/ruckzuck/wiki/RuckZuck-for-ConfigMgr#defaultadgroup
>Important: If you leave this Field empty, a Device Collection will created (without any Members) and the deployment will be set to "Required".

**Comment by williwill7** [comment]
Thanks!
