### ISSUE TITLE
Zoom detection issue

### ISSUE THREAD

**Issue by warp16** [rzander/ruckzuck#105]
Running RuckZuck 1.7.1.6

Despite having the current version of Zoom installed (5.3.53291), RuckZuck detects an update.
I noticed that the detection script is looking for zoom.exe in Program Files (x86), however on my laptop, it was installed in %appdata%. I think this is triggering the app to then look for the version info in the registry, where the version number is in a slightly different format (with parenthesis) than the actual file version number.

Uninstall registry key shows the version as: 5.3.2 (53291.1011)
Zoom.exe file version is 5.3.53291.1011

![image](https://user-images.githubusercontent.com/12633352/96357496-ba4d5300-10ca-11eb-87da-78a3353b2f5c.png)
![image](https://user-images.githubusercontent.com/12633352/96357498-c46f5180-10ca-11eb-9f8f-47a9aab6dbbc.png)

**Comment by rzander** [comment]
Thanks for providing feedback. 
It seems that the EXE installer and the MSI Installer do store different Version formats in registry. RuckZuck is only able to compare versions if they are "real" Version numbers. So the version from the EXE will always end in the result of having an update if the string does not match the Version of the MSI...
But, I agree that the detection method was only for MSI installation. So I changed the ZOOM Package to detect the installation also for User based EXE installations.
The result now is that you will get an update notification but as soon as you  install it, it will switch to "installed" without doing anything.  I think that's all I can do for the moment...
