### ISSUE TITLE
AdobeReader DC and 7-Zip is missing

### ISSUE THREAD

**Issue by Jivaross** [rzander/ruckzuck#107]
I used for atleast 2 months ur commandline tool RZget.exe mainly to install adobe reader DC but now it is not available, why?

**Comment by rzander** [comment]
Both are in the repository... Maybe there was an Issue with the Repo ?! What is your REST-API URL (Gear Icon in Ruckzuck.exe) and you can try to delete %TEMP%\rzcat.json before starting Ruckzuck.exe ...

In general, approval is required before anything is getting published... If you wish feedback, fill your email in the author attribute so I can contact you. The author attribute will be automatically deleted during the approval.

**Comment by amartin253** [comment]
That is weird. No versions of Adobe Reader or 7Zip were showing when I looked at the URL I mentioned above about an hour ago but they do now and also show in ruckzuck.exe now

**Comment by Jivaross** [comment]
I was also unable to find it in repository from website too

**Comment by amartin253** [comment]
REST-API URL is https://cdn.ruckzuck.tools for me

**Comment by rzander** [comment]
I assume there was a problem with the repo. If the CDN Cache (https://cdn.ruckzuck.tools) has incomplete content, it will cache the content for an hour....  and %TEMP%\rzcat.json will cache it for 30min...
But i hope it's fixed now ?!

**Comment by rzander** [comment]
A little secret: if you click on "Favorites\Old Feedback" in RuckZuck.exe , it will force the Server to regenerate the Catalog... it will not help if the CDN catalog is corrupt, but at least the Repo on the WebSite should be updated...

**Comment by amartin253** [comment]
Looks good for now! Thanks for the info @rzander

**Comment by Jivaross** [comment]
will it affect rzget? I use default repository

**Comment by rzander** [comment]
RZGet is using the same repository and the same CDN cache.

**Comment by rzander** [comment]
@Jivaross which Version of RZGet are you using? -> The binaries of the Preview Version (1.7.1.7) where updated several times in the last weeks, just if you are using this version...

**Comment by Jivaross** [comment]
i'm using version 1.7.1.5
