### ISSUE TITLE
RZ4Intune - Zoom machine msi install context set to user

### ISSUE THREAD

**Issue by sebawern** [rzander/ruckzuck#108]
When using RZ4Intune, the MSI file for Zoom gets executed as user rather than system. As far as I can tell, this breaks the setup for standard users (users who are not admins) on their machines.

**Comment by rzander** [comment]
It was because the detection method contains a check on HKCU Registry Key... Can't you just switch to Teams ? :-)
I have changed the detection method, so if you recreate the Zoom App with RZ4Intune it should run as System...

**Comment by sebawern** [comment]
I can, some customers won‘t (yet?) :)

Thanks for the fix, I‘ll try it tomorrow!

**Comment by sebawern** [comment]
I've just tested the new packages, it works! Thank you.
