### ISSUE TITLE
Crashing on Windows 7

### ISSUE THREAD

**Issue by freekee1** [rzander/ruckzuck#11]
While having worked nicely on Windows 8 and still working perfectly on Windows 10, RuckZuck crashes right upon startup on Windows 7 (Professional, 64Bit).
I could not yet figure out any compatibility settings or other actions to take to make it work.

**Comment by rzander** [comment]
It's working fine here... Do you have Management Framework >4 (PowerShell) installed ?

**Comment by freekee1** [comment]
Indeed, I'm very sorry! I was sure a recent WMF was installed, but after installing WMF 5.1, it actually works. Silly me ... (my excuse: computer at work, I didn't set it up! :-)).
