### ISSUE TITLE
Webroot is picking up RuckZuck as malware

### ISSUE THREAD

**Issue by captainwasabi** [rzander/ruckzuck#112]
Just FYI

**Comment by xtrenge** [comment]
same here...

**Comment by amartin253** [comment]
Perhaps because RuckZuck has IntelliJ-IDEA-Community in its repo since that was sourced as part of the whole SolarWinds hack recently

**Comment by rzander** [comment]
to make RuckZuck.exe smaller, I use ConfuserEx to compress the resources in the exe. I think that is what they do not like.. I can offer to publish an "uncompressed" version if this helps... ?!

**Comment by rzander** [comment]
https://github.com/rzander/ruckzuck/releases/download/1.7.2.0/RuckZuck_uncompressed.exe

**Comment by captainwasabi** [comment]
This seems to have resolved the issue.  Thanks!
