### ISSUE TITLE
TeamViewer Host cannot be downloaded although URL is correct

### ISSUE THREAD

**Issue by Offebaescher** [rzander/ruckzuck#113]
Hi there, i do not know if this is the right place to report this, but download of Teamviewer Host Setup File is failing. I thought that the URL at Teamviewer might be wrong and looked it up myself, also checked the redirection the server is sending and followed to that URL, but downloading still fails if i create a new package.

Is this some cloudflare protection at their end?

current json has:
`"URL":"https://dl.tvcdn.de/download/TeamViewer_Host_Setup.exe"`

Using that in my browser, works.
I looked new URL up with wget -S which redirects to 

https://dl.teamviewer.com/download/TeamViewer_Host_Setup.exe
and
https://dl.teamviewer.com/download/version_15x/TeamViewer_Host_Setup.exe

I built a new package and tested it, however again:

```
"TeamViewer Host_15.13.6_X64_setup.exe"
TeamViewer TeamViewer Host 15.13.6
Downloading...Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
ERROR: download failed... TeamViewer_Host_Setup.exe
```

Am i missing something?

Thanks!

**Comment by rzander** [comment]
Just did a test and TeamViewer Host is able to download and install here... I'm also able to create a package with `https://dl.teamviewer.com/download/version_15x/TeamViewer_Host_Setup.exe` as download source.
are you in a corp. network behind a proxy ? or a country that may be blocked ?

**Comment by Offebaescher** [comment]
Dear Roger, thank you for the quick response. In fact i can confirm that the Teamviewer Host File can now be retrieved again from their host.  It seems it was really just an temporarily error on their side (it is unlikely too that they blocked german IP ranges for some reason).

Therefore sorry for having created the issue. Can confirm that RZGet is working fine.

Cheers
