### ISSUE TITLE
IrfanView not detected as already installed

### ISSUE THREAD

**Issue by Offebaescher** [rzander/ruckzuck#114]
Installation of current IrfanView works fine:

```
rzget install IrfanView
Irfan Skiljan IrfanView (remove only) 4.57
Downloading...... done.
Installing...... done.
```

However checking if it is installed does not even list it at all, other products are listed but IrfanView is not mentioned

`rzget search --isinstalled true`

The script in the JSON returns true though if i run it manually in PS
The key in my registry is here:
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\IrfanView64
`
PS:
```
 if(([version](Get-ItemPropertyValue -path 'HKLM:\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\IRFANVIEW64' -Name DisplayVersion -ea SilentlyContinue)) -ge '4.57') { $true } else { $false }                   
True

```
What could be the reason that "rzget search --isinstalled true" does not return IrfanView?

**Comment by rzander** [comment]
I think I know why... The "Product Name" in RuckZuck is defined as "IrfanView (remove only)" but the tool does register itself as "IrfanView 4.57 (64-bit)".
I have changed now the "Product Name" to "IrfanView 4.57 (64-bit)". It may take a few hours to become active ... let me know if there is still an Issue with it..

**Comment by Offebaescher** [comment]
Hello Riger, can confirm that it works fine now. Thank you for fixing it.
