### ISSUE TITLE
Feature - Unhide specific strings from UpdExlusion

### ISSUE THREAD

**Issue by georgethemarmot** [rzander/ruckzuck#115]
Hi,
Additional to Update Exclusion Clear All Button
It would be nice to be able to unhide specific strings from a list in settings.
Very nice piece of software. Keep it up! 👍

**Comment by rzander** [comment]
I do not really get, why someone has to exclude/hide some updates in the UI in general... Maybe you have to give me some more background infos, what you plan to do an why... THX
