### ISSUE TITLE
PSDetection not usable with SCCM

### ISSUE THREAD

**Issue by rolandsallaberger** [rzander/ruckzuck#116]
hi roger,

I did some research and it looks like many detection-methods are incorrect. For example Treesize:

PSDetection    : if(([version](Get-ItemPropertyValue -path
'HKLM:\SOFTWARE\WOW6432NODE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\TREESIZE FREE_IS1' -Name        DisplayVersion -ea SilentlyContinue)) -ge '4.4.2') { $true } else { $false }

So this script will return $true or $false. However the detection method within SCCM needs another output: $true or $null. 
see: https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/gg682159(v=technet.10)#BKMK_Step4?ranMID=43674&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-EKLaIr9C8Qxp_QGhnxEvqQ&epi=je6NUbpObpQ-EKLaIr9C8Qxp_QGhnxEvqQ

Is there a way to fix it, or a simple workaround?

br roland

**Comment by rzander** [comment]
From where do you get the PSDetection? RZ4ConfigMgr should automatically translate the detection result....

**Comment by rolandsallaberger** [comment]
I've got it from "Invoke-RestMethod -method Get -Uri "https://cdn.ruckzuck.tools/rest/v2/getsoftwares?shortname=". I have created my own sccm-app-builder application and therefore i thought i can use this method to get such information. I want to add those install commands in my PsAppDeployToolkit-Templates and i want to import it without RZ4ConfigMgr.

**Comment by rzander** [comment]
a RuckZuck package is not 100% compatible with the Application model of MECM. E.g. RuckZuck can use PowerShell-Scripts as PreRequisite check -> this option does not exist in MECM.  You will have to do some translations...

**Comment by rolandsallaberger** [comment]
Okay, thanks Roger.
