### ISSUE TITLE
Help to create a json. 

### ISSUE THREAD

**Issue by dbmello75** [rzander/ruckzuck#118]
I'm tring to create a json file with all the Apps I need. 

With this json:
`[{
   "Categories": [      "Utilities"    ],
    "Description": "This program is designed to write a raw disk image to a removable device or backup a removable device to a raw image file. It is very useful for embedded development, namely Arm development projects (Android, Ubuntu on Arm, etc). Anyone is free to branch and modify this program. Patches are always welcome.",
    "Downloads": 139,
    "IconHash": "9qZq5fdeXkwBYy6FEUSVQ2eY7",
    "IconURL": "https://cdn.ruckzuck.tools/rest/v2/GetIcon?size=32&iconhash=9qZq5fdeXkwBYy6FEUSVQ2eY7",
    "isInstalled": true,
    "Manufacturer": "ImageWriter Developers",
    "ProductName": "Win32DiskImager version 1.0.0",
    "ProductURL": "http://sourceforge.net/projects/win32diskimager",
    "ProductVersion": "1.0.0",
    "ShortName": "Win32DiskImager",
    "SWId": 190491247
}]`

I'm getting this error:

`PS C:\Windows\system32> rzget install D:\Apps_Install.json
ImageWriter Developers Win32DiskImager version 1.0.0 1.0.0
Downloading...
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RZGet.Program.Install(RZUpdater oRZSW)
   at RZGet.Program.Main(String[] args)`

**Comment by rzander** [comment]
The JSON in you example is a copy of the catalog, it does not contain the required informations to install a software...
Look at: https://github.com/rzander/ruckzuck/wiki/How-to-create-a-Package-for-the-Repository 

You can use ruckzuck.exe to create a JSON (there is an option to save your package as json), or check this example:
https://cdn.ruckzuck.tools/rest/v2/GetSoftwares?shortname=RuckZuck%20provider%20for%20OneGet
