### ISSUE TITLE
Adobe Air

### ISSUE THREAD

**Issue by Blend2** [rzander/ruckzuck#119]
Salü Roger

Wie es scheint, hat Adobe die Weiterentwicklung von Adobe Air an Harman Samsung ausgelagert.
Evtl. willst du dies bei der RuckZuck DB anpassen....
https://blog.adobe.com/en/publish/2019/05/30/the-future-of-adobe-air.html#gs.rrdv2h
https://airsdk.harman.com/runtime

Gruss Dani

**Comment by rzander** [comment]
Habe das Paket angepasst... Danke.
