### ISSUE TITLE
ImageMagick 7.0.7-1 Q16

### ISSUE THREAD

**Issue by Blend2** [rzander/ruckzuck#12]
The download link "https://www.imagemagick.org/download/binaries/ImageMagick-7.0.7-1-Q16-x64-dll.exe" from the ImageMagick application doesn't exist anymore. The new link is on "https://www.imagemagick.org/download/binaries/ImageMagick-7.0.7-2-Q16-x64-dll.exe"

Greetings
Dani

**Comment by rzander** [comment]
Thx, it's fixed now, but it takes some time until it's visible in the tool...
