### ISSUE TITLE
Back/Finish buttons when editing & app selection method

### ISSUE THREAD

**Issue by vertigo220** [rzander/ruckzuck#120]
When editing a package's details, the back and finish buttons on the bottom stay and continue to perform their functions from the app list view, despite essentially being in a different window. So the user would expect the back button at this point to take them back to the list where they left off (IOW, close the edit screen), but instead it takes them back to the main screen. Similarly, the exit button closes the app entirely instead of the current screen. When opening the edit screen, it should completely replace/overlay the prior screen, including those buttons, and it should have its own back/cancel button on the bottom (outside the scroll area so it's visible all the time).

This brings me to another, somewhat related, issue: To select multiple apps for install, they have to be selected by Ctrl+clicking, which is very problematic because it means if you accidentally click without hold ctrl, you lose all your selections, and you also can't edit something partway through without losing them all. Checkboxes would be even better, though even then you could still lose all your selections if you edit something then press back or exit, since currently that would take you back to the main screen or exit the app. So by combining checkboxes for selecting apps to install and fixing the first issue, a user could select several apps, open one for editing, save or press back and be taken back to the app list, and continue from where they left off, with their previous selections still active.

**Comment by rzander** [comment]
Fixed the Issue with the "Back" button on the edit page:
https://github.com/rzander/ruckzuck/commit/89c981d6e5fdfb24b27734a7759dc17ae1241031

**Comment by rzander** [comment]
What is the use case to select several apps , edit one and swicth back to the list ?
How often do you select multiple Apps and for what reason ?

**Comment by vertigo220** [comment]
I only just started playing with RuckZuck, so it's too early to say for sure, but as for why one might select several apps, edit one, then switch back, they might simply be new to it and go through selecting several apps intending to install them all at once, and in the middle of doing so might be curious about edit, click it, and lose all their selections. Granted, this would probably be a one time thing, but still, not a very good first impression and will likely frustrate some new users. Now that I've checked out the edit screen, I don't know why I would need to use it, but it's there for a reason, so I imagine somebody having a reason to use it might do so after selecting a bunch of other apps.

Also, I just figured out that if you select multiple apps and right-click on one and choose edit, the edit screen opens for the first app selected (at least that's what it appears to be), _not_ the app that was right-clicked.

As for selecting multiple apps and why, see my other issue, #122.

**Comment by vertigo220** [comment]
The second issue (ctrl+clicking to select multiple apps) was also brought up in issue #58. The suggestion there was to double-click to add to a queue, and that was turned down because it was thought to "be dangerous if a double click triggers an installation." However, it wasn't being suggested to install on double-click, only add to queue. In any event, whether through double-clicking or a checkbox (or checkboxes that can be toggled by clicking the box or double-clicking the item), the fact is it would be more usable if users could select multiple items without risking having their selections wiped with one wrong move. Ideally, selections should be maintained until RuckZuck is closed or they're cleared by some sort of "unselect all" option.

**Comment by rzander** [comment]
Select an app and click on "start installation", then select another app you want and click on "start installation"...  If you need time to think about if you need a software or not, then do not install it ;-)

**Comment by vertigo220** [comment]
Maybe it works differently than I anticipate, but in that case it works different than most other programs (so contrary to the "standard") and it doesn't indicate that in any way. I would expect that if I select an app and click on "Start installation..." it would then install that app and I would have to wait for the installation to finish before installing the next app. One of the big benefits to a package manager like this is to be able to select all the apps to install then batch install them, so a few minutes of clicking then install and walk away. If RuckZuck doesn't work that way, then it's missing a very significant feature. If it does allow you to keep clicking "Start installation..." while other installations are already running, just queuing them up, then yeah, multiple selections are a moot point, but then it should be more clear about how it works, since the standard, and therefore the expectation, as evidenced by myself and @ltGuillaume asking for such a feature, and even having the ability to select multiple apps at once, leads people to believe it works one way when it works another. So I imagine it's not at all uncommon for new users to do exactly what we did, going through and selecting multiple apps via ctrl+click.
