### ISSUE TITLE
x64 vs x86

### ISSUE THREAD

**Issue by vertigo220** [rzander/ruckzuck#121]
I'm sure there are other examples, but I noticed WinMerge not only just has the x64 package available, but it's not labeled as such on the app screen. The only way to know which one it is is to edit it, [which has its own issues](https://github.com/rzander/ruckzuck/issues/120). I personally don't like to use the x64 version, since while comparing large files with the x86 version will result in failure with a message that the files are too large, the x64 version will just consume more and more memory until it takes down the whole system with it (poor design, [which I reported a while back](https://github.com/WinMerge/winmerge/issues/325), but despite being an _extremely_ serious issue it has only been labeled as "improvement needed," so I don't expect it to ever be fixed.

So my point is two-fold: WinMerge should ideally have the x86 version available as well, and all apps should include somewhere on the list, whether as part of the version or a separate tag, whether they're x64 or x86, because it _can_ matter.

**Comment by rzander** [comment]
RuckZuck can have multiple architectures in a single package. It will try all "Prerequisite Scripts" to find the right architecture...
But no one is willing to maintain the x86 architecture for x86 Devices... so there are only a few old packages with multiple architectures.
Personally, I would expect to get the x64 Version of a Software (if exists) on a x64 Device... and a "normal" User should not care about x86 or x64.
In case of WinMerge: if you have a real issue, which affects all users, you can publish an update to replace the x64 with the x86 version... But, RuckZuck is not the solution to fix Issues from the vendors, it's fine if there is no other workaround.

**Comment by vertigo220** [comment]
I may be misunderstanding you, but WinMerge is available in separate x64 and x86 packages from the website, so they are maintaining separate versions. And RuckZuck is downloading the x64 version specifically, not a package with both that then installs whichever based on the computer's/OS's architecture. So "all" that needs to be done is to have a separate WinMerge entry in RZ and label them as x64 and x86 and let the user choose. After all, there's a separate 7-Zip and 7-Zip (MSI), so it seems reasonable enough. But then, I don't know what all is involved in creating and maintaining the "packages" in RZ. If that's what you mean by no one being willing to maintain it, i.e. nobody is going to maintain an extra WinMerge version, that's understandable. I just want to be clear and make sure we're on the same page.

As for publishing an update, I could certainly look into doing that (I assume it's reasonably easy), but I don't know if it's a widespread issue, since it hasn't been investigated by the WinMerge team. So I'd hate to tamper with it and limit users to the x86 version when the x64 version might work without issue for them, but OTOH I'd hate to leave it and have others experience the same train wreck that I did with it, which is why it would be better to have separate versions, and ideally to allow users to attach warnings (would need to be moderated, though) to them. So is it preferable to change it just in case or leave it and hope others don't have an issue with it? I feel like just having to make that decision does exactly what you want to avoid: it makes RuckZuck the solution for fixing issues by limiting it to one version or the other, instead of providing both and leaving it up to the end user to decide.
