### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by vertigo220** [rzander/ruckzuck#122]
I'd like to make a few requests regarding favorite apps. I apologize for putting them together in one issue, but they are related.

1) There should be a way to add apps to a user's favorites list so they can use that list to easily, and preferable automatically (i.e. batch installation) install those apps (latest version, of course, so the favorites should just be the app, not app version, unless the user specifies that in some cases where they may want/need to stay on an older version) on other systems. For example, I'd like to be able to go through and mark the apps I want as favorites, then take a configuration file (.ini or .xml or .db or whatever) along with RuckZuck to a different computer and view only those apps, select the ones I want from that list, and have it install them. And ideally it would be dated so RuckZuck could use that date when displaying the "New Software" under Favorites, to display all new software (totally new, not just updated, i.e. by app, not app version, again) added since that date and update the favorites date in the config file so those apps won't be shown next time. This would make it easy for users to periodically check only new software to see if they want to add any of them to their favorites. Another option would be to have RuckZuck show newly added software since it's last launch.
2) Actually the opposite of favorites, there could be an option to hide selected apps, so ones the user would never want/need could just be hidden out of sight. Of course, they should be able to be shown and rehidden with some sort of toggle (unhiding should still remember which ones were hidden, so they don't need to be reselected manually). This may not be as good as doing the stuff in point 1, but it would more or less accomplish the same thing (at least if the hidden apps list was stored in a config file that could be transferred to another computer) and would probably be a lot easier to do.
3) The current "favorites" setup isn't intuitive. First, I don't even know why anyone, particularly myself, would need the "Oldest Feedback" favorite. Which leads me to the second issue with it: they don't appear to be customizable. Not having a need for that particular favorite, I can't remove it. And "New Software" is only partially helpful since I don't know what the cut-off is and can't customize it. And finally, I can't add apps as favorites. Right-clicking them, there's no option to do so. But there is a "Create .EXE" option, which doesn't seem to have anything to do with favorites, yet it shares the same icon, which only adds to the confusion.
4) Issue #58 has a good suggestion (# 2) regarding having a favorites based on what other users are installing, but it didn't go anywhere. I realize it can't be based on # of downloads, but if a true favorites feature, as described above, were added, so users could actually set their favorites, then those could be used. So a corporate user might add 30 apps to their favorites and use that list to install them on a bunch of PCs, and they might install them hundreds of times, but they would only actually favorite them once. Meanwhile, "normal" apps would be favorited and installed once per user by hundreds/thousands/however many users, making those apps actually top the chart. And RuckZuck could automatically add apps that are installed to favorites so they're counted even if the user doesn't manually favorite them. It would have to only do so if not already favorited, though, so they wouldn't count multiple times if they're installed multiple times, to prevent it from leading to the same issue related to corporate installs. Of course, if that can be done (and it seems it should be able to be), then it should also be doable to only count the first install done, which seems it should deal with the corporate installs.

   I don't really get why corporate installs would be so high, since typically they install once on one system then image that to all the others. So clearly there's something else going on here. Based on the numbers, it seems like they're putting RuckZuck on multiple computers and installing software to each one independently, which would just be a massive waste of time and bandwidth. And if that's what's happening, then probably none of my suggestions would help. Maybe you could offer insight into what I'm missing here and I could think of other possible solutions. Or you could implement a simple voting system, since home users would be more likely to use that whereas corporate users would probably ignore it, though that would be open to abuse by people voting multiple times, but I seriously doubt many people would do that. And it could limit votes to one per app per computer. Finally, one last possible solution would be to simply base it off of installs but remove certain apps from the list, e.g. VCRedist* and JavaRuntime*.

**Comment by rzander** [comment]
What is the use case, Personal or Business ?
I do not see a reason on personal devices why you have to hide or store favorite software list's. If you want to automate the installation then you should use https://github.com/rzander/ruckzuck/wiki/RZGet and not ruckzuck.exe. But why should I hide an app from UI, just don't select it ?!  

RuckZuck can only survive, if people are wiling to test and report broken links. "Old feedback" are packages which have not sent feedback for a long time, so everyone can help to just run them on a VM or Sanbox just to see if everything is fine.  But I agree that the name "Favorites" is missleading, and should be replaced...  

You are not going to deploy a Windows Image just because there is a new version of Teams !  So I see a big use case on corp devices. That's why https://romawo.com/ is using RuckZuck technology to patch and update 3rd party software on corp devices... 
I do not have a general problem with the usage on corp devices, it just must be a good balance of usage and the willingness to invest.

**Comment by vertigo220** [comment]
> What is the use case, Personal or Business ?

In my case, personal

> I do not see a reason on personal devices why you have to hide or store favorite software list's. If you want to automate the installation then you should use https://github.com/rzander/ruckzuck/wiki/RZGet and not ruckzuck.exe. But why should I hide an app from UI, just don't select it ?!

Because, as I said, I'd like to be able to go through once and pick out the apps I use, then be able to put RZ and a config file (used to tell RZ which apps I favorited, so it only shows those, or which I hid, so it doesn't show those, to the same effect) so I don't have to go through the whole list of ~400 apps just to install maybe 10% of them, but instead just see the ones I actually use. Then I can go through that condensed list and pick just the ones I want on that computer.

Yes, I could use RZGet, except for two things. First, I don't even know anything about it, including what it does, so I didn't know that it existed for this purpose. Even downloading RZ, I wasn't sure which one I needed, which was made even more confusing by the fact that not all files are included in each release. It didn't take long to figure out to get ruckzuck.exe, but a basic user would have no clue. And a basic user certainly wouldn't know to get RZGet. Granted, a basic user probably wouldn't _need_ it, nor would they probably even be looking at RZ, but if they did, they wouldn't have a clue, because RZ doesn't offer any insight, and because the GUI (ruckzuck.exe) could (and, IMO, should) work in a way that would allow more basic users to easily do this. And as you say, RuckZuck can only survive if people are willing to test and report broken links, which can be paraphrased to say it can only survive if people are using it. The easier and more user-friendly you make it, the more people will use it. So yes, if I spent more time figuring out the various components--something not made easy by the lack of any wiki, the lack of any info about it in the program, etc, and therefore not something many will do--I could probably use RZGet. But with a few small changes (e.g. add a "Hide App" entry to the context menu and save that to a config file, which RZ reads to see what apps to show), it can be made customizable to make it much easier to use.

The second reason RZGet may not work is because, and I could be wrong about this because I don't know anything about it at this point, I suspect you just give it a list of apps you want to install, but what if some of them are already installed or you don't want to install all of them. For example, I may install 40 apps on one computer but only want 30 on another, 45 on another, and maybe only 10 on someone else's computer I'm setting up for them. To me, it just seems by far the easiest way to do this would be to tell RZ to only show me a select list of apps, so I only have to go through a list of 40 or 50 on each computer and install the ones I want on that computer, vs going through a list of 400 apps or messing with another utility that requires lots of command line usage and manually typing each app name I want to install or even having them in a file that gets referenced but having to edit the file for each setup. And don't get me wrong, I have nothing against the command line; I use it all the time. But even considering that, I still prefer to do what I can with a GUI, since it's just faster and easier. Many people are going to see command line and just move on. If you truly want to limit RZ to more advanced users only, that's your choice, but I would think you'd want more users, and as I said you could make it much easier to use and therefore much more accessible and inviting to those users with a few changes to make the GUI able to do what currently requires RZGet.
> 
> RuckZuck can only survive, if people are wiling to test and report broken links. "Old feedback" are packages which have not sent feedback for a long time, so everyone can help to just run them on a VM or Sanbox just to see if everything is fine. But I agree that the name "Favorites" is missleading, and should be replaced...

Again, this comes down to lack of documentation. RZ needs people to do this, but how many RZ users even know that? I'd bet most users aren't going to bother, but I'd bet that most of those that would don't even know, and if you made this more apparent you'd get more testing being done on them. If I find a project to be promising and worthwhile, I'll try to help in the ways I can, which is why I'm creating these issues to make suggestions for improvement and report issues. And I'd happily do some test installs on the "old feedback" packages to help out, but I wouldn't even know the need was there if not for mentioning it here and having you explain it.
> 
> You are not going to deploy a Windows Image just because there is a new version of Teams ! So I see a big use case on corp devices. That's why https://romawo.com/ is using RuckZuck technology to patch and update 3rd party software on corp devices...
> I do not have a general problem with the usage on corp devices, it just must be a good balance of usage and the willingness to invest.

Ah, yeah, that makes sense. So maybe RZ could could installs but not upgrades for determining favorites based on usage.

**Comment by vertigo220** [comment]
I think closing this is premature. Renaming Favorites to Support was only a very, very small part of this overall issue.
