### ISSUE TITLE
Silent Installs and PUPs

### ISSUE THREAD

**Issue by vertigo220** [rzander/ruckzuck#123]
I don't see anything on the website, in the program, or in the issues regarding how, or even if, RuckZuck avoids the installation of unwanted bundled junk (PUPs, adware, crapware, toolbars, etc). Does it only include software that doesn't contain them, or does it somehow decline them, in which case how effective is it?

**Comment by rzander** [comment]
RuckZuck is (normally) using the installer from the vendor... Sometimes, the packager who creates a package, does cleanup things, but it's not a requirement... All Packages are installed in a sandbox and scanned with a virus scanner. PUA (Potentialy Unwanted Applications) are allowed if the main app is a well known PUA (e.g. Sysinternals)

**Comment by vertigo220** [comment]
If they're installed in a sandbox, then would that mean they're limited in what they can do, or are they installed normally after, once the sandbox install verifies there are no issues? Because certain apps, if sandboxed, aren't going to have the access they need. And what's the virus scanner? I know a lot of things like this like to use ClamWin, but that scanner is next to useless IME.

What about having a reporting system so users can report apps that are installing unwanted crap and those installers can then be either removed or flagged to warn others?

**Comment by rzander** [comment]
Let me know if you see any apps that install unwanted junk...
