### ISSUE TITLE
Can RuckZuck be installed and used portably?

### ISSUE THREAD

**Issue by VladPutinEu** [rzander/ruckzuck#127]
@rzander Can I install RuckZuck and use it on a thumb-drive? Will all the apps be portable too? Something like PortableApps.com

**Comment by rzander** [comment]
Yes and No... RuckZuck.exe is a portable app. You can also create an EXE from a specific app via RuckZuck.exe... But it will still download the content from the Internet (you can theoretically preload the content in %TEMP%).

**Comment by VladPutinEu** [comment]
> Yes and No... RuckZuck.exe is a portable app. You can also create an EXE from a specific app via RuckZuck.exe... But it will still download the content from the Internet (you can theoretically preload the content in %TEMP%).

If I use RuckZuck on a thumb-drive, will all the programs I install using it only be installed to the thrumb-drive and make no changes to the system?

**Comment by rzander** [comment]
No, RuckZuck triggers a download from the vendors web-site and start's a "normal" installation of the software.

**Comment by VladPutinEu** [comment]
> No, RuckZuck triggers a download from the vendors web-site and start's a "normal" installation of the software.

Oh, so it can't install apps portably like PortableApps.com?

**Comment by rzander** [comment]
No

**Comment by VladPutinEu** [comment]
> No

Thanks for your support.
