### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by ajtak-angelus** [rzander/ruckzuck#128]
Hi,
I have please two problems.
1) the application cannot be installed if there is diacritics in the path c:\users\uživatel\appdata\local\temp (ěščřžýíé etc) - implement UTF-8 in the path? Tested on RuckZuck and RZGet
2) rzget install RuckZuck does not work.

Thank you very much

**Comment by rzander** [comment]
1. To be able to reproduce, the Username has some special characters? Do you get an error when it downloads the content ?

2. ```rzget install ruckzuck``` will not work as ruckzuck is a portable app and cannot be installed. It's in the repository to allow updating ruckzuck.exe. If you check the metadata, you will see that it looks for a ruckzuck process to find the path where ruckzuck.exe is located.

**Comment by ajtak-angelus** [comment]
1. MPC-HC Team MPC-HC 1.9.9 (64-bit) 1.9.9
Downloading...... done.
Installing...ERROR:An object at the specified path C:\Users\JI8DC8~1 does not exist.
ERROR:This command cannot be run due to the error: Systém nemůže nalézt uvedený soubor.
ERROR:You cannot call a method on a null-valued expression.
WARNING: Product not detected after installation.
... Error. The installation failed.

C:\Users\JI8DC8~1 - correct is C:\Users\Jiří
Or change the download folder?

2. ok, thanks.

**Comment by rzander** [comment]
I tried to reproduce , but everything is working fine here:
![image](https://user-images.githubusercontent.com/11909453/116135946-027cac00-a6d2-11eb-89c1-7ea7c5be8212.png)

**Comment by martinlugger** [comment]
Hello Rzander
I did a deeper testing.
I found: If you have a Username with a char "." in the name and 4 chars after the char "." the download is always OK but the installation fails. If the length of the username is equal 12chars or more, the installation succeed. You shuld be able the reproduce the problem:

**User:U.1234
============**

![U 1234_Error](https://user-images.githubusercontent.com/74625265/116231659-73b37200-a759-11eb-8355-f4dbdab91aee.png)

**User:U1.1234
============**

![U1 1234_Error](https://user-images.githubusercontent.com/74625265/116231813-a5c4d400-a759-11eb-9c27-967a95173a43.png)

**User:U12345.1234
================**

![U12345 1234_Error](https://user-images.githubusercontent.com/74625265/116232167-07853e00-a75a-11eb-8920-56794449928e.png)

**User:U123456.1234
================**

![U123456 1234_NO-Error](https://user-images.githubusercontent.com/74625265/116232267-326f9200-a75a-11eb-99b1-ea76bed8a47c.png)

**User:Martin.Test
================**

![martin test_Error](https://user-images.githubusercontent.com/74625265/116232461-72cf1000-a75a-11eb-8e9e-474a8f371240.png)

**User:MartinTe.st
================**

![MartinTE st_NO-Error](https://user-images.githubusercontent.com/74625265/116232624-af9b0700-a75a-11eb-8cac-32d33c8d8ec3.png)

**Comment by rzander** [comment]
A "normal" `Set-Location $env:temp` does also not work... -> https://superuser.com/questions/1524767/powershell-uses-the-short-8-3-form-for-envtemp.
![image](https://user-images.githubusercontent.com/11909453/116293228-f0b10c80-a796-11eb-96ed-26e8e8ab5d68.png)


In general, I would say that this is a PowerShell Issue...
I have changed the way how RZ is setting the location: https://github.com/rzander/ruckzuck/commit/f086c259f0634f75565da64650d34c0f476cac12
You can try the following preview version if the Issue is fixed:
[RZGet_Preview.zip](https://github.com/rzander/ruckzuck/files/6386746/RZGet_Preview.zip)

... let me know if the preview version does fix the issue ....

**Comment by martinlugger** [comment]
Hello,
yes the RZGet_Preview.zip is doing the job.
The fix is working well.
Thank you for fixing the RZGet.exe.
