### ISSUE TITLE
RZ4CM updates with Powershell

### ISSUE THREAD

**Issue by CDB100** [rzander/ruckzuck#129]
Hi, just started with RZ and have the following question. I am using your supplied PS script top check for updates, which is fine, but I would like to know how I can obtain the following from $RZ.Scan, as variables:
Number apps in repository
Number apps detected
Number updates available
Many thanks

**Comment by prisme666** [comment]
when we make a $RZ.Update(), can we have a message when the application to prepare fails, like in the interface (example download failed).

**Comment by rzander** [comment]
RZ4CM is depreciated.
