### ISSUE TITLE
R for Windows 3.4.2

### ISSUE THREAD

**Issue by Blend2** [rzander/ruckzuck#13]
Hi Roger

The correct uninstall string is:

cd $PSScriptRoot;
$proc = (Start-Process -FilePath "$($Env:ProgramFiles)\R\R-3.4.2\unins000.exe " -ArgumentList "/SILENT" -Wait -PassThru);$proc.WaitForExit();$ExitCode = $proc.ExitCode

Greetings
Dani

**Comment by rzander** [comment]
Thanks Dani,

It's fixed... may take a Moment (up to 2Hours) until you see the change...

Regards

Roger
