### ISSUE TITLE
Zoom Outlook Plugin error

### ISSUE THREAD

**Issue by amartin253** [rzander/ruckzuck#131]
Zoom Zoom Outlook Plugin new Version: 5.5.12365
Downloading...ERROR: Signature mismatch on File ZoomOutlookPluginSetup.msi

Looks like Version 5.6.0.42 is out now here: https://zoom.us/client/latest/ZoomOutlookPluginSetup.msi and the script is trying to pull an older version perhaps?

**Comment by rzander** [comment]
Thanks, the Zoom Plugin is updated...
