### ISSUE TITLE
RZGet ignores --exclude "openvpn"

### ISSUE THREAD

**Issue by spec1re** [rzander/ruckzuck#132]
```
RZGet.exe update --all --exclude "openvpn"
OpenVPN Technologies OpenVPN Connect 3.2.2
Downloading...... done.
Installing...... done.
```
No matter what, OpenVPN Connect is installed even when its explicit excluded.

This is on Windows 10 2009 x64, the classic OpenVPN Client is installed and should keep untouched.

Any Idea why this happen or how to stop it?

Thanks.

**Comment by rzander** [comment]
Sorry, but I can't reproduce it... are you using the latest Version V1.7.2.1 from https://github.com/rzander/ruckzuck/releases ?
```PowerShell
RZGet.exe update --list --all
OpenVPN
```
now with an exclude:
```PowerShell
RZGet.exe update --list --all --exclude "OpenVPN"
```
... no result was returned

the same behavior if I skip the "--list" parameter and enforce and update...

**Comment by spec1re** [comment]
Yes latest from here.

```
RZGet.exe update --list --all --exclude "OpenVPN"
OpenVPN
VCRedist2012x86
```

I have **OpenVPN 2.5.0-l601 amd64** installed, but for some odd reason RZGet.exe is installing **OpenVPN Technologies OpenVPN Connect 3.2.2** and ignores --exclude "OpenVPN".

**Comment by amartin253** [comment]
I am finding the same to occur with Snagit. If I have an older version of Snagit installed and I enter:

`RZGet.exe update --all --exclude "Snagit"`

It still insists on installing Snagit 2022 every time

**Comment by rzander** [comment]
Based on the Version I assume you have installed "OpenVPN CE" and not "OpenVPN"...
