### ISSUE TITLE
MusicBrainz Picard update issue

### ISSUE THREAD

**Issue by vertigo220** [rzander/ruckzuck#133]
When updating Picard, it shows a dialog that says 

MusicBrainz Picard is already installed and must be uninstalled before installing this upgrade to version 2.5.6.

Click "OK" to proceed or "Cancel" to cancel this upgrade.

Not sure if it's possible, but it would be ideal if RuckZuck could automatically hit ok for this message, as well as Next (Alt+N), Uninstall (Alt+U), and Finish (Alt+F) on the boxes that pop up to uninstall it.

And then RuckZuck shows "WARNING: Product not detected after installation." afterward, so it didn't even do the install after the uninstall completed. Really a bad design by them.

Edit: When I went to reinstall it from the install page, it gave me the error "Status: Requirements not valid. Installation will not start." Download progress was 0%. I did it again and it worked.

**Comment by rzander** [comment]
The best thing would be, if the vendor provides a setup that does automatically update previous installations. 
Currently the setup.exe is started with parameter "/S"... maybe there are other options to enforce a silent install/update ?
Sending Key strokes during a setup is very ugly (I know there are some packages in RuckZuck that are doing this) and this should be the last option to use....

You can edit and upload the modifications if you think there are better ways to install the product.

**Comment by phw** [comment]
We'll provide a fully silent installer (with the "/S" parameter) for the 2.7 release of MusicBrainz Picard.

Thanks for providing Picard via ruckzuck!
