### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by vertigo220** [rzander/ruckzuck#134]
On the edit screen, perhaps it should say "Start Update(s)..." or "Start Updating..." instead of "Start Installation..." since the apps are already installed, just to avoid any possible confusion, especially with more basic users. Also, once updates are complete, the list should auto-refresh (currently have to go back to main screen then back to verify they're done, and even then not all of them go away, which is another issue).

**Comment by rzander** [comment]
Fixed in : https://github.com/rzander/ruckzuck/commit/750f2f15fe7e16486fe38bcf64c9b772606ab32f
