### ISSUE TITLE
Boxcryptor nicht aktuell

### ISSUE THREAD

**Issue by Blend2** [rzander/ruckzuck#139]
Salut Roger

In deinem Repo ist Boxcryptor 2.44.1485 nicht aktuell. Die aktuelle Version ist  2.45.1556

LG Dani

**Comment by rzander** [comment]
Gefixt...  Du weisst, dass Du das Paket auch selber aktualisieren kannst ? :-)

**Comment by Blend2** [comment]
Ich wollte ein neues Software-Item erstellen. Der Upload war jedoch ausgegraut...?
