### ISSUE TITLE
.Net Framework

### ISSUE THREAD

**Issue by kmohdnawaz** [rzander/ruckzuck#14]
If we search for .net framework then product description shows is 4.6.2 but the version showed is 4.7, i gues this is type, how do i find 4.6.2 version.

**Comment by rzander** [comment]
Thx, typo will be fixed...
RuckZuck is designed to provide the latest Version of a Product which is for ".NET" the Version 4.7.02558.
If it's a real need to have an older Version in the repository, you can create and Upload Version 4.6.x and give it a Shortname like ".NET 4.6"...

Why do you want to install 4.6.2 and not 4.7.1 ?

**Comment by kmohdnawaz** [comment]
Thanks for reply, its my privilege to have word with you. Thanks Again for all your efforts. I am still on 4.5.2 and looking ahead to upgrade to 4.6.2, so i was asking on for 4.6.2. , are you on twitter ?

**Comment by rzander** [comment]
Move on to Win10 ;-) ! Yes, you can follow me on @roger_zander
