### ISSUE TITLE
RZGet WARNING: Product not detected after installation

### ISSUE THREAD

**Issue by MarcoZaino** [rzander/ruckzuck#140]
Good morning,
I noted that some programs aren't detected after installation/update even if they are correctly installed or updated.
I suppose there is a mistake in product release detection with "update --all" options.
Products to be updated doesn't appears with "--list --all" option.
For example:
Cisco Webex LLC Cisco Webex Meetings 41.5.2.15
QGIS Development Team QGIS 3.18.0 'Zrich' 3.18.2

Thanks, Marco@UniUPO

**Comment by rzander** [comment]
- Cisco WebEx does always download latest msi from vendor, in this case there was a newer version available. -> Updated RuckZuck.
- QGis, there was a mistake in the Productname of QGis 3.18.2. Additionally, the Productname includes special characters which can impact the dectection. -> Fixed ProductName in RuckZuck.
