### ISSUE TITLE
Error detecting version JavaRuntime8x64

### ISSUE THREAD

**Issue by juangranados** [rzander/ruckzuck#141]
¡Hi! First of all, thank you for this amazing software.

There is an error when detecting JavaRuntime8x64, new version and old version are the same:

![imagen](https://user-images.githubusercontent.com/6050403/118622801-f0b99080-b7c7-11eb-98a4-f71106490da4.png)

**Comment by rzander** [comment]
If I install "JavaRuntime8x64",  I will get Version "8.0.2910.10"
What happens if you Update your version "8.0.2910.9"  ? do you get "8.0.2910.10" ?
