### ISSUE TITLE
Duplicate VLC Player versions installed if original was a 64-bit MSI

### ISSUE THREAD

**Issue by amartin253** [rzander/ruckzuck#142]
I've noticed if I have the 64-bit MSI of VLC Player installed in my fleet of PCs and I run RuckZuck, it detects a newer version of VLC but doesn't overwrite the 64-bit MSI with the latest version. It leaves that in place and installs a new VLC Player (that in this case is v3.0.14) but is the 32 bit .exe.

Is there any way to modify the detection method in the script to pull the 64-bit MSI download instead? URL path is here: https://get.videolan.org/vlc/3.0.14/win64/vlc-3.0.14-win64.msi 

Adding some photos for visual aid

<img width="1146" alt="Screen Shot 2021-05-18 at 11 31 10 AM" src="https://user-images.githubusercontent.com/62969925/118705723-6d9b3900-b7cd-11eb-9a22-faa512c7a538.png">

<img width="1138" alt="Screen Shot 2021-05-18 at 11 32 24 AM" src="https://user-images.githubusercontent.com/62969925/118705711-6a07b200-b7cd-11eb-9ed2-950176111204.png">

**Comment by amartin253** [comment]
That makes sense to me. And maybe once the MSI version is created, modify the VLC exe detection from detecting the MSI version (so it doesn't try to install as well).

Personally I don't see a need to install the 32 bit version. I have a deployment set up in my SCCM environment right now that is scoped to all PCs with any variant of VLC player installed that then runs this as a pre-install before installing v3.0.12 64 bit MSI.

```
# Check if VLC 32 bit Exists
$WantFile = "C:\Program Files (x86)\VideoLAN\VLC\uninstall.exe"
$FileExists = Test-Path $WantFile
If ($FileExists -eq $True) {Start-Process -Wait -FilePath "C:\Program Files (x86)\VideoLAN\VLC\uninstall.exe" -ArgumentList "/S" -PassThru}
Else {Write-Host "No file at this location"} 
```

**Comment by rzander** [comment]
I have created a "VLC (msi)"... For the update detection it is evaluating product-names that contains "(32-bit)" or "(64-bit)". 
Let me know if it does detect the right type... (it may take a moment until all cached rules are updated).
Maybe with the next version, I do also enforce the MSI and remove the EXE installer...

**Comment by amartin253** [comment]
Amazing! Works perfectly now!

VideoLAN VLC media player 3.0.14 (64-bit) new Version: 3.0.14.0
Downloading...... done.
Installing...... done.
![image](https://user-images.githubusercontent.com/62969925/118872863-e79af300-b89d-11eb-8446-3b5c20f0f297.png)
