### ISSUE TITLE
Meshlab installation do not work

### ISSUE THREAD

**Issue by Mannshoch** [rzander/ruckzuck#143]
Meshlab download and Install it's dependency Microsoft Visual C++ 2015-2019... - 14.29.30037 successfully but is not able to proceed further it seems it freeze on the Status 'Installing dependencies' and Downloaded: 100%

If I right click Meshlab in the main window and click Open download Path... I get an error about a non existing Directory.

**Comment by rzander** [comment]
Fixed, Mashlab was outdated... I have update the package with the latest version.

**Comment by Mannshoch** [comment]
Isn't there an automatism to update ruckzuck if https://github.com/cnr-isti-vclab/meshlab/releases has a new release?

**Comment by rzander** [comment]
someone has to create a new package in ruckzuck... that's not automated.
If packages are running on error during installation, it will end up in a to do list... but MeshLab is not used very frequently.
