### ISSUE TITLE
After Updating CrystalDiskInfo 8.0.0 I got two Installation of this Application

### ISSUE THREAD

**Issue by Mannshoch** [rzander/ruckzuck#144]
After Updating CrystalDiskInfo 8.0.0 I got two Installation of this Application. It seems that I had 32bit version of this software on my PC after the update with RuckZuck I had now also the 64bit installed. It seems Ruckzuck could not replace the 32bit with the 64 bit version.

**Comment by rzander** [comment]
RuckZuck is just the postman who delivers packages, it's not the job of ruckzuck to fix packages it's the job of the vendor...
Do you have the uninstall command for the x86 version ? I can add it as a postinstall task..

**Comment by Mannshoch** [comment]
I have not uninstalled the 32 bit version until now. So If you could tell me how to find this command I willl do it.

**Comment by rzander** [comment]
- In RuckZuck.exe cpress shift and click on "Create new Software-Item".
- Select Crystaldisk 32bit and click on "Create new Software-Item"
- Post the "UnInstallation Script" here

**Comment by Mannshoch** [comment]
`$proc = (Start-Process -FilePath "$(${Env:ProgramFiles(x86)})\CrystalDiskInfo\unins000.exe " -ArgumentList "/SILENT" -Wait -PassThru);$proc.WaitForExit();$ExitCode = $proc.ExitCode`

**Comment by rzander** [comment]
Thanks, I have update the package to run this command before installing the X64 version.
You can try to uninstal the x64 version manually and then do an upgrade again with ruckzuck. It should now remove the x86 version...
