### ISSUE TITLE
Local user Installation KDE-connect is not detectable by ruckzuck

### ISSUE THREAD

**Issue by Mannshoch** [rzander/ruckzuck#145]
I use KDE-Connect also on Windows Desktop. It seems I'm not able to autocreate a Package from this Software.

Webseite: https://kdeconnect.kde.org/download.html
Download Page: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/
UninstallString: C:\Users\Daniela\AppData\Local\KDE Connect\uninstall.exe

So I request for package it here.

**Comment by rzander** [comment]
Attached an JSON File that can be imported in RuckZuck.exe where you see all the details...
[EXP_KDE Connect21.04.2X64.json.zip](https://github.com/rzander/ruckzuck/files/6779535/EXP_KDE.Connect21.04.2X64.json.zip)


..and a Setup.exe to just test in installation...
[KDE Connect_21.04.2_X64_setup.exe.zip](https://github.com/rzander/ruckzuck/files/6779537/KDE.Connect_21.04.2_X64_setup.exe.zip)

Can you test if this app is working when installed from ruckzuck (I recommend to test in on a VM or SandBox) ? 
If yes, we should find a way to automatically parse the url of the latest .exe as the version seems to change very frequently ?!

**Comment by Mannshoch** [comment]
The link to the Download is not correct. The Webpage I mentioned go to the "lastSuccessfulBuild". 

I replaced: 
https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-21.04.2-642-windows-msvc2019_64-cl.exe

With:
https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/642/artifact/kdeconnect-kde-21.04.2-642-windows-msvc2019_64-cl.exe

The Installation now worked without problems. the Application do start and run.

**Comment by rzander** [comment]
Ok, now we are close to get it done  :-)
The challenge now is that the download url does change on a daily base... We have to parse the website (e.g. https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/ ) to find the link to the latest build...
Do you get this done? you can take Firefox or "Citrix Workspace" as an example ... Otherwise I will help ...

**Comment by Mannshoch** [comment]
If you open https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/ you find on the below left corner an RSS feed with the last build. 
https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/rssAll
they link to a page like: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/643/
with that link you could filter the webpage. We need the URL which end to ".exe" and may the hash which ends on ".exe.sha256"
so you get them with:
https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/643/artifact/*.exe/
https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/643/artifact/*.exe.*/
I played around with the filter and got this URL to download the EXE
https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/643/artifact/*.exe/*zip*/kdeconnect.zip
https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/643/artifact/*.exe.*/*zip*/kdeconnect.zip

Is that helpfull for you?

**Comment by rzander** [comment]
In PowerShell I would do it like:
```PowerShell
$uri = "https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/"
$content = Invoke-RestMethod -uri $uri
$search = "windows-msvc2019_64-cl.exe"
$start = $content.IndexOf($search)+$search.length+2
$end = $content.IndexOf("</a>", $start)
return $uri + "artifact/" + $content.Substring($start, $end-$start)
```

.. I will add the PowerShell in the  "URL" file in RuckZuck , so it will always get the latest binaries...

**Comment by rzander** [comment]
KDE Connect is now available in the public Repository: https://cdn.ruckzuck.tools/rest/v2/GetSoftwares?shortname=KDE%20Connect

**Comment by Mannshoch** [comment]
thanks it works!
I only sometimes made some windows batch files. Powershell seems intersting but is a bit more difficult to use.

For the record. I found a REST API page: 
https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/api/

**Comment by Mannshoch** [comment]
... And to complete the title in this issue. What was the cause RuckZuck was not able to found the installed KDE-Connect?

**Comment by rzander** [comment]
- great link with the REST API, will change the code to get the link from there instead of parsing html
- I created the package by installing a KDE-Connect version on a VM and completed the Package in RuckZuck.exe... so I was able to create it..

**Comment by rzander** [comment]
... much simpler:
```PowerShell
$uri = "https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/";
$j = Invoke-RestMethod -uri "$($uri)/api/json"
return $uri + "artifact/" + ($j.artifacts.fileName | Where-Object { $_.endswith('.exe') })
```
