### ISSUE TITLE
Since updating RDP-Manager to v4.9.9.3 ruckzuck list this app everytime as updatable

### ISSUE THREAD

**Issue by Mannshoch** [rzander/ruckzuck#146]
Application: RDP-Manager v4.9.9.3
https://gitlab.com/pdoll/rdpmanager

Shown in Updater: 
![grafik](https://user-images.githubusercontent.com/7795891/124925148-70abec00-dffc-11eb-9938-e300ba2fc195.png)

Shown in Creat new Software ITEM:
![grafik](https://user-images.githubusercontent.com/7795891/124925279-91744180-dffc-11eb-91b3-72be6749c174.png)

**Comment by rzander** [comment]
You have to contact the Software Vendor to create a Package with a valid Version number... If you install "RDP-Manager" with RuckZuck, it does write the version to the registry... but it's not the job of RuckZuck to fix packages ;-)

**Comment by Mannshoch** [comment]
For the record: 
https://gitlab.com/pdoll/rdpmanager/-/issues/634
