### ISSUE TITLE
Feature Request: add Date of last Update to the Software overview.

### ISSUE THREAD

**Issue by Mannshoch** [rzander/ruckzuck#147]
Feature Request: add Date of last Update to the Software overview.

Mockup:
![grafik](https://user-images.githubusercontent.com/7795891/124927167-9d610300-dffe-11eb-9584-2e1b73d8ef2f.png)

**Comment by rzander** [comment]
It's a good hint...
RuckZuck only knows the date when the product was created in the repository, would this still be a benefit ?

**Comment by Mannshoch** [comment]
Yes. **Camstudio** as an example got his last update in 2016. I dont see a security problem her, but a god point to think about.
![grafik](https://user-images.githubusercontent.com/7795891/124954568-83cbb580-e016-11eb-92ef-653a038bb9c3.png)
(As a Replacement I use OBS Studio now.)

**Comment by rzander** [comment]
https://github.com/rzander/ruckzuck/commit/7c316a9dfd0c0b775ffdd4a115fdc92355b102d0
Modify Date added on top/right of each SW:
![image](https://user-images.githubusercontent.com/11909453/125820051-873fdb05-ddd2-43b4-9e17-d6d607e311c8.png)
Preview binaries:
[RuckZuck.zip](https://github.com/rzander/ruckzuck/files/6824600/RuckZuck.zip)

**Comment by Mannshoch** [comment]
Nice!
I would propose to create a little tooltip on the Date. So If you point with your mouse on it, you get a notification.
e.g.
"Date of last seen Software Update. Software without a Date are older than Year XXXX-XX. If an Update Is missing please report "

**Comment by rzander** [comment]
[RuckZuck.zip](https://github.com/rzander/ruckzuck/files/6832557/RuckZuck.zip)
a minor Update...

**Comment by Mannshoch** [comment]
Tested and looks great. Thanks a lot!
