### ISSUE TITLE
Feature Request allow to add Values for Installation variants

### ISSUE THREAD

**Issue by Mannshoch** [rzander/ruckzuck#148]
Some Application appear more than one time in Ruck zuck. I Propose to find a way that there is a possibility to setup values to download and install the needed setup.
![grafik](https://user-images.githubusercontent.com/7795891/125308911-9b19e400-e331-11eb-9824-94c772d70873.png)

**Comment by rzander** [comment]
RuckZuck can handle multiple architectures or languages within a single RuckZuck package. There is no UI to build such packages with RuckZuck.exe, but the JOSN File can handle it and RuckZuck.exe will install the first version that fulfills the requirements... e.g. have a look at [https://cdn.ruckzuck.tools/rest/v2/GetSoftwares?shortname=adobereader%20dc%20mui](https://cdn.ruckzuck.tools/rest/v2/GetSoftwares?shortname=adobereader%20dc%20mui) as an example...  

Some Package exist in a x86 and x64 version to let the user choose which architecture he wants (e.g. VCRedist)... 

The usage of RuckZuck.exe to install Software is just a small percentage... Most installations are coming from enterprises using RZGet.exe / OneGet Provider or other options where no UI exists... So the installation must run silent without any prompts...

**Comment by Mannshoch** [comment]
ah! good to know. I thought about kind of ticks I could do on the page where I could choose the app. 
e.g.
![grafik](https://user-images.githubusercontent.com/7795891/125316769-b89e7c00-e338-11eb-9891-5d5abb00fb6f.png)
