### ISSUE TITLE
JavaScript error when trying to install Teams Machine-Wide Installer

### ISSUE THREAD

**Issue by amartin253** [rzander/ruckzuck#149]
![image](https://user-images.githubusercontent.com/62969925/125363537-a5ce7c00-e325-11eb-8a07-3802cb407a70.png)

The following error seems to occur intermittently on some PCs when trying to upgrade Teams Machine-Wide installer. Not sure if there is a log file I can submit to help track down the root cause or what needs to be fixed to resolve this

**Comment by rzander** [comment]
Teams Machine-Wide Installer is a single MSI.. You may have ask the Vendor what's wrong... Must be something specific on your devices as the package is working fine on other machines...
