### ISSUE TITLE
Error Code 16389 during task sequence capture

### ISSUE THREAD

**Issue by trahald10** [rzander/ruckzuck#150]
Hello,

We have been receiving an error code of 16389 when installing any applications built using RuckZuck during our capture task sequence. Do you know what could be causing this? 

Things I've tried/verified:
- Confirmed that these RuckZuck applications install successfully from within the Software Center (after changing execution policy to bypass)
- Confirmed that non-RuckZuck applications install during our capture task sequence
- Created a brand new capture task sequence. 
- I have set execution policy to bypass in a task sequence step just before RuckZuck application installs and have also confirmed that it is set to Bypass with a: get-executionpolicy command
- I have checked the "Allow this application to be installed from the Install Application task sequence action without being deployed" checkbox.

Thanks!

**Comment by rzander** [comment]
At the end, an Application created with RuckZuck is a standard Application (no hidden secrets)... You have to find the difference from a running Application to the ones that failed... Often its the "Allow this application to be installed from the Install Application task sequence action without being deployed" checkbox... how long have you waited after you checked that box? Check the smsts.log, if the error is comming from the script or from the task sequence before calling the script...

**Comment by trahald10** [comment]
Thanks for your quick reply. I'll try another build and capture and try it again. The error according to smsts.log was:

NotifyProgress received: 16 (Application failed to evaluate)

**Comment by rzander** [comment]
Where and how did you set the powershell execution policy ? -> https://github.com/rzander/ruckzuck/issues/5

**Comment by trahald10** [comment]
I ended up figuring it out. I had to create an SCCM Client policy to set the powershell execution policy to bypass and set that on the 'All Unknown Computers' collection, which was used during the Capture Task Sequence.
