### ISSUE TITLE
Add x64 version of Zoom - Can I add to the existing x86 version or do I create a new package?

### ISSUE THREAD

**Issue by amartin253** [rzander/ruckzuck#153]
https://zoom.us/client/latest/ZoomInstallerFull.msi?archType=x64 is the latest version path for the x64 MSI installer. I couldn't find a way to add a 2nd path in tandem with the existing x86 version but didn't want to submit a new package if I was overlooking something. Thanks!

**Comment by rzander** [comment]
I'm not a zoom user; does it make sense to install the x64 as default ? are there any limitations with the x64 version ?

**Comment by amartin253** [comment]
To be completely honest, while I am an avid Zoom user, the 64 bit client was released sometime around March 2021 and still isn't the default installer version from Zoom's download landing page as shown here: 
![image](https://user-images.githubusercontent.com/62969925/126366286-bd7dcf28-0706-4eb7-a1d5-f9e3f9fe7935.png)

My biggest reason for thinking it should be added to the scope of options in RuckZuck is for companies who do prefer the 64 bit client (which since it is still relatively new, there hasn't been a lot of data to show it is significantly better or worse than the 32 bit client) can get an update from RuckZuck and so it doesn't overwrite the 64 bit version with the 32 bit version.

Probably best to have it be its own separate installer since the GUID is different too
