### ISSUE TITLE
Update of TeamViewer always fails

### ISSUE THREAD

**Issue by creibens** [rzander/ruckzuck#156]
The update of TeamViewer always fails:
![image](https://user-images.githubusercontent.com/27630073/131251242-b9dee7e8-a9f9-4f75-9596-b7690c27ed95.png)

**Comment by rzander** [comment]
"Product not detected.." must not always be a "failure"...
- Pending Reboot ? Do you get the latest version after reboot
- What happens if you install TeamViewer manually ? RuckZuck just starts TeamViewer_Setup.exe /S
