### ISSUE TITLE
ffmpeg through RuckZuck?

### ISSUE THREAD

**Issue by Creanimo** [rzander/ruckzuck#157]
Hi everyone! Great project, really makes initial setup and updates so much easier.

One thing that is always a challenge in my animation projects, is to make sure that the artists have ffmpeg on their machine to be used by other software like OpenToonz. As ffmpeg doesn't have an official installer only "portable" files, I was wondering if (and how) such a software could be packaged with RuckZuck.

This page is linked on the official ffmpeg.org site and can be used to always fetch the most recent release: https://www.gyan.dev/ffmpeg/builds/
This would be the link to the most recent release: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z

But as you can see it is just a 7z file and not an installer. Can RuckZuck still fetch, extract and update these files? I would be very grateful for any help with packaging ffmpeg if this is something that is agreeable for this package manager.

**Comment by rzander** [comment]
Hi, If you can extract and install the Files with PowerShell, you would be able to do it with RuckZuck... 
Check out the "Sysinternals" Package as an example...
Note: You can only get updates if you register the installation in AddRemovePrograms, as this the only place RuckZuck is scanning...
