### ISSUE TITLE
Cleanup script for DWG TrueView

### ISSUE THREAD

**Issue by amartin253** [rzander/ruckzuck#158]
I tested in the edit mode of RuckZuck and this script in the Post Script section will clean up any previously installed versions of DWG TrueView after the latest version is installed. Otherwise, because AutoDesk changes the GUID string every year, the previous version remains on the computer. I tried saving this in the RuckZuck app but wasn't successful. Please add:

 ##Uninstall AutoDesk DWG TrueView 2011
$MSIUninstallArguments = @(
    "/x"
    "{5783F2D7-9028-0409-0100-0060B0CE6BBA}" 
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2012
$MSIUninstallArguments = @(
    "/x"
    "{5783F2D7-A028-0409-0100-0060B0CE6BBA}" 
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2013
$MSIUninstallArguments = @(
    "/x"
    "{5783F2D7-B028-0409-0100-0060B0CE6BBA}" 
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2014
$MSIUninstallArguments = @(
    "/x"
    "{5783F2D7-D028-0409-0100-0060B0CE6BBA}" 
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2015
$MSIUninstallArguments = @(
    "/x"
    "{5783F2D7-E028-0409-0100-0060B0CE6BBA}" 
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2016
$MSIUninstallArguments = @(
    "/x"
    "{5783F2D7-F028-0409-0100-0060B0CE6BBA}" 
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2017
$MSIUninstallArguments = @(
    "/x"
    "{28B89EEF-0028-0409-0100-CF3F3A09B77D}"
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2018
$MSIUninstallArguments = @(
    "/x"
    "{28B89EEF-1028-0409-0100-CF3F3A09B77D}"
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2019
$MSIUninstallArguments = @(
    "/x"
    "{28B89EEF-2028-0409-0100-CF3F3A09B77D}"
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2020
$MSIUninstallArguments = @(
    "/x"
    "{28B89EEF-3028-0409-0100-CF3F3A09B77D}"
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

##Uninstall AutoDesk DWG TrueView 2021
$MSIUninstallArguments = @(
    "/x"
    "{28B89EEF-4128-0409-0100-CF3F3A09B77D}"
    "/passive"
    "/quiet"
    "/norestart"
)
Start-Process "msiexec.exe" -ArgumentList $MSIUninstallArguments -Wait -NoNewWindow

Start-Sleep -Seconds 5

**Comment by rzander** [comment]
Thanks for the feedback... I'm not using DWGView so I have some question:
- Is there any reason for a user/company to use a specific (old) version ? License, Compatibility ?
- Wouldn't it be easier to search in the registry for the uninstall key of installed versions? -> so we do not have to maintain a list of productid's ?

**Comment by amartin253** [comment]
No reason that I can find. Every new release is backwards compatible with its predecessor. As for searching the registry, that may be possible. I created the aforementioned script based on some of the data that was provided from AutoDesk's forums here: https://knowledge.autodesk.com/support/dwg-trueview/learn-explore/caas/sfdcarticles/sfdcarticles/How-to-run-self-extraction-of-DWG-TrueView-2019-install-package-from-Command-Line.html 

As for searching in the registry for the uninstall key, that may be possible however, as of DWG TrueView 2022, AutoDesk changed things up a bit and it requires a more in-depth removal process than its predecessors. Here is the uninstall script for 2022:

https://forums.autodesk.com/t5/installation-licensing/how-to-silently-uninstall-dwg-trueview-2022/m-p/10356890#M254754

**Comment by rzander** [comment]
DWG TrueView is updated:
https://cdn.ruckzuck.tools/rest/v2/getsoftwares?shortname=DWG%20TrueView
