### ISSUE TITLE
Update for ShareX Stalls

### ISSUE THREAD

**Issue by dudefoxlive** [rzander/ruckzuck#159]
I noticed that when trying to install ShareX using Zuckruck from SCCM that the installation takes forever before failing due to timeout. I noticed that the powershell script was running but was just doing nothing. Looking at the script I noticed this line 
`get-process ShareX -ea SilentlyContinue | kill` appears to be asking the user to confirm if the process should be kill. Appending a -f to the kill command forced it to continue and kill the process. `get-process ShareX -ea SilentlyContinue | kill -f`

**Comment by rzander** [comment]
Thanks, I fixed the preinstall command to 
```PowerShell
Get-Process ShareX -ea SilentlyContinue | Stop-Process -force
```
