### ISSUE TITLE
Addon Installed but cant search app as no app is available

### ISSUE THREAD

**Issue by kmohdnawaz** [rzander/ruckzuck#16]
Addon Installed but cant search app as no app is available, i am on .netframeowrk 4.7 and powershell 5.0
![image](https://user-images.githubusercontent.com/7412278/37164260-cc1c5b30-231f-11e8-8586-2d881b35aaa8.png)

**Comment by rzander** [comment]
.NET 4.7 and PS5 is fine. Please check if you are able to connect to https://ruckzuck.tools ; is it the same behavior with RuckZuck.exe ? Is a Proxy required ? Does the Proxy require authentication ?

**Comment by kmohdnawaz** [comment]
Yes Mate, it was Proxy issue, i gave direct  proxy in Internet options and it started working.
