### ISSUE TITLE
RZGet Powershell convertfrom-json issue

### ISSUE THREAD

**Issue by Jivaross** [rzander/ruckzuck#161]
I've been using this oneliner in powershell for about a year now and it used to work to obtain a list of all ShortName:

```powershell
((& "C:\RZGet.exe" search | convertfrom-json) | Select ShortName | Out-String -Stream | foreach {$_.trimend()} | Where {$_ -ne ''} | Where {$_ -ne '---------'} | Where {$_ -ne 'ShortName'})
```
But now I receive a error ArgumentException from convertfrom-json:

![image](https://user-images.githubusercontent.com/57919034/142227807-172e15f0-8e2c-4b91-abba-b8deca1f7f88.png)

What am I doing wrong?

**Comment by rzander** [comment]
There was an encoding Issue in the QNAP packe description... There where non ASCII double quotes which where translated to regular double quotes... this caused an invalid JSON. 
You can now run just 
```PowerShell
(&"C:\RZGet.exe" search | convertfrom-json).Shortname | Sort-Object
```

**Comment by Jivaross** [comment]
Thank you!
