### ISSUE TITLE
Wrong MSI Code in package "Adobe Acrobat Reader DC (64-bit) - German"

### ISSUE THREAD

**Issue by anl-do** [rzander/ruckzuck#162]
Hi,
I have seen a wrong MSI product ID.
The API Call delivers: MSIProductID   : {AC76BA86-1033-1033-7760-BC15014EA700}
The correct ID is: {AC76BA86-1031-1033-7760-BC15014EA700}

best reagrds
Andreas

**Comment by rzander** [comment]
Fixed... it was only wrong on the attribute "MSIProductID", detection and uninstall key was correct ...
