### ISSUE TITLE
Application update + available/required

### ISSUE THREAD

**Issue by Joriempie** [rzander/ruckzuck#163]
I just started using RuckZuck for ConfigMgr.

I saw that there was a update available for TeamViewer. So I hitted the "there are currently (value) updates available". After my select I have chosen the "Create App" button. After that RuckZuck was downloading and creating the new version into my SCCM environment.

I immediately noticed that it made a separated deployment for the newer version of TeamViewer. And it didn't superseded the older version.

Also the other thing which I'm not sure about is to create apps in RuckZuck for available or required. For example I would like to make TeamViewer required for the whole company. And only make PowerBI available. It is possible to do this with RuckZuck? I tried to redeploy to the RuckZuck created User Collection with the status required. But after a update it went back to available.

**Comment by rzander** [comment]
RZ4CM does not create any supersedence for you. You should first test the new app before you send it to production.

Out-of-the-box RZ4CM creates available deployments, targeting user collections. You are free to deploy the app to a device based collection as required.. but again, you should first test the app before you deploy something required to your devices...
