### ISSUE TITLE
The catalog response of the RestAPI switches to old versions and back again.

### ISSUE THREAD

**Issue by pacmor** [rzander/ruckzuck#166]
I have noticed a strange behavior from the [catalog api.](https://cdn.ruckzuck.tools/rest/v2/getcatalog) From time to time the api answer for e.g. "MSOpenJDK11-x64" change back and forth. 

The answers switch always between these two:

```
{
    "Timestamp": "2022-01-25T18:20:03.8745458Z",
    "Downloads": 21,
    "IconHash": "9qZnwEWv9cEHKPe3PRJx3QJ5B",
    "Manufacturer": "Microsoft",
    "ModifyDate": "2021-11-02T07:13:18.9014458Z",
    "ProductName": "Microsoft Build of OpenJDK with Hotspot 11.0.13+8 (x64)",
    "ProductURL": "TBD",
    "ProductVersion": "11.0.13.8",
    "ShortName": "MSOpenJDK11-x64",
    "Categories": [
        "Runtime"
    ],
    "SWId": 21306433
}
```

```
{
    "Timestamp": "2022-02-04T10:13:47.9251165Z",
    "Downloads": 0,
    "IconHash": "9qZnwEWv9cEHKPe3PRJx3QJ5B",
    "Manufacturer": "Microsoft",
    "ModifyDate": "2022-02-04T10:13:47.901181Z",
    "ProductName": "Microsoft Build of OpenJDK with Hotspot 11.0.14+9 (x64)",
    "ProductURL": "https://docs.microsoft.com/en-us/java/openjdk/download",
    "ProductVersion": "11.0.14.9",
    "ShortName": "MSOpenJDK11-x64",
    "Categories": [
        "Runtime"
    ],
    "SWId": 22035614
}
```

Only for a short time the api answers with version "11.0.13.8" and then it quickly switches back to version "11.0.14.9"

**Comment by rzander** [comment]
The [catalog api](https://cdn.ruckzuck.tools/rest/v2/getcatalog) is using a content delivery network (CDN), which caches the requests. As the MSOpenJDK11 was updated a few hours ago, it seems that some nodes in the CDN cache have the updated version and some still the old....  Give it a few hours and all nodes should have the new version.

On the Client-Side, the catalog is additionally cached in %TEMP%\rzcat.json... which sometimes also need so time to "realize" that there is an updated version.. Just if you wonder why you don't see the latest version in RuckZuck.exe ....

**Comment by pacmor** [comment]
Thanks for the quick reply. That explains my issues.
