### ISSUE TITLE
Are you reviewing every new repository entry/update? 

### ISSUE THREAD

**Issue by RichardEb** [rzander/ruckzuck#17]
Hey

Are you reviewing every new repository entry/update?  So no one can inject a url to a virus download?

**Comment by rzander** [comment]
Yes, every change will be reviewed and tested on a machine with AV. The tool does also check file signatures or hashes to guarantie the file integrity. All sources must come from the vendors web site or from a trusted site (as some vendors do not host their own files).

**Comment by RichardEb** [comment]
Thank You
