### ISSUE TITLE
OSRequirementsX64 pour RZ4CM.exe

### ISSUE THREAD

**Issue by prisme666** [rzander/ruckzuck#171]
Hello,
What is the parameter for OSRequirementsX64  for Windows 11 X64 (RZ4CM.exe)
example : Windows/All_x64_Windows_11_and_higher_Clients
Or Windows/All_x64_Windows_11_Client
Did it works ?
Thanks,

**Comment by rzander** [comment]
It's "**Windows/All_x64_Windows_11_and_higher_Clients**" but it should now be part of the latest version https://github.com/rzander/ruckzuck/releases
