### ISSUE TITLE
rzget update libreoffice: fails (repo outdated?)

### ISSUE THREAD

**Issue by m1027** [rzander/ruckzuck#172]
rzget update libreoffice fails:

`The Document Foundation LibreOffice 7.3.2.2 7.3.2.2
Downloading...
ERROR: download failed... LibreOffice_7.3.2_Win_x64.msi
`

It seems that libreoffice has been updated to 7.3.3 or so.

Please tell if this is not the place to post such issues.

Thanks for this awesome app.

**Comment by rzander** [comment]
Fixed. LibreOffice was updated to version 7.3.3.2.
