### ISSUE TITLE
Deployment Type Name

### ISSUE THREAD

**Issue by DJKatastrof** [rzander/ruckzuck#174]
Hi!

Is there anyway to change the deployment type name?
So you can read the logs easier

Regards

![image](https://user-images.githubusercontent.com/64254359/171400451-7467e28b-3e97-4555-8762-6ba323808334.png)

**Comment by rzander** [comment]
What is the problem with the current name ?

**Comment by djkatastrof** [comment]
Pretty hard to know in the logs which app is deploying. Of course that could be changed manually afterwards but easier if its automated. :)

`+++ Did not detect app deployment type Install_X64(ScopeId_F87F2958-CCDA-4622-901A-BF64E5602896/DeploymentType_e368f819-ccd9-45e5-a950-8e1002d1c1cb, revision 1) for system.`

**Comment by rzander** [comment]
But I think it's a topic you have to discuss with Microsoft ... They do not log the Application-Name, only the name of the Deployment-type...

**Comment by djkatastrof** [comment]
I think we can close this one :) 

Mind if I as another question?
I tried updating existing applications created by RuckZuck but "Update existing applications" is greyed out. 
Got full rights on DB as well.
Tried running powershell also. Any ideas? :)
![image](https://user-images.githubusercontent.com/64254359/172567246-c596182b-7222-4c0f-a7f0-10f20bc8300c.png)

**Comment by rzander** [comment]
I do no longer have access to an SCCM environment... Do you have configured the "CM_SQLServer","CM_SQLServerDBName" and "CM_Server" in RZ4CM.exe.config ? -> https://github.com/rzander/ruckzuck/wiki/RuckZuck-for-ConfigMgr#configuration

**Comment by djkatastrof** [comment]
Hi,

Yes, all is configured. 
I can create applications and deploy them as well :)
