### ISSUE TITLE
AnyDesk old version being promoted as new

### ISSUE THREAD

**Issue by warp16** [rzander/ruckzuck#175]
RuckZuck is incorrectly showing AnyDesk 7.0.9 as newer than 7.0.10. Probably because of the weird version string used ("ad 7.0.9" with a space and "ad7.0.10" without a space.

![image](https://user-images.githubusercontent.com/12633352/172321360-21bc9a3e-8b90-4545-b4ff-25592c622cbf.png)

**Comment by rzander** [comment]
Yes, RuckZuck can only compare real Version-Numbers... everything else is detected as "old".  AynDesk is now updated in RuckZuck, so you should no longer see this detection...

**Comment by warp16** [comment]
Confirmed fixed, thank you!
