### ISSUE TITLE
Impossible to Create Adobe Reader Package to Intune

### ISSUE THREAD

**Issue by OriginalGoschi** [rzander/ruckzuck#176]
Hi,
i'm trying to deploy an Adobe Reader DC Package to Intune but it does not work. The MUI Version is working.

i'm getting this error in the end:

Invoke-WebRequest : "System.Object[]" kann nicht in den Typ "System.Uri" konvertiert werden, der für den Parameter
"Uri" erforderlich ist. Die angegebene Methode wird nicht unterstützt.
In C:\Users\tgosd\AppData\Local\Temp\intunewin\RZ4Intune.ps1:1240 Zeichen:24                                            + Invoke-WebRequest -Uri $rzSW.iconURL -OutFile "$($sourceFolder)\logo. ...                                             +                        ~~~~~~~~~~~~~                                                                                      + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException                           + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

ERROR  The setup file you specified cannot be accessed.

What did i wrong?

Best Regards
Tobias

**Comment by rzander** [comment]
Which Package are you trying : "AdobeReader DC" or "Adobe Acrobat Reader DC (64-bit)" ?

**Comment by OriginalGoschi** [comment]
Both

**Comment by rzander** [comment]
"Adobe Acrobat Reader DC (64-bit)" is special.. so that would make sense if this does fail... But I will try. Have you tried the "preview" Version of RZ4Intune.exe from here: https://github.com/rzander/ruckzuck/releases/tag/1.7.2.4 ?

**Comment by Stensel8** [comment]
I've written a simple script to download the packages for Microsoft Intune 🙂

Sorry for the late reply 🥲
