### ISSUE TITLE
RZ4CM - unable to create and download Microsoft Edge Webview2 Runtime

### ISSUE THREAD

**Issue by csigno1204** [rzander/ruckzuck#177]
Hi, 
I am trying to download and install Microsoft Edge Webview2 Runtime, version 102.0.1245.33 and it is stuck to "Connecting ConfigMgr..." status. It doesn't go further. The download is not done. The connection and creation of folder in CM neither. 

Any suggestions on how to troubleshoot that? Some old versions were working fine. Other applications are working fine.

I tried to update all through powershell instead of GUI, and it seems that I've got a mix between Edge and the Webview runtime, based on the last picture. Any idea how to solve it? 

![image](https://user-images.githubusercontent.com/90890699/173007280-32dd1e36-a256-4a4a-afb3-c42ccc27b1f4.png)
![image](https://user-images.githubusercontent.com/90890699/173007364-e4a326de-843c-4f39-9ae3-c1c572abeb7e.png)
![image](https://user-images.githubusercontent.com/90890699/173031312-bc30d26d-0df6-4a59-aa84-7080879fe832.png)

**Comment by rzander** [comment]
Have you tried to update to the latest Version of RZ4CM ?  https://github.com/rzander/ruckzuck/releases
Other Packages are working ?

**Comment by csigno1204** [comment]
Sorry, I left the issue opened, but that was fix long time ago by reinstalling the tool. Thanks a lot!
