### ISSUE TITLE
SCCM Plugin Not Finding Application Updates

### ISSUE THREAD

**Issue by matty1086** [rzander/ruckzuck#18]
RZ4CM.exe Version: 1.6.1.4

I came across this tool and love that it can automate such a large portion of my job in no time. Over the weekend, I had RuckZuckForCM create over 30 applications.

Over the past couple of days, I've seen that the RuckZuck repository has updated some of the applications that I created.

When I launch the CM Plugin, it says that "there are currently no updates available...", though briefly flashes that it's checking.

I've configured to the CM_SQLServer and the CM_SQLServerDBName variables in the config and confirmed via SQL profiler that the SQL query executes as expected against the v_configurationitems view when the plugin is launched to get the current list of applications in SCCM that were generated with RuckZuck. Running this query manually returns the ~30+ application results as expected.

Is there a delay before the SCCM plugin will show that there are application updates? I see that the PowerShell methods were removed so updating that way is no longer possible. Am I missing something? Is there a different way to update applications?

Thank you!

**Comment by rzander** [comment]
Do you have an %TEMP%\RZError.txt File with some errors ?
You can also try V1.6.1.5 from https://github.com/rzander/ruckzuck/releases which has some improvements in the Update detection (Backup your .config file !!)

**Comment by rzander** [comment]
There is no delay, but I've seen some cases where the detection did not return any results on first run... mostly on the second run it was fine... IF you do not get a error in %TEMP%\RZError.txt, I can create a DebugVersion to log mor details...

**Comment by matty1086** [comment]
%TEMP%\RZError.tx does not exist after I run the tool.

I've updated to 1.6.1.5 but am getting the same result.

**Comment by rzander** [comment]
so at least no exception… I will create a debug-version with logging…

**Comment by matty1086** [comment]
Thank you, that was fast!
Attached is the resulting file.

[RZDebug.txt](https://github.com/rzander/ruckzuck/files/1985170/RZDebug.txt)

**Comment by rzander** [comment]
In %Temp% there is an RZcat.json which represents the Repository. If it does not exists, you may not have Access to the RuckZuck Repository or it's outdated -> delete %temp%\RZcat.json it will be recreated when starting RZ4CM.exe

**Comment by matty1086** [comment]
Deleted the json and relaunched. The file was recreated but still no updates found.

**Comment by rzander** [comment]
[RZ4CM.zip](https://github.com/rzander/ruckzuck/files/1985204/RZ4CM.zip)
At least it's not an SQL Problem as you have 33 Applications with a RuckZuck ID...  For some reason it does not compare the items with the Repository...

Attached another RZ4CM.exe with more logging...

**Comment by matty1086** [comment]
Updated debug log:

[RZDebug.txt](https://github.com/rzander/ruckzuck/files/1985215/RZDebug.txt)

**Comment by rzander** [comment]
5/8/2018 11:41:00 AM;S0;Repository Items: 
0
… the tool does not see a Repository.. In the UI , you get the list off Applications?

**Comment by matty1086** [comment]
Yes. Items show up for me to create as expected. 

![image](https://user-images.githubusercontent.com/17831198/39776247-15b39cda-52b5-11e8-9913-f497fe3bf3cc.png)

**Comment by rzander** [comment]
[RZ4CM.zip](https://github.com/rzander/ruckzuck/files/1985256/RZ4CM.zip)
Super strange… it starts scanning for updates before the repository is loaded..
Can you do another test (attached File)

**Comment by rzander** [comment]
[RZ4CM.zip](https://github.com/rzander/ruckzuck/files/1985278/RZ4CM.zip)
You must have a superfast or super poor machine… Never had this Issue.

Attached a Version where Scanning should wait until Repository is loaded...

**Comment by rzander** [comment]
This Bug also affects the standalone tool. The update detection does not propperly wait until the Repository is loaded… will fix that also on RuckZuck.exe

**Comment by rzander** [comment]
[RZ4CM.zip](https://github.com/rzander/ruckzuck/files/1985368/RZ4CM.zip)
Ok, will create a V1.6.1.6 in the next days.. The attached File contains the fix but does not create a debug log.

thank you for your patience

**Comment by matty1086** [comment]
Thank you. I'll use the non-debug version and be on the lookout for the official release. Thank you for the quick fix/support!
