### ISSUE TITLE
RuckZuck OneGet Provider: Update missing updates with excludes

### ISSUE THREAD

**Issue by killerkarnickel404** [rzander/ruckzuck#181]
Hello,

with RZGet you can update with 
"RZGet.exe update --all --exclude "<Shortname>;[<Shortname2>]"" 
everything except exceptions.

Is this also possible with 
"Find-Package -ProviderName RuckZuck -Updates" ?

**Comment by rzander** [comment]
With ```Find-Package -ProviderName RuckZuck -Updates``` you will get a list of Updates; then you can implement a logic to exclude  whatever you want... before you trigger an ```Install-Package``` ...

[find-package](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/find-package?view=powershell-7.2) does not provide an **exclude** (as far as I know)...
