### ISSUE TITLE
Automatic task kill possible after installation?

### ISSUE THREAD

**Issue by killerkarnickel404** [rzander/ruckzuck#182]
Hello, 

with some programs the program starts automatically after the installation? 
Can this be prevented? Or alternatively run taskkill after installation?

Example program where it is currently happening:
PicPick https://cdn.ruckzuck.tools/rest/v2/getsoftwares?shortname=PicPick 
But there are more.

**Comment by rzander** [comment]
The best option would be if the software vendor provides a way to prevent this... I don't know PicPick, maybe there is an option ?!
RuckZuck should not be the tool to fix installer issues, but if you have some real arguments why a "taskkill" does help after the PicPick installation... ?!

**Comment by killerkarnickel404** [comment]
Unfortunately, there does not seem to be an option that prevents the program from starting after installation. 

The idea with TASKKILL comes from here.
https://silentinstallhq.com/picpick-silent-install-how-to-guide/

**Comment by rzander** [comment]
Task-Kill is implemented in PicPick
