### ISSUE TITLE
Docker Desktop: Signature mismatch

### ISSUE THREAD

**Issue by davem365** [rzander/ruckzuck#184]
Hi Roger,

When i want do download the Docker Desktop application i receive the following Status: ERROR: Signature mismatch on File Docker Desktop Install.exe.

I also receive the same error when im creating a new software-item with the newest version.

**Comment by rzander** [comment]
I've seen some issues on some devices (mostly VM's), where the signature of the downloaded files seems to be broken, or windows cannot verify the signature... Download the file directly and check if windows detects the signature as "OK"...
![image](https://user-images.githubusercontent.com/11909453/179392047-d5ffa897-72d6-4078-8b5f-8ac3400dd167.png)
If this is not the case, RuckZuck will also skip the downloaded files...

**Comment by rzander** [comment]
Is the signature of these manually downloaded Files "OK" ?
![image](https://user-images.githubusercontent.com/11909453/182462601-cb9ef8ef-bc8f-4974-a23d-a6f7c54d382b.png)

**Comment by davem365** [comment]
Hi Roger,

Your right, its working with another machine. Thanks & regards,
Dave
