### ISSUE TITLE
Lenovo System Update hangs on update

### ISSUE THREAD

**Issue by maximilian301** [rzander/ruckzuck#185]
Hello
we use RZ for Intune and it works great for several apps we deploy in our company.
But when we click on "Lenovo System Update" that is shown in the apps that need an update, the "RuckZuck installation Queue" window opens, but nothing else happens anymore. It status sais "waiting" and "Donwnloaded" stays at 0%. There is no error message show.
It worked in the past, but not for several moths now.
Other apps update very good, only this one hangs.

![rz1](https://user-images.githubusercontent.com/109512479/179475175-2f21836d-1cfb-461a-8002-3b3d01223f23.jpg)

**Comment by rzander** [comment]
Is RZ4Intune running on a Lenovo Device ? I think, the PreReq check is still active on RZ4Intune... (Not tested, just guessing)

**Comment by maximilian301** [comment]
Good tip, I was using rz4intune on a virtual machine and was not aware that for updating an intune app the local hardware has to fit (and the program has to be an old version or not installed).
I now used rz4intune on a Lenovo PC. I uninstalled Lenovo System Update, as it had the newest version and afterwards it successfully downloaded the software and created a new intune app for Lenovo System Update.
Thank you very much for your help.

One question: Does it make sense to have a dependency to the local system when checking and updating intune apps?

**Comment by rzander** [comment]
Well, for the most packages, it does not make sense to check the PSPreReq.... But some RuckZuck Apps have multiple installation types (e.g. [AdobeReader DC MUI](https://cdn.ruckzuck.tools/rest/v2/getsoftwares?shortname=AdobeReader%20DC%20MUI)), where the PSPreReq is used to determine which Installation-Type is used... otherwise you would end up with multiple applications in intune with the same name...  

I will keep it in mind, maybe I will change this behavior in the future...

**Comment by maximilian301** [comment]
Do I understand right, the PC where I run rz4intune defines which Adobe Reader MUI installation language is chosen and only this language is packed in the intune app? I thought the final client system defines the language of apps like Adobe reader and the MUI app has still the possibility for all of them?
Ok, then I will definitively have to take more care on the PC where rz4intune runs on and need one with English and one with German OS.

**Comment by rzander** [comment]
AdobeReader DC MUI, has two packages, one with a full installation and one that only install the update. If the PC you run RZ4Intune does have an "AobeReader DC MUI" installation, then it will only create a Package to update existing installations... In the case, the MUI Package contains a set of Languages...

"FireFox MUI" does detect the language of the Host running RZ4Intune and only downloads this Language.  In Intune the Package is not MUI, it's a fixed Language, from the Host running RZ4Intune...
