### ISSUE TITLE
Chrome, Adobe Reader Signature Mismatch

### ISSUE THREAD

**Issue by CC-PatrickC** [rzander/ruckzuck#186]
I am currently using a script to run RZGet to install a few programs. The computers are fresh builds and have nothing other than Win10 on them. When it comes to Google Chrome and Adobe Reader. I get this message "ERROR: Signature mismatch on File googlechromestandaloneenterprise64.msi" and ERROR: Signature mismatch on File AcroRdrDCUpd2200120169.msp.

These are line from the script. 
RZGet.exe install "Google Chrome"
RZGet.exe install "AdobeReader DC"

**Comment by rzander** [comment]
Maybe same issue as here https://github.com/rzander/ruckzuck/issues/184
Download the File manually and check if windows accepts the file signature as trusted… I think there is an Issue on Machines that are not uptodate… Have you installed all current updates.

**Comment by CC-PatrickC** [comment]
I do that after I run RZGet. I will try to update Windows before and see if that fixes it.

**Comment by CC-PatrickC** [comment]
I was able to download and install the programs without any issues. I have updated Windows to fully and still getting the error message.

**Comment by rzander** [comment]
I have updated the way the signature is checked, can you try with the version 1.7.2.5 https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5
It's not a Ruckzuck issue, if the OS does not validate the signature of a file, So I would still search for the reason why this happens...

**Comment by CC-PatrickC** [comment]
That seem to fix it. Not sure why it was reject it. I was able to download via RuckZuck and their website without issues.

Also love the new look to RZGet. Thanks for your time rzander. Love RuckZuck. Makes my job a whole lot easier..
