### ISSUE TITLE
API key request

### ISSUE THREAD

**Issue by grantemsley** [rzander/ruckzuck#192]
I've been using the ruckzuck API in a little script I wrote to find updates for applications on my MDT server. How would I go about getting an API key?

Thanks!

**Comment by rzander** [comment]
Send me an email to roger at zander.ch...

**Comment by rzander** [comment]
Why do you need "GetSoftware" to detect updates.. All the Information you need should be in "GetCatalog" (Manufacturer, Name, Version) ?  "GetSoftware" is only needed if you want to install/download a package...

**Comment by grantemsley** [comment]
I'll send you an email to discuss further.

I'm trying to kind of emulate the way your ConfigMgr plugin works - downloading the install files to the MDT server and writing a script to install them. So that's where the need for the GetSoftware part comes from.
