### ISSUE TITLE
Intune - App Creation not working

### ISSUE THREAD

**Issue by new-it** [rzander/ruckzuck#194]
Since yesterday I cannot create Intune Apps with RuckZuck for Intune Version 1.7.2.4.

![2022-08-16_09h15_05](https://user-images.githubusercontent.com/15217438/184820462-8eb1877c-1951-445b-b9a3-3a3b6d1ba38e.png)

I tried it several times with Git and Jabra Direct, also with the old version 1.7.2.1 it's the same behavior. And I also logged on several times, the Azure AD shows - everything fine.

![2022-08-16_09h18_12](https://user-images.githubusercontent.com/15217438/184820619-18f5423b-b176-4d89-bb1e-ab785486e7dc.png)

**Comment by rzander** [comment]
Seems the same problem as with RZ4Cm https://github.com/rzander/ruckzuck/issues/193
Will create an updated version....

**Comment by new-it** [comment]
Yes it's working now :). Thanks a lot for the quick fix.

**Comment by new-it** [comment]
But it looks like updated versions are not hidden.

![2022-08-17_12h56_53](https://user-images.githubusercontent.com/15217438/185102416-0128ce51-e9e2-4ffe-9420-da5da9302678.png)

**Comment by rzander** [comment]
RZ4Intune updated on https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5
It does now:
1) get all Apps from MEM where notes contains "ShortName"
2) If "ShortName" is available in Ruckzuck Catalog and
2a) Notes:Version does Match with the Catalog = it's an existing app
2b) Notes:Version does not match with Catalog = it's an outdated version

**Comment by new-it** [comment]
Yeah, now it seems to be fixed. Thanks a lot.
