### ISSUE TITLE
APIKey request

### ISSUE THREAD

**Issue by juangranados** [rzander/ruckzuck#195]
Hi Roger!

First of all, thanks for your amazing API!

I wrote a small PowerShell script to install software using RuckZuck API in my company because we are not allowed to use external apps.

When I write and test a script, I usually upload it to GitHub to contribute in a small way with the comunity, [here is my script](https://github.com/juangranados/powershell-scripts/tree/main/Install%20Software)

Can I continue using your API please?

Thank you very much!

**Comment by rzander** [comment]
Can you please send me an email to: roger at zander . ch

**Comment by rzander** [comment]
I'm not very happy with the way you detect updates, as you always run a "getSoftware" even if the software is already installed... ;-) I recommend to reduce to call "getSoftware" as much as possible. You can e.g. check if the Manufacturer + ProductName + Version exists (values from "getCatalog") in the Registry and only call "GetSoftware" if this is not the case...  If you run your script once a day on a few PC's... no problem... but if you trigger it on many devices on a schedule, it may impact the RuckZuck service... 

If you are not allowed to use external apps, you can fork "RZGet.exe" and compile and sign it internally, then you have all the logic to detect updates out-of-the-box.. ?!

**Comment by juangranados** [comment]
Hi, Zander!

> I'm not very happy with the way you detect updates, as you always run a "getSoftware" even if the software is already installed... ;-) I recommend to reduce to call "getSoftware" as much as possible. You can e.g. check if the Manufacturer + ProductName + Version exists (values from "getCatalog") in the Registry and only call "GetSoftware" if this is not the case... If you run your script once a day on a few PC's... no problem... but if you trigger it on many devices on a schedule, it may impact the RuckZuck service...
> 
> If you are not allowed to use external apps, you can fork "RZGet.exe" and compile and sign it internally, then you have all the logic to detect updates out-of-the-box.. ?!

I will modify it as you sugested!
First call https://{URL}/getcatalog and check if software is installed before call GetSoftware

> Can you please send me an email to: roger at zander . ch

Email sent!
