### ISSUE TITLE
Invoke-RestMethod gives (401) unauthorized. Was working fine a few weeks ago

### ISSUE THREAD

**Issue by hotzenwalder** [rzander/ruckzuck#196]
Since last week every time we try to package an application with RuckZuck for Intune it starts downloading the app, but then gives an error in Powershell and just quits. 

![2022-08-23 20_01_27-Window](https://user-images.githubusercontent.com/78266646/186231929-e67dac2c-87fe-4f4b-a171-6edd58080257.png)

I have no idea what is going wrong, nothing was changed on our end. Only thing that comes to mind after reading other issues is we might be blacklisted, but to my knowledge we are using the application as it is intended. Could you tell us what might be behind this error?

`Invoke-RestMethod : The remote server returned an error: (401) Unauthorized.
At C:\Users\*******\AppData\Local\Temp\intunewin\RZ4Intune.ps1:1224 char:9
+ $rzSW = Invoke-RestMethod -Uri "$($url)/rest/v2/getsoftwares?shortnam ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
Invoke-WebRequest : Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Users\*******\AppData\Local\Temp\intunewin\RZ4Intune.ps1:1240 char:24
+ Invoke-WebRequest -Uri $rzSW.iconURL -OutFile "$($sourceFolder)\logo. ...
+                        ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-WebRequest], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid DateTime."
At C:\Users\*******\AppData\Local\Temp\intunewin\RZ4Intune.ps1:1255 char:89
+ ... e" = "application/json"; "Authorization" = "Bearer $($args[1])" ; "Ex ...
+                                                          ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException`

**Comment by grantemsley** [comment]
If you're using official tools, update them. If you're using your own scripts, you'll need an API key.

They recently locked out some of the APIs to prevent people from hammering them excessively and putting a lot of load on the servers. The apps have been updated to work still.

**Comment by rzander** [comment]
Replace RZ4Intune.exe with this one: https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5

**Comment by hotzenwalder** [comment]
Thanks for the quick fix. The new version works as expected again. We are not using our own scripts, just the RZ4Intune.exe
