### ISSUE TITLE
Ruckzuck downloads but stops installing after 1 install

### ISSUE THREAD

**Issue by Willieworteljes** [rzander/ruckzuck#198]
Ruckzuck 1.7.2.5 stops installing after the first download. It does download the others but never starts installing/updating on Win 11.

**Comment by Willieworteljes** [comment]
[image: image.png]
 It just doesn't continue installing FreeMind in this case.
Cheers,
Wil Bremers
www.IDEE.NU

M +31.620 392 048
Admiralengracht 63-1
1057 EP Amsterdam


Op wo 31 aug. 2022 om 16:42 schreef Roger Zander ***@***.***>:

**Comment by Willieworteljes** [comment]
Yes, I have the same with updates.



Op do 17 nov. 2022 om 15:34 schreef Claus Reibenstein <
***@***.***>:

**Comment by rzander** [comment]
I can confirm that there is a deadlock in the current version ... If someone knows a way to reproduce it (always), let me know.
When multiple installation stuck, you can press "F5" to refresh and most of the time the installation will start... just as a workaround...

**Comment by rzander** [comment]
Should be fixed in https://github.com/rzander/ruckzuck/releases/tag/1.7.3.0
