### ISSUE TITLE
No Deployment Type is being created

### ISSUE THREAD

**Issue by onazim** [rzander/ruckzuck#199]
Hello rzander!

Unfortunately we have the problem that we cannot create any new software packages via RuckZuck. The entry in SCCM in the applications is created, but no package is downloaded when the software entry is created, in which the deployment type and the corresponding software are stored.

In the RZError.txt logs we have the following information:

`09.09.2022 13:49:03;F239E1The SELECT permission was denied on the object 'v_ConfigurationItems', database 'CM_DHH', schema 'dbo'.
SQL:;WITH XMLNAMESPACES ( DEFAULT 'http://schemas.microsoft.com/SystemCenterConfigurationManager/2009/AppMgmtDigest')   SELECT RZID, Shortname, Bootstrap, [Version] FROM  ( SELECT  SDMPackageDigest.value('(/AppMgmtDigest/Application/SoftwareVersion)[1]', 'nvarchar(MAX)') as [Version], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Bootstrap"]/@Value)[1]', 'nvarchar(MAX)') [Bootstrap], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Shortname"]/@Value)[1]', 'nvarchar(MAX)') [Shortname],  RIGHT(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="SWID"]/@Value)[1]', 'nvarchar(MAX)'), LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="SWID"]/@Value)[1]', 'nvarchar(MAX)')) - 2) AS RZID, vCI.CI_ID FROM v_ConfigurationItems as vCI WHERE CIType_ID = 10 and IsLatest = 1 and LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomId)[1]', 'nvarchar(MAX)')) > 2  ) as app WHERE RZID is not null
Connection:Data Source=ham-msc-cm1;Initial Catalog=CM_DHH;Integrated Security=True
09.09.2022 13:49:38;F239E1The SELECT permission was denied on the object 'v_ConfigurationItems', database 'CM_DHH', schema 'dbo'.
Data Source=ham-msc-cm1;Initial Catalog=CM_DHH;Integrated Security=True
RZ0
09.09.2022 13:49:38;F239E1The SELECT permission was denied on the object 'v_ConfigurationItems', database 'CM_DHH', schema 'dbo'.
Data Source=ham-msc-cm1;Initial Catalog=CM_DHH;Integrated Security=True
RZ0
`

We have not made any changes to the permissions. Are you already familiar with this error pattern and do you have a solution suggestion for us?

Many thanks in advance and best regards!
Olaf

**Comment by rzander** [comment]
You have to install the latest version: https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5

**Comment by onazim** [comment]
Hi rzander!

thank you for your reply. Updating to the latest Version fixed the Problem right away.

Best regards!
Olaf
