### ISSUE TITLE
Private Repository Support

### ISSUE THREAD

**Issue by dkattan** [rzander/ruckzuck#20]
To handle situations where licensing is embedded in the installer, it would be nice if there was support for private repositories.

**Comment by rzander** [comment]
at least an RZ. Server version which caches binaries is now available: https://github.com/rzander/ruckzuck/releases/tag/1.7.0.0

**Comment by rzander** [comment]
https://github.com/rzander/ruckzuck/wiki/RuckZuck-Server-with-custom-Repository
Please leave feedback if fulfills your requirements...
