### ISSUE TITLE
Lenovo System Update

### ISSUE THREAD

**Issue by RobertEbbrecht** [rzander/ruckzuck#200]
Hi Roger,

first of all great job you are doing for years now! Client Center, RZ4CM, RZ4Intune are always part of my trainings to introduce students to usefull tools besides the Microsoft product itself.

For a couple of weeks (or months?), RZ4Intune cannot update "Lenovo System Update".

Latest version in RZ4Intune's repository is "Lenovo System Update 5.07.0137. It is always stuck in Status: Waiting

Also editing the app/update in RZ4Intune does not work. Right-clicking on the app update shows "Edit..." but nothing happens after clicking. Same for the app itself, "Edit..." does nothing. Right-clicking and "Download files..." is then also stuck in "Waiting..."

On one tenant I managed to update to 5.07.0136 on another I'm stuck since 5.07.0131.

It's the only app causing such issues.

Best regards,
Robert

**Comment by rzander** [comment]
... it's not a bug, it's a feature...
All Tools do check the "Prerequisite Script" to check if the package can be installed. For the "Lenovo System Update" , the PreReq Script is: `[Environment]::Is64BitProcess -AND ((Get-CimInstance -ClassName Win32_BIOS).Manufacturer -eq "LENOVO")` 
That means, you need to have a LENOVO device to be able to install the Tool... also on RZ4Intune and RZ4CM.

For the "Edit" Option, there is a trick, press [Shift] + "Edit" ... then you should be able to see the details for the first package.
