### ISSUE TITLE
 APIKey

### ISSUE THREAD

**Issue by jydareau** [rzander/ruckzuck#202]
Hi roger

 the API function "GetSoftwares" will require an APIKey . API-Keys 

Could you give me an APIKey, i use Ruckzuck for 3 years

Thanks

Jean-Yves

**Comment by rzander** [comment]
please send an email to roger at zander.ch....

**Comment by KenbhII** [comment]
Using Admin PowerShell trying to pull API, 
Invoke-RestMethod -Uri "https://cdn.ruckzuck.tools/rest/v2/getsoftwares?shortname=Firefox&?apikey={API KEY}" | Out-File -FilePath c:\Firefox.txt

returns the following:
Invoke-RestMethod : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Invoke-RestMethod -Uri "https://cdn.ruckzuck.tools/rest/v2/getsoftwar ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

what am I doing wrong?

**Comment by rzander** [comment]
The URL is not correct formated (remove the '?' before the "apikey=")...

```PowerShell
Invoke-RestMethod -Uri "https://cdn.ruckzuck.tools/rest/v2/getsoftwares?shortname=Firefox&apikey={API KEY}"
```
