### ISSUE TITLE
libreoffice update currently fails / needs security fixes

### ISSUE THREAD

**Issue by m1027** [rzander/ruckzuck#203]
libreoffice urgently needs security updates. ruckzuck seems to have an outdated version, though:

`[09:49:06 INF] Processing 'The Document Foundation' 'LibreOffice 7.4.1.2' '7.4.1.2'`
`[09:49:06 INF] Download started: LibreOffice (all file size:338MB)`
`[09:49:07 ERR] Download failed: 'LibreOffice' error: ERROR: download failed... LibreOffice_7.4.1_Win_x64.msi  downloaded: 0MB`

Please fix ASAP if possible

**Comment by rzander** [comment]
Fixed... FYI, everyone can update a package in the repo with ruckzuck.exe... only the final approval step is not "public".
