### ISSUE TITLE
Import GUI works, update PowerShell doesn't work

### ISSUE THREAD

**Issue by TheTaran** [rzander/ruckzuck#204]
NICE tool and work! 👍🏻 
I was able to successfully import applications according to the RZ4CM.exe.config. (Prefix, folders etc.) However, when I then after the scan, i run the update of these via PowerShell. 
This does not take over the settings within the RZ4CM.exe.config configuration.
Any idea why?

**Comment by TheTaran** [comment]
I have seen this error on the error Log.
11.11.2022 14:35:19;CM12Mgmt;E62Value cannot be null.
Parameter name: configMgrServerPath

**Comment by rzander** [comment]
Sorry, I have no ConfigMgr environment anymore to test or reproduce your issue...
The error is raised in line 84 of https://github.com/rzander/ruckzuck/blob/master/RZ4CM/CM_API.cs 
Do you have specified the CM_SQLServerDBName, CM_SQLServer and CM_Server in your .config file ?

**Comment by TheTaran** [comment]
Yes that values are set.
I solved that issue wiht a powershell step that i use for automatic update of the Apps.

**Comment by rivvee25** [comment]
> Yes that values are set. I solved that issue wiht a powershell step that i use for automatic update of the Apps.

Hey, how did you fix this? Im having the same issue :)
