### ISSUE TITLE
Incorrect versions of the installed program are detected

### ISSUE THREAD

**Issue by DkmS1953** [rzander/ruckzuck#207]
The program prompted me to update the version of the previously installed program from 2.7.1 to 2.7.3, but in fact I have a version 2.7.4 installed and working fine.

**Comment by rzander** [comment]
Which Product ?
If the ProductVersion is not a proper version (like containing letters), these things may happen ... Have you checked in AddRemovePrograms that 2.7.3 is not installed ? sometimes multiple versions of the same Software is installed....
