### ISSUE TITLE
Still deadlocking

### ISSUE THREAD

**Issue by johnfromstatefarm** [rzander/ruckzuck#211]
Hello, the software still deadlocks when I am downloading multiple applications.

I am searching for an app and hitting download individually, but it'll sometimes get stuck on Downloaded and not proceed with the installation.

**Comment by johnfromstatefarm** [comment]
Hello, it will install one app and the others will stay stuck on
"Downloaded". I've tried starting over the download by re-pressing "Start
Installation" and still nothing.

For further reference, the apps I frequently install together are: VLC,
Zoom, WinZIP, WinRAR, Acrobat Reader (64 bit), LibreOffice, and Chrome.

I have not tried F5, but I will when I get the chance.

**Comment by e-t-l** [comment]
Not sure if it's the same thing, but when downloading multiple programs, I experienced what others have, where it appears stuck on 0% and the entire UI goes completely nonresponsive... I just ignored it and went about my business in other windows, and within a few minutes I started getting UAC prompts for installs. So for me, at least, it _was_ downloading updates. The UI just froze while it did so.

**Comment by aswincoolsaet** [comment]
just use CLI ... 
-install ".NET" "Zoom" "Winrar" "Acrobat Reader (64bit)" "LibreOffice" .. 
or script it do do one by one.

**Comment by rzander** [comment]
Should be fixed in [v1.7.3.1](https://github.com/rzander/ruckzuck/releases/tag/1.7.3.1)
