### ISSUE TITLE
RZGet.exe missing in github latest release URL (currently 1.7.3.0)

### ISSUE THREAD

**Issue by m1027** [rzander/ruckzuck#212]
Hey, thanks for this awesome tool!

We've been using this common github url style to always download the *latest* RZGet.exe:
https://github.com/rzander/ruckzuck/releases/latest/download/RZGet.exe

However, RZGet.exe is missing there now. Could you provide RZGet.exe always for the latest release, too (even if nothing changed)?

Thanks

**Comment by rzander** [comment]
Fixed
