### ISSUE TITLE
The RPC server is unavailable

### ISSUE THREAD

**Issue by razo559** [rzander/ruckzuck#213]
Just recently install RuckZuck and when I select the Application > Download files and create CM App > I get an error "The RPC server is unavailable"

![image](https://user-images.githubusercontent.com/47169393/213284921-e42eef3d-65d1-4a98-baae-5976299eb5dc.png)
[RZError.txt](https://github.com/rzander/ruckzuck/files/10450351/RZError.txt)

**Comment by rzander** [comment]
I cannot confirm this issue, everything is working fine here...
RuckZuck does not depend on any RPC services, I assume that something is wrong with your client ?

**Comment by Maxwitat** [comment]
I'm getting the same error: The RPC Server is unavailable. Exception from HRESULT: 0x800706BA. Can't find an issue on the primary in my lab.

**Comment by rzander** [comment]
Sorry, my fault, it's about RuckZuck for ConfigMgr....
I assume, your *CM_Server*, *CMContentSourceUNC* or *CM_SQLServer* is not configured correctly in RZ4CM.exe.config -> https://github.com/rzander/ruckzuck/wiki/RuckZuck-for-ConfigMgr 
... is there anything written in %TEMP%\RZError.txt or in C:\RZError.txt ?
