### ISSUE TITLE
Endpoint/Intune Ruckzuck Application Install Failure

### ISSUE THREAD

**Issue by KenHII** [rzander/ruckzuck#214]
Trying to setup Endpoint to install Firefox through Ruckzuck

RZUpdate.exe - Download 2/01/2023, I did not set it up with any script inside.
Way I have it set up in Endpoint Applications Currently:

![Firefox App Information](https://user-images.githubusercontent.com/124192282/216401791-02564a72-a0da-42ce-b39c-9ee3c2d67e98.PNG)
![Firefox Program and Requirements](https://user-images.githubusercontent.com/124192282/216401815-42199efa-320c-407f-a95c-937fc4c74b45.PNG)

**Comment by rzander** [comment]
- RZUpdate is depreciated... why not using https://github.com/rzander/ruckzuck/releases/download/1.7.2.5/RZGet.exe ?
- What happens if you run the install/uninstall command in a VM/Sanbox ? Does it work ?
- How does Intune find RZUpdate.exe / RZGet.exe ? Have you created an .intunewin File that includes the tool ? 
- Your Uninstall command will also not work as you have parts from PowerShell, but you have to enter a command like `C:\Program Files\Mozilla Firefox\uninstall\helper.exe -ms`

**Comment by KenHII** [comment]
RZander, 

> * RZUpdate is depreciated... why not using https://github.com/rzander/ruckzuck/releases/download/1.7.2.5/RZGet.exe ?
Just started working on it today, after a Month and half off, and forgot to use RZGet.exe

> * What happens if you run the install/uninstall command in a VM/Sanbox ? Does it work ?
In command line on individual Machine
RZGet.exe "Firefox" failed
but changed to 
RZGet.exe Install "Firefox" Worked 
For the Uninstall
C:\Program Files\Mozilla Firefox\uninstall\helper.exe -ms Failed
Changed to
"C:\Program Files\Mozilla Firefox\uninstall\helper.exe" /s Pass

> * How does Intune find RZUpdate.exe / RZGet.exe ? Have you created an .intunewin File that includes the tool ?
Yes, created .intunewin file that included a virgin copy of RZGet.exe this morning

> * Your Uninstall command will also not work as you have parts from PowerShell, but you have to enter a command like C:\Program Files\Mozilla Firefox\uninstall\helper.exe -ms
Had to look online for the Cmd coding for silent running as /ms failed when attempted

Changed both Install and Uninstall commands in Endpoint. Now installs however does not detect the software.
![Detection Rule](https://user-images.githubusercontent.com/124192282/216666837-e4a32780-5ac9-4e97-944c-64fa1258626b.PNG)

**Comment by rzander** [comment]
This seems to be an Intune Issue... Have you tried to check for a File? E.g. RuckZuck does check:
if((Get-Item "$($env:ProgramFiles)\Mozilla Firefox\firefox.exe"-ea SilentlyContinue).VersionInfo.FileVersionRaw -ge "116.0.1.0") { $true } else { $false }
