### ISSUE TITLE
Notepad++ give nothing

### ISSUE THREAD

**Issue by Michael-ol** [rzander/ruckzuck#217]
Hello,

We notice that since some days Notepad++ give nothing anymore : https://cdn.ruckzuck.tools/rest/v2/getsoftwares?apikey=93827751614070&shortname=Notepad++(x64)

;-)

Regards.

**Comment by rzander** [comment]
Seems to be a bug as the URL is not encoded correctly... Will fix that...

**Comment by rzander** [comment]
Fixed

**Comment by Michael-ol** [comment]
Perfect. Thanks.
