### ISSUE TITLE
cannot download the Adobe x64

### ISSUE THREAD

**Issue by crapitouille** [rzander/ruckzuck#218]
![image](https://user-images.githubusercontent.com/42565172/223214340-c445c895-93e8-471f-9729-cbb377437e0d.png)

**Comment by crapitouille** [comment]
while trying to login, I got this error in the login frame

![image](https://user-images.githubusercontent.com/42565172/223214687-a7cc0043-9599-4308-a9aa-85620e1ecb57.png)

**Comment by rzander** [comment]
1. "Update your browser"
2. Update RZ4Intune: [1.7.2.5](https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5)
