### ISSUE TITLE
"Status: Recursive read lock acquisitions not allowed in this mode"

### ISSUE THREAD

**Issue by e-t-l** [rzander/ruckzuck#219]
I have no idea what this means, but programs do not download (they show 0%) and appear highlighted in red with this message. A lot of programs got this error, like 7-Zip, Notepad++, and Android Studio. 

I'm running RuckZuck 1.7.3.0 Portable on Windows 11 Home

**Comment by rzander** [comment]
Never seen this before... is it still the case ?

**Comment by e-t-l** [comment]
Yes, as of v1.3.7.1. Do I need to run it as administrator or something?

![image](https://github.com/rzander/ruckzuck/assets/40775958/83b1a8e7-2516-4722-9b4e-8120abd1668c)

**Comment by rzander** [comment]
That looks strange... Do you have any special AntiVirus Settings/solutions in place? It seems that something as blocking the files....
Yes, you must run RuckZuck.exe as Admin (It should request Admin automatically..)

**Comment by e-t-l** [comment]
Just wanted to update this to say that I did have to reinstall my AV recently, and now Ruckzuck is able to install all programs as expected.
