### ISSUE TITLE
Request API Key

### ISSUE THREAD

**Issue by antoinemoussy** [rzander/ruckzuck#220]
Hi! I would like to try Rucksack and I understand I need an API Key.
Could you provide me one please?

Regards

**Comment by rzander** [comment]
You only need an API-Key if you want to access the Ruckzuck API (e.g. with PowerShell).. If you just use the compiled tool like RuckZuck.exe or RZGet.exe there is no need for an API-Key...

Still need one? -> send me an email to roger at zander.ch
