### ISSUE TITLE
Upload is not possible

### ISSUE THREAD

**Issue by antoinemoussy** [rzander/ruckzuck#221]
Hi! My first upload is not OK because the button in greyed.
I read the forum and maybe the unique URL is the cause.

Am I the right place too ask what to do?

Thanks!
[EXP_sfdx-cli7.191.1X64.json.zip](https://github.com/rzander/ruckzuck/files/10995078/EXP_sfdx-cli7.191.1X64.json.zip)

**Comment by rzander** [comment]
The Upload Button is greyed out if some parameters are missing or if the File URL is not touched... 
After editing the URL, a File dialog will pop up... just select the downloaded file so RuckZuck can calculate the Hash and File Size (hidden value)... Then the Upload Button should get active.
I have updated your XML (as it's now Version 7.191.2) and uploaded it... The package is now available in the public repository.

Thanks for your submission! 
 that's the way to go, if something is unclear just post the XML here as I can give feedback...

**Comment by antoinemoussy** [comment]
Hi. I think I understood, thanks ! When I reopen a JSON file I have to do the action into URL once again even I did before saving.
I tried another one but I don't know if I have no talent or I am unlucky but Test Install is ok but install fails when I try with the generated exe... 🤔
[EXP_Amazon Corretto (x64)11.0.18.10X64.json.zip](https://github.com/rzander/ruckzuck/files/11001434/EXP_Amazon.Corretto.x64.11.0.18.10X64.json.zip)

**Comment by rzander** [comment]
Everything looks fine, I just set the shortname to "amazon corretto 11 x64 jdk" to follow the same standard as the older versions...
