### ISSUE TITLE
Adding arguments to application

### ISSUE THREAD

**Issue by aarnold-sd68** [rzander/ruckzuck#222]
This isn't really an issue other than for some reason my windows 11 clients will not install google chrome with out this, works find on windows 10.  But the install needs to have /L*V .\ChromeInstall.log added to arguments to make it install :(.  What I was wondering is if their is away for me to do this manually or if there is some way this could be added to the install.ps1 if needed?

**Comment by rzander** [comment]
Google Crome works fine on all my W11 devices...

**Comment by aarnold-sd68** [comment]
Yeah not sure why it doesn't on mine.  I think it's getting an non terminal error as part of the install :( and needs somewhere to write this too.  But it's not the only software that I'd like to be able to do this to, it's just an example I have, and a reason for it.  I can do it manually as well just something I have to remember to do.
