### ISSUE TITLE
Rz4Intune "Install Software" no apps

### ISSUE THREAD

**Issue by kIrk2k** [rzander/ruckzuck#225]
Hi, i wanted to install new apps but it seems like that the repositry is not getting searched by the app?
only a blank screen. at you website i can search the repo
![image](https://github.com/rzander/ruckzuck/assets/20935901/41e5bedd-e50c-4346-bad3-4ee06c02568c)

any idea?

kind regards

**Comment by rzander** [comment]
delete %temp%\rzcat.json and restart the app...
Make sure you can connect to https://cdn.ruckzuck.tools/rest/v2/getcatalog

**Comment by kIrk2k** [comment]
Great that helped! Thanks :=)
