### ISSUE TITLE
How and were do you find/calculate the file hashes?

### ISSUE THREAD

**Issue by x0tester0x** [rzander/ruckzuck#227]
How and were do you find/calculate the file hashes?

**Comment by rzander** [comment]
A File-Dialog will pop up if you leave the URL Field in RuckZuck.exe (when you edit/create a package)... Then you have to select the previously downloaded File. It will use the X509 signature or the MD5 Hash if no signature exists. Additionally, the File Size is also stored (not visible in the GUI).

**Comment by x0tester0x** [comment]
Can the file hash not be uniquely (also calculated) SHA256?

**Comment by rzander** [comment]
Let's take FireFox as an example, where ruckzuck does download the installer based on the language of the os... The File-Hash would be different for every language... That's why the X509 Signature is used to validate the integrity of the file.

**Comment by x0tester0x** [comment]
Ok, I understand.
Is therea PowerShell command to validate if the X509 Signature corresponds to the file downloaded?

**Comment by x0tester0x** [comment]
The X509 Signature changes when a new version is released, correct?

**Comment by x0tester0x** [comment]
The X509 Signature changes when a new version is released, correct?

**Comment by rzander** [comment]
No, only when the vendor is changing the code-signing certificate...
