### ISSUE TITLE
Not getting any list of program.

### ISSUE THREAD

**Issue by Juanikus** [rzander/ruckzuck#23]
Every time I open the program and access the install option I get an empty section where the list should be placed as you can see [here](https://i.imgur.com/hpvcF7h.png). I would like to know if I need to install something in order to use this.

Thanks in advance.

**Comment by rzander** [comment]
RuckZuck requires Internet access to get the software repository list… Are you in a Company Network with  Proxy Server ? RuckZuck is using the Proxy-Settings from InternetExplorer… are you able to browse to https://ruckzuck.tools in IE without an additional authentication prompt ?
