### ISSUE TITLE
Prefer EXE or MSI?

### ISSUE THREAD

**Issue by x0tester0x** [rzander/ruckzuck#231]
Do ypu prefer .exe files over .msi files when there are both versions available?

**Comment by rzander** [comment]
In general, I would prefer MSI over EXE ... but it depends on the quality of the MSI.

**Comment by rzander** [comment]
I have updated KeePassXC. Maybe it was by mistake during an update or the author of the tool has chosen the "legacy" MSI for what reason...

**Comment by x0tester0x** [comment]
Will you change the URLs listed?

**Comment by rzander** [comment]
Teams will stay on the current solution as its synced with the MachineWideInstaller... Maybe when Teams 2.0 is released.
PDF24 makes sense, but I wait until there is a new version.
AnyDesk I have to check the differences, but it has to wait until a new version is released
Skype is updated

**Comment by rzander** [comment]
reverted skype to use "https://download.skype.com/s4l/download/win/Skype-8.98.0.407.msi" as "https://go.skype.com/msi-download" does not work from a RuckZuck Package.... They may have too many redirects so the download does fail...

**Comment by x0tester0x** [comment]
What did you do with the Skype URL?
