### ISSUE TITLE
All packages on RuckZuck website are down

### ISSUE THREAD

**Issue by QMSPS** [rzander/ruckzuck#232]
Hi,

When I tried to test the 'RZGet.exe' command line tool, I was getting this error: Downloading...Error: Object reference not set to an instance of an object

If I click on any package on the website, it's shows only "[ ]", so no data on any package.

If I use the RuckZuck GUI app, it's working with no problems.

Hope you can fix it, thanks already!

**Comment by QMSPS** [comment]
It's working again, thanks!

**Comment by rzander** [comment]
Self healing :-) .... Sometimes the Service will be flooded with requests and becomes unresponsive....

**Comment by QMSPS** [comment]
Ah, because now is the same issue. I'm just checking  some apps on the website and use RZGet.exe check and do what neess to  be done, like install., update or skip.

Is that something I  need a API key for? Because I didn't a API key in the console option..

**Comment by QMSPS** [comment]
What I found interesting is that the website, RZGet and RZOneGet are having troubles and only the GUI was working fine.

**Comment by rzander** [comment]
Are you using the latest Version of RZGet.exe -> https://github.com/rzander/ruckzuck/releases/latest 
As RZGet.exe should have the same codebase as RuckZuck.exe.... The OneGet Provider is outdated and will no longer maintained.
