### ISSUE TITLE
Firefox - correct language

### ISSUE THREAD

**Issue by ajtak-angelus** [rzander/ruckzuck#234]
The current Firefox installation does not detect the language correctly. Here is the correct configuration.
[EXP_Mozilla Firefox 115.0.2 x64 115.0.2.0X64.txt](https://github.com/rzander/ruckzuck/files/12050756/EXP_Mozilla.Firefox.115.0.2.x64.115.0.2.0X64.txt)

**Comment by rzander** [comment]
should be fixed now... thanks for reporting it!

**Comment by ajtak-angelus** [comment]
So I tested it and unfortunately it doesn't work properly. Not even my version. The links are generated correctly, but the correct version is not installed.
for EN
https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=en-US
for CS
https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=cs

Your version always installs the English version and my Czech version

**Comment by rzander** [comment]
The generated URL's and the downloaded MSI seems to be correct...
Are you installing from a user context or from a software deployment tool running in SYSTEM context ? What is the result of ```(Get-Culture).TwoLetterISOLanguageName``` should be "cs" ?! and what is th eresult of ```(Get-Culture).Name``` ?

**Comment by ajtak-angelus** [comment]
I tried switching the system to another region, but the result is strangely the same - install only english (your version) or czech (my version). I tried both rzget.exe and RuckZuck.exe and both behave the same. Does it work correctly for you?
Czech region:
(Get-Culture).TwoLetterISOLanguageName : cs
(Get-Culture).name : cs-CZ

**Comment by rzander** [comment]
If I replace and hardcode your values in the script:
```PowerShell
$lang = "ach,af,sq,ar,an,hy-AM,as,ast,az,eu,be,bn-BD,bn-IN,bs,br,bg,ca,zh-CN,zh-TW,hr,cs,da,nl,en-US,en-GB,en-ZA,eo,et,fi,fr,fy-NL,ff,gd,gl,de,el,gu-IN,he,hi-IN,hu,is,id,ga-IE,it,kn,kk,km,ko,lv,lij,lt,dsb,mk,mai,ms,ml,mr,nb-NO,nn-NO,or,fa,pl,pt-BR,pt-PT,pa-IN,ro,rm,ru,sr,si,sk,sl,son,es-AR,es-CL,es-MX,es-ES,sv-SE,ta,te,th,tr,uk,hsb,uz,vi,cy,xh"  -split(",");
if($lang -contains "cs-CZ") { $lang = "cs-CZ"} elseif($lang -contains "cs") { $lang = "cs" } else { $lang = "en-US"};
"https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=$($lang)"
```
I will get `https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=cs` which does download the cs language...

What do you get as output ?

**Comment by ajtak-angelus** [comment]
links are generated correctly in powershell - as I wrote:
for EN
[EXP_Mozilla Firefox 115.0.2 x64 115.0.2.0X64.txt](https://github.com/rzander/ruckzuck/files/12061992/EXP_Mozilla.Firefox.115.0.2.x64.115.0.2.0X64.txt)

https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=en-US
for CS
https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=cs

And when I create a new package in RuckZuck and load my config (attached), it always installs CS - even if I have EN region. And your config always installs only EN.

[EXP_Mozilla Firefox 115.0.2 x64 115.0.2.0X64.txt](https://github.com/rzander/ruckzuck/files/12061996/EXP_Mozilla.Firefox.115.0.2.x64.115.0.2.0X64.txt)

**Comment by ajtak-angelus** [comment]
I set the region to Germany and RuzckZuck installs the EN version.
![obrazek](https://github.com/rzander/ruckzuck/assets/19210976/b27c5bcd-b6d4-4065-87f5-bc55f6157db8)

**Comment by rzander** [comment]
Have you verified, which language was installed? The text in the installation queue "Mozilla Firefox (x64 en-US)" is misleading as it's not related to the downloaded and installed language !
I will remove the "en-US" part of the product-name with the next update.

**Comment by ajtak-angelus** [comment]
Yes, of course he did. Firefox actually installs in English.

**Comment by rzander** [comment]
I just did a test on a german windows11 and it did install the german firefox...

**Comment by ajtak-angelus** [comment]
So I discovered the problem. I deleted the contents of the folder c:\users\user\appdata\local\temp. And then installed it correctly. But until I deleted the contents of the folder, it installed in English

**Comment by rzander** [comment]
Then it's clear, ruckzuck does check in %temp%\<contentid> for a file "Firefox Setup 115.0.2.msi". If its there with the right signature, it will use the file from disk.

**Comment by ajtak-angelus** [comment]
I'm glad we solved the problem. And thank you for your help.
