### ISSUE TITLE
Slowing PC's Down

### ISSUE THREAD

**Issue by jayjayuk85** [rzander/ruckzuck#236]
OK, I know this a bit random, we ran this on quite a few machines (the same time there were windows updates) 

However it seems to have caused machines to slow down. I am not sure if this is the software or something else, but thought I would post in case others have the same issue?

**Comment by rzander** [comment]
What do you run... RuckZuck.exe , RZGet.exe , OneGet ? I need mor Infos of what you are doing nad how often.... But yes, if you update a bunch of Software on a device it may slow down network and cpu...

**Comment by jayjayuk85** [comment]
I am using the RZGet.exe  and running the command remotely - RZGet.exe update --all

It doesn't happen when updating, it may just be a coincidence and possibly windows update. My other thought may be something running in the background? or adobe update.

**Comment by rzander** [comment]
RZGet.exe is a command-line tools, which terminates when done. When installing updates, also AntiVirus will generate activity to analyze the downloaded content... Also be aware that if you run the command on multiple devices at the same time, your network may become the bottleneck as every device is downloading the content from internet...
