### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by peng10922** [rzander/ruckzuck#238]
Hi Roger,
Could you please generate an API Key for me? 
My email address:  peng10922@gmail.com
Thank you!

**Comment by peng10922** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by rzander** [comment]
I've sent an email with the key... please check also the spam folder.

**Comment by peng10922** [comment]
> I've sent an email with the key... please check also the spam folder.

Hi Roger,

I had checked all mailbox include spam folder.. cant find any emails from you... could you please send me the key again?
Sorry for inconvenience.. and Thank you very much! :)
