### ISSUE TITLE
Status:Installed but nothing inside sccm console?

### ISSUE THREAD

**Issue by ruiqiu** [rzander/ruckzuck#24]
Hi, 

I setup the config file and can add software, in the end it said " Status:Installed" , however I cannot find the application inside SCCM.

What might be wrong? any logs I can check? I only see "rzcat.json" from %TEMP%

thanks!

**Comment by rzander** [comment]
It creates a Folder "RuckZuck" in the Applications node. You have to refresh (F5) the console to see the Folder...

**Comment by ruiqiu** [comment]
ah, yes! sorry...been stupid...lol....didn't realized need to press F5 :)
