### ISSUE TITLE
Incorrect Old Versions

### ISSUE THREAD

**Issue by truthsword** [rzander/ruckzuck#240]
Apparently this app uses the Windows Uninstall information in the registry to decide what the existing version is. But this is flawed. For example, the Windows Uninstall registry shows the Mozilla versions for Firefox and Thunderbird, as the version when they were originally installed. But both apps have self-updated several times, and the registry info remains as the original. For example, RuckZuck thinks Thunderbird is at v115.2 when it is actually at v115.3.2.

How to fix? Several packages have this.

When I tried to "update" these packages RuckZuck uninstalled them!!! Fortunately I was able to restore using a drive image. Thanks!

**Comment by rzander** [comment]
RuckZuck is detecting updates based on the ProductName and Version  from the Registry (SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall). 
If Products do install updates without updating the version in the registry,  then RuckZuck will report wrong updates as you mentioned (that's something the vendor should fix). 
Beside that, each RuckZuck package also has a detection logic to determine, if the product is installed. FireFox as an example does check the version of firefox.exe and if the exe is a newer version, it does detect it as "installed" and RuckZuck will not download and update the product.
If you recommend to use another detection logic (e.g. Thunderbird) let me know what you would check to determine the version of the installed product.
RuckZuck is just triggering the original setup from the vendor. Please contact the vendor if there are issues with their installer.

**Comment by truthsword** [comment]
> FireFox as an example does check the version of firefox.exe and if the exe is a newer version, it does detect it as "installed" and RuckZuck will not download and update the product.

That's not my experience. This happens too with Firefox. 
![](https://i.imgur.com/Mc1g0Uz.png)
![](https://i.imgur.com/M3eTovb.png)

I'd prefer that only the executable version is checked.

I'd also like to see my installations scanned for executable. Few of my programs are "seen". Thank you!

**Comment by rzander** [comment]
You can (right click) **edit** a package to see the logic behind it... Firefox is using the following detection script:
![image](https://github.com/rzander/ruckzuck/assets/11909453/95e6df14-6abe-400f-aceb-2fe3308e71a8)
RuckZuck does not scan for executables, it does detect updates based on the registry values.

The packages where made from the community. If you think that some are not working correctly, make a proposal for a change.   

If you have packages that shows up in the registry (or in ControlPanel "Uninstall a program"), but does not show the update in RuckZuck, please post the exact ProductName, Manufacturer and Version you have... RuckZuck is using a mapping table to detect the updates and sometimes the Productnames or Manufacturer string has changed...

**Comment by truthsword** [comment]
Thanks, but not for "average users".
