### ISSUE TITLE
Microsoft Configuration Module

### ISSUE THREAD

**Issue by mastercodefu** [rzander/ruckzuck#241]
Hi I seem to have a problem where installed no problem have configured my config file using details from the site using my server details.   But still the client does not launch with the added button in  Applications.  Any ideas am i missing something?

Regards
Craig

**Comment by rzander** [comment]
Are your referenceing "RuckZuck for Configuration Manager" ?
Have you checked the settings from https://github.com/rzander/ruckzuck/wiki/RuckZuck-for-ConfigMgr#configuration ?

**Comment by mastercodefu** [comment]
Apologies on the long delay as this was my lab, I figured I'd redo my sccm server to confirm was not an issue with my installation.  So, I can install apps normally.  Unfortunately, I can't do it from your addon as the addon does not show in my config manager. I'm not sure if I am missing somehow activating into the console.  I have followed https://www.youtube.com/watch?v=Qsm88osD6rY&t=344s and read https://github.com/rzander/ruckzuck/wiki/RuckZuck-for-ConfigMgr#configuration but still my client won't open with the addon. Another strange thing is the error.txt file you mention in temp is not there also.  After checking all the temp files am lost now where to look.  
Console version is 5.2309.1113.1000 sccm version 2309,

**Comment by rzander** [comment]
The Setup of "RuckZuck 4 ConfigMgr" does copy the following XML to **{ConsolePath}\XmlStorage\Extensions\Actions\d2e2cba7-98f5-4d3b-bc2f-b670f0621207\RZ4CM.xml**

```XML
<ActionDescription Class="Executable" SelectionMode="Both" DisplayName="RuckZuck import..." MnemonicDisplayName="RuckZuck import..." Description="Import an Application from the RuckZuck.tools repository.">
	<ShowOn>
		<string>ContextMenu</string>
		<string>DefaultHomeTab</string>
	</ShowOn>
	<ImagesDescription>
		<ResourceAssembly>
			<Assembly>RZ4CM.exe</Assembly>
			<Type>RuckZuck_Tool.Properties.Resources.resources</Type>
		</ResourceAssembly>
		<ImageResourceName>RZ</ImageResourceName>
	</ImagesDescription>
	<Executable>
		<FilePath>RZ4CM.exe</FilePath>
		<Parameters></Parameters>
	</Executable>
</ActionDescription>
```

Please check if the file is there...  Please also check if RZ4CM.exe is in the "Bin" directory of the ConfigMgr Console Path...

**Comment by mastercodefu** [comment]
Thanks for coming back to me.  I can confirm the xml is in the correct path. 
"C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\XmlStorage\Extensions\Actions\d2e2cba7-98f5-4d3b-bc2f-b670f0621207" and the EZ4CM.exe is in the bin folder along with the config file.

**Comment by mastercodefu** [comment]
I am running on windows 2022 21h2 - Build 20348.2159  not sure is this helps.  Something i can't see is how to remove.  As is not working and we can't get working would be nice to manually remove as the is no uninstall options in add and remove.  Ideally i would like to get working as looks a great addition.

**Comment by rzander** [comment]
Check your Site Hierarchy Settings if "**Only allow console extensions that are approved for the hierarchy**" is enabled...

**Comment by mastercodefu** [comment]
Just checking now and it is enabled. Apologies am fairly new to sccm as a whole.

**Comment by rzander** [comment]
You have to disable "**Only allow console extensions that are approved for the hierarchy**".
