### ISSUE TITLE
API key 

### ISSUE THREAD

**Issue by AbhignyaTayi15** [rzander/ruckzuck#243]
can I get an api key to fetch information of software repository and get details like app current version and download url .
And can you also explain how the ruckzuck tool gets the info and updates of all the application ( source) for office use

**Comment by rzander** [comment]
Please send me an email: roger at zander.ch , then i will send you an API key. 
Even without an API-Key you can get the Metadata by using ruckzuck.exe (right click an app->edit...) or on https://ruckzuck.tools/Home/Repository (click on the ShortName)

The files you download are sourced directly from the vendor, with RuckZuck hosting them only in exceptional circumstances. Anyone can report or create updates if a newer version is available. RuckZuck meticulously reviews all submissions to ensure the downloaded files are valid through hash or certificate checks. Furthermore, the package undergoes testing on a virtual machine running default antivirus software (Defender).

The reliability of the public repository is bolstered by numerous submissions from the commercial solution, https://romawo.com.

**Comment by AbhignyaTayi15** [comment]
I have checked that the api key is updating everyday if I click on shortname .For how long the API key is valid and how many requests can be made per day. As it is a 3rd part application is it allowed to use for company use to fetch the software updates if they are present

**Comment by AbhignyaTayi15** [comment]
But in the rss feed information like app version and download url link is missing . That's the information I want to retrieve
