### ISSUE TITLE
Change Datasource

### ISSUE THREAD

**Issue by mastercodefu** [rzander/ruckzuck#246]
Finally i can see in moy console, really appreciate the point int he right direct.  Problem i now have Is when trying to access it looks from the log file the sql server i get the below.  From what can make out it's because i am not in my domain i am trying to use a sql server account rather than local domain.  Is this possible or do i need to work from in my domain only.  I'm just wanting to avoid running my local machine in my domain.

Regards
Craig

20/12/2023 18:40:38;F239E1The target principal name is incorrect.  Cannot generate SSPI context.
SQL:;WITH XMLNAMESPACES ( DEFAULT 'http://schemas.microsoft.com/SystemCenterConfigurationManager/2009/AppMgmtDigest')   SELECT Shortname, Bootstrap, [Version] FROM  ( SELECT  SDMPackageDigest.value('(/AppMgmtDigest/Application/SoftwareVersion)[1]', 'nvarchar(MAX)') as [Version], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Bootstrap"]/@Value)[1]', 'nvarchar(MAX)') [Bootstrap], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Shortname"]/@Value)[1]', 'nvarchar(MAX)') [Shortname],  vCI.CI_ID FROM v_ConfigurationItems as vCI WHERE CIType_ID = 10 and IsLatest = 1 and LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomId)[1]', 'nvarchar(MAX)')) > 2  ) as app WHERE ShortName is not null
Connection:Data Source=myserver.mydomain.local;Initial Catalog=CM_A51;Integrated Security=True
20/12/2023 18:42:41;F239E1The target principal name is incorrect.  Cannot generate SSPI context.
Data Source=myserver.mydomain.local;Initial Catalog=CM_A51;Integrated Security=True
RZ76093789296
20/12/2023 18:42:41;F239E1The target principal name is incorrect.  Cannot generate SSPI context.
Data Source=myserver.mydomain.local;Initial Catalog=CM_A51;Integrated Security=True
RZ76093789296

**Comment by rzander** [comment]
The Tool does not support SQL authentication with an SQL account... Even if it would, you still have to authenticate against WMI on ConfigMgr and on the FileShare... Your scenario does not make sense to me...

**Comment by mastercodefu** [comment]
No worries, as was at my home lab it was just for ease of use in my scenario,  Really great work so far playing with.  Thanks for coming back to me.

**Comment by mastercodefu** [comment]
No worries, as was at my home lab it was just for ease of use in my sceniario,  Really great work so far playing with.  Thanks for coming back to me.
