### ISSUE TITLE
1Password showing needs update when later beta installed

### ISSUE THREAD

**Issue by wiz2003** [rzander/ruckzuck#247]
![RUCKZUCK false 1password update](https://github.com/rzander/ruckzuck/assets/18750228/01f1622a-b444-4d9c-979f-c8901eebb9e1)

**Comment by rzander** [comment]
RuckZuck necessitates a valid version adhering to semantic versioning standards (referenced here: https://en.wikipedia.org/wiki/Software_versioning) for effective comparison and detection of software updates.
1Password, along with certain other products, deviates from this standard, consequently impeding the capability for update detection.

**Comment by wiz2003** [comment]
Thank you...
Will feedback to 1password
