### ISSUE TITLE
show multiple programs

### ISSUE THREAD

**Issue by famko09** [rzander/ruckzuck#249]
is it possible to show the metadata of multiple items ? 
like this: : RZGet.exe show "prog1", "prog2", "prog3""

**Comment by rzander** [comment]
Can you give some more information about the use-case of your request...

**Comment by famko09** [comment]
this  "RZGet.exe update --list --all" gives all the available updates but without the versions. This: "RZGet.exe show " gives the metadata including the versions ect. Would be nice if you could add more then one program name and show more info about the the programs that need an update. 
Solved it now to search in the json file and extract the things i needed. 
thank for answering me, it a nice peace of software!

**Comment by rzander** [comment]
if you need the version, I would recommend to use ```$cat = &".\RZGet.exe" search | ConvertFrom-Json``` to get the full catalog, and then search the $cat object for the required information...  This uses the local cached %temp%\rzcat.json or does one web-request to get the catalog.

If you are using ```.\RZGet.exe show <shortname>```, it does call the Web API for every request...
