### ISSUE TITLE
KeePass 2.40.0 is reported as a new version for version 2.40

### ISSUE THREAD

**Issue by sschuberth** [rzander/ruckzuck#25]
See

![image](https://user-images.githubusercontent.com/349154/47614759-2a5d0b80-daa5-11e8-8889-9c57ef7cbc8b.png)

Maybe trailing zeros (separated by dots) should generally be ignored to avoid this?

**Comment by rzander** [comment]
Fixed: Excluded "KeePass Password Safe 2.40"
It's maybe the difference between the MSI and EXE setup... ?!

**Comment by sschuberth** [comment]
> Fixed: Excluded "KeePass Password Safe 2.40"

Hmm, if that's a hard-coded fix for version 2.40, you'll likely have to do it for 2.41 vs 2.41.0 and every other release.

> It's maybe the difference between the MSI and EXE setup... ?!

I don't think so, because [there does not seem to be an MSI installer for KeePass](https://keepass.info/download.html), only the InnoSetup-based one.

**Comment by rzander** [comment]
There is an MSI on https://keepass.info/download.html that goes to https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.40/KeePass-2.40.msi/download

Mapping versions is only partial automated as ProductNames and version numbers are changing. Normally I check for un-mapped ProductNames and versions during approval of a new version.

**Comment by stonecrusher** [comment]
As predicted by sschuberth:
![2019-03-11 10_14_59-RuckZuck](https://user-images.githubusercontent.com/1388389/54112591-d36a2a00-43e6-11e9-9b9c-5d111842cdda.png)
Installed from .exe

**Comment by rzander** [comment]
It's a technical Issue because 2.41.0 is detected as a higher version than 2.41...

**Comment by sschuberth** [comment]
Right. A possible way to solve this is to "normalize" version numbers by stripping insignificant trailing zeros and dots before version comparison.

**Comment by rzander** [comment]
Fixed in Server Version 2.0.0.13  (https://github.com/rzander/ruckzuck/commit/d96e20a41476c26f4956ad536c888d02efd44e0c)
