### ISSUE TITLE
Incorrectly flags updates for 7zip, when 7-Zip-zstd is installed

### ISSUE THREAD

**Issue by slycordinator** [rzander/ruckzuck#253]
7-Zip-zstd is a fork of 7-Zip with additional compression codecs.

The latest version of 7-Zip-zstd is "7-Zip ZS 22.01 - v1.5.5 - Release 3".

But RuckZuck recognizes this as an outdated version of 7-Zip.

In the registry, on a 64 bit machine, this is installed with the DisplayName of "7-Zip ZS 22.01 ZS v1.5.5 R2 (x64)" and DisplayVersion of "22.01 ZS v1.5.5 R2"

Thanks

**Comment by rzander** [comment]
The detection should be fixed and it should no longer detect that product as "7-Zip"...
