### ISSUE TITLE
7-Zip

### ISSUE THREAD

**Issue by techygeekshome** [rzander/ruckzuck#254]
7-Zip v24 have been out for a while now, is there any reason it hasn't been updated in RuckZuck yet?

**Comment by rzander** [comment]
based on https://www.7-zip.org the current version is 23.01 ... 24.x is still beta...
![image](https://github.com/rzander/ruckzuck/assets/11909453/e314790c-5cf1-48d6-b983-2d2a49e776ea)

**Comment by techygeekshome** [comment]
oh ok, thanks for that.
