### ISSUE TITLE
Created application does Not Show in Software Center.

### ISSUE THREAD

**Issue by Keywan2009** [rzander/ruckzuck#255]
Hi,
I have created with a Application named Zoom and deploy it User Collection, but I cannot see it on the Software center.
If I deploy that Application to a device Collection, I see it on the Software Center
The Power Shell is set to bypass
Any idea?
The Application is created but it is not distributed, I see it on the "Content". why? I did distribute it manually
How can I add my DP to the Application? I don't have any DP Group. I have only a Distribution Point

**Comment by Keywan2009** [comment]
I

**Comment by rzander** [comment]
Two things:
1. RuckZuck 4 ConfigMgr is depreceated
2. read https://rzander.azurewebsites.net/ruckzuck-for-configmgr-new-v1-5-18/

**Comment by Keywan2009** [comment]
I have installed the Version 1.7.2.5 and using it
