### ISSUE TITLE
How can I update a created application automatically?

### ISSUE THREAD

**Issue by Keywan2009** [rzander/ruckzuck#257]
Hi,
I have created a Application(Firefox Browser) with Ruckzuck and deploy it to User Collection  successfully. Is there anyway to update the created Firefox Browser automatically as well Firefox as deployment?
I mean, if there is a new Firefox Version, it should Download it atomatically and deploy it to  already created User Collection?

regards

**Comment by rzander** [comment]
You can try to script it: https://github.com/rzander/ruckzuck/wiki/RuckZuck-for-ConfigMgr#automatically-update-applications
... but out-of-the-box, there is no automatic update.

**Comment by Keywan2009** [comment]
Ok, it is Updated online The gui and The sccm application

**Comment by rzander** [comment]
RZ4CM is depreciated...
