### ISSUE TITLE
After creating a Application with Ruckzuck, the application does not show in software center, PS is set to bypass.

### ISSUE THREAD

**Issue by Keywan2009** [rzander/ruckzuck#258]
Hi,
I have created a Application an deploy it to User Collection. The User cannot see it on the Software Center.
Only if I deploy to Device Collection, the user can see it on the software Center. PS is set to bypass

Regards

**Comment by TheTaran** [comment]
Try to set te value LimitingUserCollectionID inseide de Rz4CM.exe.config file.

**Comment by Keywan2009** [comment]
Hi,

I set it on the config file as following
<setting name="LimitingUserCollectionID" serializeAs="String">
                <value>SMS00004</value>
