### ISSUE TITLE
Please add a built-in way to test-run the detection script

### ISSUE THREAD

**Issue by sschuberth** [rzander/ruckzuck#26]
When trying to fix detection scripts, it would be nice to be able to test-run them from within the "Create a new Software Package..." dialog.

PS: There is a typo in "Create a new Soft**w**are Package...", the "w" is missing.

**Comment by rzander** [comment]
Typo is fixed… :-)

The detection script is generated automatically based on MSI ProductCode or if you create a Software Package based of an existing installation... Only in very rare cases, it's required to modify or change the detection script.

Will think about it..

**Comment by rzander** [comment]
closed as it's very rare to modify the detection script. For this case you can just copy-paste into powershell...
