### ISSUE TITLE
Ruckzug does not work After upgrading from SCCM 2207 to SCCM 2403 

### ISSUE THREAD

**Issue by Keywan2009** [rzander/ruckzuck#261]
HI,

I have upgraded my SCCM 2207 to SCCM 2403, Now the Ruckzug doesn not work any more, it started and if click on Install new Software, it happened nothing and it doe not appears the Repository

Any Idea?

**Comment by DJKatastrof** [comment]
Seems to be an global issue. Not working for me either.

**Comment by rzander** [comment]
Yes, there was an outage today.. should be fixed now.

**Comment by Keywan2009** [comment]
resolved
