### ISSUE TITLE
download link for Docker

### ISSUE THREAD

**Issue by Michael-ol** [rzander/ruckzuck#264]
Hello Roger,

Is it normal that for Docker the URL link is a powershell command please?
"URL": "iwr \"https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe\" -OutFile \"Docker Desktop Installer.exe\""

https://[cdn.ruckzuck.tools/rest/v2/getsoftwares?apikey=76876958183895&shortname=Docker](https://cdn.ruckzuck.tools/rest/v2/getsoftwares?apikey=76876958183895&shortname=Docker)

Regards.

**Comment by rzander** [comment]
Define "normal" :-) the download does not work with the direct URL... it seems they block some requests but allow PowerShell...

**Comment by Michael-ol** [comment]
Thanks for your answer.

I ask because in our script we create a powershell command to download the file with the HTTP link. So here we make a powershell in a powershell. ;-)

But I unerdstand. ;-)

I close it.
