### ISSUE TITLE
Master Packager not visible in Intune

### ISSUE THREAD

**Issue by al-itc** [rzander/ruckzuck#265]
Hi,
I have uploaded MasterPackager through RZ4Intune and it says "Installed" but the App does not appear in Intune. I have made sure that I'm connected to the correct tenant. Even after deleting the msalchache file and re-connecting to my tenant, it says "Installed" in the queue.
Is there a way to force a new Upload?

Thanks and best regards.
Andreas

**Comment by rzander** [comment]
Make sure that "MasterPackager" is not installed on the local machine.... Always use a "blank" Machine to create Apps in Intune.

**Comment by al-itc** [comment]
Sorry for the newbie issue, Roger, and thanks for reminding me :-)
