### ISSUE TITLE
RZGet install returns a " Reference not set to an instance of an object"

### ISSUE THREAD

**Issue by dezihh** [rzander/ruckzuck#266]
command executed: `.\RZGet install RuckZuck`
Returned Error: 
```
ROMAWO GmbH RuckZuck 1.7.3.5
Downloading...Error: Object reference not set to an instance of an object.
```

Environment Windows 11 Sandbox
Tried with cmd and Powershell in Sandbox

**Comment by dezihh** [comment]
Updated RZGet, now it works, sorry

**Comment by rzander** [comment]
The "RuckZuck" Package is an update for the portable RuckZuck.exe ... You cannot "install" RuckZuck, but if you have an outdated RuckZuck.exe, you will get this Package as an update and it will replace the exe. But this does only work if your run RuckZuck.exe... 
RZGet.exe cannot install or update RuckZuck.exe
