### ISSUE TITLE
Issue with TortoiseSVN, Deploy on TS

### ISSUE THREAD

**Issue by Keywan2009** [rzander/ruckzuck#267]
Hi,

I have a Task Sequence and I added a new step **"Install Application"** and put in there **"TortoiseSVN"**.
The Ts does work fine until that step, it show me **"Install TortoiseSVN-1.14.7.29687-x64-svn-1.14.3"** and stay a long time. until I switch out the machine.

After reboot the machine I see on the programs and feature, the **"Install TortoiseSVN-1.14.7.29687-x64-svn-1.14.3"** is installed but does not work.

Here is PS script

Set-Location $PSScriptRoot;
$proc = (Start-Process -FilePath "msiexec.exe" -ArgumentList "/i `"TortoiseSVN-1.14.7.29687-x64-svn-1.14.3.msi`" /qn ALLUSERS=2 REBOOT=REALLYSUPPRESS" -Wait -PassThru);$proc.WaitForExit();$ExitCode = $proc.ExitCode
Exit($ExitCode)

![image](https://github.com/user-attachments/assets/dcca15ef-db51-46f0-96de-778d7e3b519b)

Is that the issue that the Step **"Install TortoiseSVN-1.14.7.29687-x64-svn-1.14.3"**  stay and does not nothing?

can you help me?

**Comment by rzander** [comment]
You should ask TortoiseSVN for support.... 
I just checked the latest TortoiseSVN Package in RuckZuck and it does silently install... Maybe you should try to change the order of the package installation.... try to install it at the very beginning, to see if there is a conflict with another package...

**Comment by Keywan2009** [comment]
I have checked the appdiscovery.log and appenforce.log and see by TortoiseSVN the following error
Maybe 60 second to littel time
Failed to read script execution time-out from policy. Use default 60 seconds. task sequence
