### ISSUE TITLE
Uninstall with rzget.exe

### ISSUE THREAD

**Issue by s1lverl1ne** [rzander/ruckzuck#270]
I see in your repository that you have an uninstall string in an application's json file. Is there a way to use this with the rzget.exe command line tool?

**Comment by rzander** [comment]
With the latest Version, you can use the uninstall parameter:
**UnInstall:**  
UnInstall a Software from Shortname : `RZGet.exe uninstall "<Shortname>"[;"<Shortname2>"] [/cleanup]`  
UnInstall a Software from JSON File : `RZGet.exe uninstall "<JSON full path>"[;"<JSON full path>"]`  
UnInstall a Sepcific Version : `RZGet.exe uninstall --name "<ProductName>" --vendor "<Manufacturer>" --version "<ProductVersion>"`  

>Note: The Uninstall is not tested for every version and may not always work. Please provide feedback if you see some packages where uninstall can be improved...
