### ISSUE TITLE
Unsuccessfull download of .NET Core Runtime 3.1.32.31916

### ISSUE THREAD

**Issue by hopalongrock** [rzander/ruckzuck#271]
Hello!

Using Windows 10 Home x64, version 22H2 (OS Build 19045.5011)

RuckZuck found:

Microsoft .NET Core Runtime 3.1 (x64)
New Version: 3.1.32.31916 Old Version: 3.1.32.31915
Manufacturer: Microsoft Corporation

Start updating:

RuckZuck Installation Queue
Microsoft .NET Core Runtime - 3.1.32 (x64)
Status: Waiting
Downloaded: 0 %

The download doesn't begin.

**Comment by rzander** [comment]
Fixed..
It may have been intentional to show that the product is no longer supported since December 13, 2022.
