### ISSUE TITLE
ApiKey request

### ISSUE THREAD

**Issue by Ytraxx** [rzander/ruckzuck#272]
Hi, It's possible to have APi key for use GetSoftwares API function ? 
Thanks

**Comment by rzander** [comment]
Please send am mail to roger at zander.ch ... 
>Note:  Since August24, there is a rate limit which does also affect requests with API-Keys: https://github.com/rzander/ruckzuck?tab=readme-ov-file#august-2024-rate-limiting-on-public-infrastructure
