### ISSUE TITLE
Old version of Sublime Text 3 not correctly detected on first run

### ISSUE THREAD

**Issue by sschuberth** [rzander/ruckzuck#28]
The current detection script for Sublime Text 3 is

```
if ((Get-ItemProperty -path 'HKLM:\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\SUBLIME TEXT 3_IS1' -Name DisplayVersion -ea SilentlyContinue | Select-Object -exp DisplayVersion) -eq '3.0.3176') { return $true } else { 
    if ((Get-ItemPropertyValue -path 'HKLM:\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\SUBLIME TEXT 3_IS1' -Name DisplayName -ea SilentlyContinue) -eq 'Sublime Text Build 3176') {
        New-ItemProperty -Path 'HKLM:\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\SUBLIME TEXT 3_IS1' -Name DisplayVersion -PropertyType String -Value '3.0.3176'; return $true
    } else {  return $false }
}
```

That is, if RuckZuck is run for the first time, initially the "Old Version" of Sublime Text 3 is not detected (it shows an empty string in the overview), but as the detection script actually writes (!) the `DisplayVersion` key (that is used for the "Old Version") to the registry, subsequent runs of RuckZuck *will* actually show the "Old Version".

Two thoughts here:
1. I believe it's back practice to let the detection script *write* to the registry. Esp. when using RuckZuck as a portable tool, that behavior is certainly unexpected.
2. It's not nice that the "Old Version" is only displayed correctly after starting RuckZuck a second time.

To solve both issues, I'd suggest to let the detection script not return `$true` or `$false`, but the version string of the installed version. The comparison of that returned version to the latest version could then be done internally by RuckZuck.

**Comment by rzander** [comment]
I agree, the detection script should not write any keys.. will fix that.

The Problem with Sublime (and some other tools) is that they do not have a DisplayVersion at all. RuckZuck requires a DisplayVersion to find the latest version of a product.

Fixes: 
- Changed detection script to ignore DisplayVersion:
```
if ((Get-ItemPropertyValue -path 'HKLM:\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\SUBLIME TEXT 3_IS1' -Name DisplayName -ea SilentlyContinue) -eq 'Sublime Text Build 3176') { return $true } else { return $false }
```
- Excluded "Sublime Text Build 3176" without Version from getting Updates

This should work until a new Version is released...
