### ISSUE TITLE
SCCM Plugin - Run update of existing apps from command line

### ISSUE THREAD

**Issue by ktrsccm** [rzander/ruckzuck#29]
Is it possible to automate the update of existing applications using the SCCM plugin?  I attempted to use this script: http://rzander.azurewebsites.net/update-existing-sccm-applications-with-ruckzuck/ 

I edited it to point to the new exe name and the updated assembly import, and it runs without any errors.  However, the last line of "$RZ.Run()" doesn't seem to actually do anything (though it doesn't error out and the script is properly pulling package shortnames from SCCM.)  Is this functionality deprecated?

**Comment by ktrsccm** [comment]
Yes, but I'd like to automate that.  I have a script that notifies me when new version of software are released.  I'd like to be able to kick off the update using the SCCM plugin via that same script  (instead of having to login and click the button.)  That way it's already in SCCM and all I have to do manually is test and then supersede.  Is there a way to make that happen?

**Comment by rzander** [comment]
I think, the current version does no not have the "hidden" PowerShell module included… So it's currently not possible to fully automate application updates.  

I will check how much effort it is to implement a fully automated way to update...

**Comment by ktrsccm** [comment]
Any news on this?  Thanks!

**Comment by rzander** [comment]
https://github.com/rzander/ruckzuck/issues/56
