### ISSUE TITLE
Error launching on windows 7

### ISSUE THREAD

**Issue by mr-aleks** [rzander/ruckzuck#3]
Greetings, I try to run RuckZuck 1.5.2.0 on Windows 7 (64bit) but I get an error when I start the program
![virtualbox_windows 7_20_05_2017_23_58_02](https://cloud.githubusercontent.com/assets/23143866/26279319/0de5823c-3db9-11e7-86aa-e9cd9a59621c.png)
![virtualbox_windows 7_20_05_2017_23_59_21](https://cloud.githubusercontent.com/assets/23143866/26279318/0de2e298-3db9-11e7-9b89-bf17f9695c16.png)
![virtualbox_windows 7_21_05_2017_00_02_42](https://cloud.githubusercontent.com/assets/23143866/26279320/0de8f3ae-3db9-11e7-82e8-206db3b96314.png)
What is the problem? I have installed NET Framework 4.6

**Comment by rzander** [comment]
The Tool requires also PowerShell4. What Version of PowerShell do you have? Run in PowerShell `(get-Host).Version` to get the PS Version.... Can you reproduce the error on another Win7 machine?

As the Error mentioned something like "System.IO.FileNotFound.." , the only thing it does load from file is  a custom repository?!  I would recommend to delete all existing user configurations stored in "%localappdata%\Zander_Tools\RuckZuck*" to remove all custom repositories...

**Comment by mr-aleks** [comment]
@rzander Thanks for the answer, I really did not have powershell installed, installed it and the program worked. I apologize for the carelessness.

**Comment by rzander** [comment]
The downloads are stored in Users %TEMP%. Every Package will create a Sub-Folder and the Foldername is the ContentID of the Package. You can right click a downloaded package and select "Open download path..." to open the Folder.

**Comment by mr-aleks** [comment]
@rzander thanks for the answer. I really liked your application, this is what I wanted. But I have a wish, сan I change the folder in which the installers of the programs are downloaded?
Ideally, for me it would be great if the program was able to download programs to a folder next to eXe, and offered to install them after downloading them. After all, not always and everywhere there is an Internet, I want to download the necessary programs at home to go to a person and install them, but what if there is no internet? (Can eat but I do not know for sure) ;)

**Comment by rzander** [comment]
There is currently no option to redirect the download path.. maybe in a future release.

**Comment by PeRogger** [comment]
Thanks for the info. after installing PS 4.0 porblem on a Win7 got solved
