### ISSUE TITLE
Ruck Zuck in PXE OS Deployment

### ISSUE THREAD

**Issue by MDemirkiran** [rzander/ruckzuck#30]
Hi,

Is there a way to install these application while in pxe deployment in sccm. When i try I got error.

**Comment by rzander** [comment]
RuckZuck does create "normal" applications without any dependency to the RuckZuck Service. The Applications will use a PowerShell script to trigger the setup and PowerShell is not  available out-of-the-box in WinPE.  
What do you want to do exactly, what is the error you get ?

**Comment by MDemirkiran** [comment]
Dear Roger,
Thank you, you answered the question as "PowerShell is not available out-of-the-box in WinPE"
But as for test purpose when I want to deploy in task sequence with a clean install of Windows 10, I got this error. 
![sccm_app](https://user-images.githubusercontent.com/45977564/50243199-a0af2780-03dd-11e9-97bf-c56edfe229f6.png)
If it can be used in SCCM Task sequence it can become the most amazing tool for SCCM. Already it is the best Tool. :)

**Comment by rzander** [comment]
The Content of the the Application is not distributed to a Distribution Point (In this case, the message is clear). You have to manually (re)-distribute the content to your DP's.  In RZ4CM.exe.config, you can define a DPGroup Name which is used to automatically distribute the content (Default its: "All DP's").

**Comment by MDemirkiran** [comment]
As you said, after distributing the application, it works perfectly. Now I see as the most fantastic tool for SCCM :) Thanks for your quick support Roger.
