### ISSUE TITLE
SCCM 1810 / Plugin issue with update detection

### ISSUE THREAD

**Issue by JuergenMK** [rzander/ruckzuck#31]
After updating to SCCM 1810 and SQL 2017, I do not get the correct updates listed. 
For all downloaded applications the wrong version gets detected and an updated offered.

Any idea how to resolve it?

Since that time I do get an RZError.txt error with the following content:

18.01.2019 12:31:08;F239E1Invalid length parameter passed to the RIGHT function.
SQL:;WITH XMLNAMESPACES ( DEFAULT 'http://schemas.microsoft.com/SystemCenterConfigurationManager/2009/AppMgmtDigest')   SELECT RZID, Shortname, Bootstrap, [Version] FROM  ( SELECT  SDMPackageDigest.value('(/AppMgmtDigest/Application/SoftwareVersion)[1]', 'nvarchar(MAX)') as [Version], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Bootstrap"]/@Value)[1]', 'nvarchar(MAX)') [Bootstrap], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Shortname"]/@Value)[1]', 'nvarchar(MAX)') [Shortname],  RIGHT(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="SWID"]/@Value)[1]', 'nvarchar(MAX)'), LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomId)[1]', 'nvarchar(MAX)')) - 2) AS RZID, vCI.CI_ID FROM v_ConfigurationItems as vCI WHERE CIType_ID = 10 and IsLatest = 1  ) as app WHERE RZID is not null
Connection:Data Source=sccm;Initial Catalog=CM_S01;Integrated Security=True

**Comment by JuergenMK** [comment]
Hi Roger, thanks for the info. In deed the information for SWID, Shortname and Bootstrap are missing. 
I verified the installed version and it is already 1.6.1.6. 
Removing and reinstalling did not help either.
Do you have any ideas?

**Comment by rzander** [comment]
If these attributes are missing, RuckZuck will not detect any updates automatically.  Verify that the information can be written if you create a new Application. What happens if you import the same Application again? will it update the attributes or create a new application ?

**Comment by JuergenMK** [comment]
I just wrote a short PS to get all RuckZuck Apps and list the Shortname, SWID and Bootstrap. My previous message was misleading. All data are there:

Application:  7-Zip 18.06
  --> Display Name      :  7-Zip 18.06 (x64) 18.06 RZ793047
  --> Software Version  :  18.06
  --> Component ID      :  17033191
  -->  Shortname :  7-Zip
  -->  SWID :  RZ793047
  -->  LastModified :  2019-01-23 23:09:48
  -->  Bootstrap :  false

BUT, if I run the following sql command (which I took from the RZError.txt file) in the SQL management studio, then I see an error:

SELECT  SDMPackageDigest.value('(/AppMgmtDigest/Application/SoftwareVersion)[1]', 'nvarchar(MAX)') as [Version], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Bootstrap"]/@Value)[1]', 'nvarchar(MAX)') [Bootstrap], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Shortname"]/@Value)[1]', 'nvarchar(MAX)') [Shortname],  RIGHT(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="SWID"]/@Value)[1]', 'nvarchar(MAX)'), LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomId)[1]', 'nvarchar(MAX)')) - 2) AS RZID, vCI.CI_ID FROM v_ConfigurationItems as vCI WHERE CIType_ID = 10 and IsLatest = 1

the sql command shows me the following:

Version: null
Bootstrap: null
Shortname: null
RZID: null
and CL_ID the correct number of the item

It seems that the SQL command cannot collect the required data from SDMPackageDigest which also states the rzerror.txt
(23.01.2019 23:14:42;F239E1Invalid length parameter passed to the RIGHT function.)
If I run the select command with * then I see the packages, with SDMPackageDigest.value('(/AppMgmtDigest/Application/SoftwareVersion)[1]', 'nvarchar(MAX)')  then null.

It is very curios, because if I extract the title for example, then it works just fine:
SDMPackageDigest.value ('(/AppMgmtDigest/DeploymentType/Title)[1]', 'nvarchar(max)') [Title]
gives me the  the Install_x64 deployment title.

Now I am at the end of my ideas... :-(

**Comment by rzander** [comment]
Attached, the full query from the code:
```
;WITH XMLNAMESPACES ( DEFAULT 'http://schemas.microsoft.com/SystemCenterConfigurationManager/2009/AppMgmtDigest')   SELECT RZID, Shortname, Bootstrap, [Version] FROM  ( SELECT  SDMPackageDigest.value('(/AppMgmtDigest/Application/SoftwareVersion)[1]', 'nvarchar(MAX)') as [Version], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name=\"Bootstrap\"]/@Value)[1]', 'nvarchar(MAX)') [Bootstrap], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name=\"Shortname\"]/@Value)[1]', 'nvarchar(MAX)') [Shortname],  RIGHT(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name=\"SWID\"]/@Value)[1]', 'nvarchar(MAX)'), LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomId)[1]', 'nvarchar(MAX)')) - 2) AS RZID, vCI.CI_ID FROM v_ConfigurationItems as vCI WHERE CIType_ID = 10 and IsLatest = 1  ) as app WHERE RZID is not null
```

Do you get any Results if you run this query ?

**Comment by JuergenMK** [comment]
by using the sql query I get the same issue as logged in RZError.txt:

Msg 536, Level 16, State 5, Line 1
Invalid length parameter passed to the RIGHT function.

If I remove the " - 2" stated in the len parameter, then I get the correct output.

**Comment by rzander** [comment]
What about 
```
;WITH XMLNAMESPACES ( DEFAULT 'http://schemas.microsoft.com/SystemCenterConfigurationManager/2009/AppMgmtDigest')   SELECT RZID, Shortname, Bootstrap, [Version] FROM  ( SELECT  SDMPackageDigest.value('(/AppMgmtDigest/Application/SoftwareVersion)[1]', 'nvarchar(MAX)') as [Version], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name=\"Bootstrap\"]/@Value)[1]', 'nvarchar(MAX)') [Bootstrap], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name=\"Shortname\"]/@Value)[1]', 'nvarchar(MAX)') [Shortname],  RIGHT(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name=\"SWID\"]/@Value)[1]', 'nvarchar(MAX)'), LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name=\"SWID\"]/@Value)[1]', 'nvarchar(MAX)')) - 2) AS RZID, vCI.CI_ID FROM v_ConfigurationItems as vCI WHERE CIType_ID = 10 and IsLatest = 1  ) as app WHERE RZID is not null
```
The original query is referencing CustomId in the assumption that it's the same as SWID... That can be an issue...

**Comment by rzander** [comment]
Can you please check if you have an "Optional reference" defined on your RuckZuck-Applications?
![image](https://user-images.githubusercontent.com/11909453/51844945-ca316c00-2316-11e9-8fd4-ff506d389c3e.png)
The Query is using the "Optional Reference" to give an Admin the option to skip any further updates by removing the RuckZuck-ID from "Optional reference"...

**Comment by rzander** [comment]
The following query should filter unusable "Optional references" ….
```
;WITH XMLNAMESPACES ( DEFAULT 'http://schemas.microsoft.com/SystemCenterConfigurationManager/2009/AppMgmtDigest')   SELECT RZID, Shortname, Bootstrap, [Version] FROM  
( SELECT  SDMPackageDigest.value('(/AppMgmtDigest/Application/SoftwareVersion)[1]', 'nvarchar(MAX)') as [Version], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Bootstrap"]/@Value)[1]', 'nvarchar(MAX)') [Bootstrap], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Shortname"]/@Value)[1]', 'nvarchar(MAX)') [Shortname],  RIGHT(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="SWID"]/@Value)[1]', 'nvarchar(MAX)'), LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomId)[1]', 'nvarchar(MAX)')) - 2) AS RZID, vCI.CI_ID FROM v_ConfigurationItems as vCI WHERE CIType_ID = 10 and IsLatest = 1 and LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomId)[1]', 'nvarchar(MAX)')) > 2 ) as app WHERE RZID is not null
```
Let me know if the query will return results without any errors....

**Comment by rzander** [comment]
Attached an updated Version:
[RZ4CM.zip](https://github.com/rzander/ruckzuck/files/2808925/RZ4CM.zip)

**Comment by JuergenMK** [comment]
Sorry for my late response. I was on a business travel with very limited access to the internet...

The optional reference is available in all the application packages.
The Query two post behind is working well.

After updating the attached files, everything works well 👍 
The error report in the %temp%\rzerror.txt is also gone away

Thank you! You are the best of the best 🥇
