### ISSUE TITLE
Registred user at ruckzuck.tool

### ISSUE THREAD

**Issue by Binkan** [rzander/ruckzuck#36]
How do I register at ruckzuck.tool?

Link doesn't work at http://rzander.azurewebsites.net/ruckzuck-for-configmgr-new-v1-5-18/

https://ruckzuck.tools/Account/Register.aspx

**Comment by rzander** [comment]
RuckZuck does no longer store any user credentials. You can now do everything without having a RuckZuck account… Just make sure you have a Version >= 1.6.2.14

**Comment by Binkan** [comment]
I have that version and are trying to create my own items but "Create exe..." doesn't work even if I close my Antivirus. Test install works fine.
Sorry but if there is a Wiki about this, please tell me

**Comment by rzander** [comment]
Create exe will create the executable in the same Directory as ruckzuck.exe is. If you have "Constrolled Folder Access" enabled, Windows does block creating files on Folders like the desktop. Copy RuckZuck.exe to your %TEMP% directory and try it from there… It's working fine here on V1.6.2.14 (Windows10 1809 x64)

**Comment by Binkan** [comment]
Shame on me, should have notices the block. Works really great. Thanks!
