### ISSUE TITLE
Exit Code 16,389 on all RuckZuck Apps in Task Sequence

### ISSUE THREAD

**Issue by djeronimo** [rzander/ruckzuck#37]
Good Day,

All of the RuckZuck apps I use in my task sequence to build a reference machine exit with code 16,389.  I have custom Application (Office 2016 and SIP client) install fine.  Only the RuckZuck applications faile.

Can you help?

Danny

**Comment by rzander** [comment]
Have you enabled "Allow this application to be installed from ... task sequence...." ?
![image](https://user-images.githubusercontent.com/11909453/53979434-20f84580-410e-11e9-95ad-ca0c18927d92.png)

**Comment by djeronimo** [comment]
Sorry for the delayed response.  I have that option enabled.  I did a test and created a 7-zip application from an MSI and it installed using the same task sequence.  Could it be something with PowerShell script used for the install?  I do have a packaged running a PowerShell script to install .Net 3.5 and it works fine in this task sequence.

Danny

**Comment by rzander** [comment]
PowerShell Version should be V5 and higher. Do you have configured an execution Policy?
 ```Get-ExecutionPolicy -L```
or is PowerShell running in constrained mode (e.g. App-Locker policy)
```$ExecutionContext.SessionState.LanguageMode```

**Comment by djeronimo** [comment]
Hi Roger,

Sorry for my delayed response.  I created all of the app packages from scratch.  Sorry I needed to have my base image update by a deadline, so I had to move forward.

Danny
