### ISSUE TITLE
Product not detected after installation

### ISSUE THREAD

**Issue by stonecrusher** [rzander/ruckzuck#38]
Hi,
although installation is successful, I always receive that error, no matter what update I've had installed:
![2019-03-11 10_00_39-RuckZuck Installation Queue](https://user-images.githubusercontent.com/1388389/54112026-905b8700-43e5-11e9-9ce2-c4d96b1c67b2.png)
RuckZuck 1.7.0.1 (latest)
Windows 8.1x64 (fully updated)

![2019-03-11 11_11_50-RuckZuck Installation Queue](https://user-images.githubusercontent.com/1388389/54116360-d832dc00-43ee-11e9-83c2-774e62ea4910.png)

**Comment by rzander** [comment]
RuckZuck Packages are tested on Win10 x64 (currrent Build)

Every failed installation will trigger an automated test (normally withing 24h) to identify changed download URLs or Version changes... and then, "someone" has to fix the applications ....  or you can also upload fixed versions as RuckZuck is a cummunity driven repository...

**Comment by stonecrusher** [comment]
But the installation did not fail.
So it means RuckZuck can't detect the newer version of the product and I have to create a new package (will try to learn that from the wiki and contribute to the community)?
My problem here is that I can't see which programs were detected and are up to date or if they are simply missing because the package info is out of date.

**Comment by rzander** [comment]
Just did a manual test on Win10 x64 1809 EN:
![image](https://user-images.githubusercontent.com/11909453/54135458-1ee9fb80-441a-11e9-9643-50d6edea232e.png)
Some of your "failed" installations are using `Get-ItemPropertyValue` in the detection script. What is your PowerShell Version ```$PSVersionTable.PSVersion``` as this command does require PS V5+ (if I remember correctly).

**Comment by stonecrusher** [comment]
Aah, that's the culprit.
I got PowerShell 4.0 from Win8.1 and also PowerShell Core 6.1.3 installed afterwards, but you need specifically PowerShell 5.x.
Thank you!
