### ISSUE TITLE
f.lux detection

### ISSUE THREAD

**Issue by stonecrusher** [rzander/ruckzuck#39]
f.lux latest stable is 4.84 which I have installed.
RuckZuck claims to have an update to the older 4.78 but doesn't recognize current version.
![2019-03-11 09_59_41-RuckZuck](https://user-images.githubusercontent.com/1388389/54112147-cb5dba80-43e5-11e9-8509-0d62dfbbba6e.png)

**Comment by rzander** [comment]
Based on the ScreenShot, it seems that f.lux does not store any ProductVersions in Add-RemovePrograms… RuckZuck update detection requires a valid Version to detect updates.

In this case, the Software Vendor has to change the setup routine to store a valid ProductVersion.

**Comment by stonecrusher** [comment]
After a manual reinstall of flux v4.84 it doesn't appear again in RuckZuck, so either something was corrupted, they fixed it or it's invisible to RuckZuck now. We will see in the future.

Things to notice: They have the wrong version info in the Windows Add-Remove Programs dialouge:
![2019-03-11 14_39_35-Programme und Features](https://user-images.githubusercontent.com/1388389/54128094-93696e00-440b-11e9-8102-f2a537685dba.png)

But the right info in their .exe file:
![2019-03-11 14_33_37-Eigenschaften von flux exe](https://user-images.githubusercontent.com/1388389/54127731-c7905f00-440a-11e9-9467-cb6f35e0f8d5.png)

The program by default is not installed to the program folders but rather to `C:\Users\MyName\AppData\Local\FluxSoftware\Flux`.

Thanks for your answer and that nice, easy to use program!

**Comment by rzander** [comment]
f.lux in RuckZuck is now updated to Version 4.84. 
You have to install the Software once with RuckZuck and it will write back the FileVersion into the registry for "Programs and Features" (Control Panel). 

Do you know a way to install f.lux for all users ? it seems that the setup does install it for the current user only...

**Comment by stonecrusher** [comment]
I don't know a way and there's a controversy and some requests about that in the f.lux forum.
The enterprise edition defaults to the programs folder.
One user made a [possibly helpful post](https://forum.justgetflux.com/post/12150).
