### ISSUE TITLE
Snagit, Bootstrapping

### ISSUE THREAD

**Issue by BaddMann** [rzander/ruckzuck#4]
Using the Config-man RuckZuck importer, it's been great for a bunch of apps.
For some reason that I fully don't understand yet, no matter what I choice I keep getting Snagit wrapped in a bootstrap.exe when I'd prefer it in msi.

I've signed up as a user and would love to contribute directly but I've not figured out all the ins and outs of contributing to the repo as of yet.

Please advise.
version: 1.0.1.35722
Same on version: 1.5.18

**Comment by rzander** [comment]
1) Can it be that you aleady have the Snagit App created as Bootstrap? If yes, you have to delete the App and Collection and recreate it (it does remember the type once you have created it).
2) The difference between bootstrap and "normal" is just the size of the file.. E.g. Snagit, you will get an exe in both ways, but the bootstrap .exe is just 60KB and the regular is 100MB.

If you have a RuckZuck Account, you have to logon within the tool:
![image](https://user-images.githubusercontent.com/11909453/27710739-0ab2ceda-5d21-11e7-9a60-04ec0c06d759.png)
![image](https://user-images.githubusercontent.com/11909453/27710796-352adea0-5d21-11e7-9f21-04f93280e24f.png)

Then you should be abe to right click and App ->edit to get the Metadata
![image](https://user-images.githubusercontent.com/11909453/27710840-5d3cc00c-5d21-11e7-8eeb-9e4a5dbec2ab.png)

If you want to upload a new App, I would recommend to use the standalone Tool (not RuckZuck for ConfigMgr). You can install the App on a reference Computer to get most of the details from the installed software when you create a new Software-Item in Ruckzuck.
Just make sure:
- You have enterred the URL,  it will open a file browser to pick the downloaded file to get the chekcsum
- You know how to install it silently -> update the Installation paramters
- Add a description and an Icon
- **Save the File as XML** (So you can mail it to me if something goes wrong)
- Upload it (you should see it as pending on https://ruckzuck.tools)
- Once approved you can Edit it to see what I've changed :-)

Don't hesitate, I will Support you, if there is something wrong with the uploaded App..
