### ISSUE TITLE
Add portable tools like "Autoruns"?

### ISSUE THREAD

**Issue by stonecrusher** [rzander/ruckzuck#41]
Is it possible to add portable tools that have no installer, like [Autoruns](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns)? I constantly forget to update them and googling-downloading-unzipping-cut-paste-deleteRemains is quite unpleasant.
However, there is an always up to date .exe: https://live.sysinternals.com/Autoruns64.exe
I have no idea how the install / detect / uninstall scripts should look like, nor what the default folder path should be.
Sorry for all the requests, I'm not a professional sysadmin.

**Comment by rzander** [comment]
Portables do not have a fixed location nor do they have ProductName and Version registerred. The Sysinternal Tools (inkluding Autoruns) are available as Package where the RuckZuck package will create the required registry keys to detect updates...
