### ISSUE TITLE
RuckZuck SCCM will always Update all Applications

### ISSUE THREAD

**Issue by AnsgarGeers** [rzander/ruckzuck#42]
I have today installed, newest Update of SCCM  5.0.8740.1000.
All works fine.
but Every Start of RuckZuck, he will always all Applications (65).
I uninstalled and deleted the Config, newly installed 1.6.2.14
and Edited the Config File.
no error log is created
Any additional Information needed, and/or any Idea?

**Comment by rzander** [comment]
There is a temporary fix available for this issue: https://github.com/rzander/ruckzuck/releases/tag/1.6.2.15 (just replace the existing RZ4CM.exe)

Version 1.7.0.1 with a full setup is comming soon...

**Comment by AnsgarGeers** [comment]
Fast and Perfect Help
Thanks! Thanks! Thanks!
