### ISSUE TITLE
SMS Provider Error.

### ISSUE THREAD

**Issue by aaronflaugh** [rzander/ruckzuck#43]
hello, 

I am getting an SMS provider error when trying to sync software into my SCCM 1810 environment.  It was working like a week ago.  I am also unable to find the RZerror.txt file to further troubleshoot on my end.  

Any suggestions?

Aaron

**Comment by rzander** [comment]
- Verify "CM_Server" in RZ4CM.exe.config 
- Try V1.7.0.1 (https://github.com/rzander/ruckzuck/releases/download/1.7.0.1/RZ4ConfigMgrSetup.exe)
 Note: Backup your RZ4CM.exe.config and Transfer all required values into the new RZ4CM.exe.config.. But do **not** just copy the old file !!!
