### ISSUE TITLE
Issue with OneGet provider?

### ISSUE THREAD

**Issue by ktrsccm** [rzander/ruckzuck#44]
As of Monday (4-8), I'm experiencing issues using the OneGet provider in Powershell.  A couple machines that I have it installed on no longer return any packages when using the Find-Package cmdlet.  When I run Get-PackageProvider, I see RuckZuck in the list.  However I do not see RuckZuck when I run Get-PackageSource.  

I have installed the OneGet provider fresh on two machines that did not have it previously and those machines seem to work just fine.  I have tried a repair of the provider and then an uninstall/reboot/reinstall of the provider to no avail.  Any advice?  Thanks!

**Comment by rzander** [comment]
What is the endoint URL you get from `(Get-PackageSource ruckzuck).Location` ? You should get https://cdn.ruckzuck.tools …  I assume you have V1.7.0.2 ( `Get-PackageProvider ruckzuck` )

**Comment by ktrsccm** [comment]
Hi Roger,

On the machines that aren't working, I get nothing back from that command as RuckZuck is not listed when I run Get-PackageSource.  Running Get-PackageProvider shows that I have RuckZuck v1.7.0.2 installed.

**Comment by rzander** [comment]
Just to confirm, do you have some settings in HKLM:\SOFTWARE\Policies\RuckZuck from the previous version ?

**Comment by ktrsccm** [comment]
Nope, I don't see anything there.

**Comment by rzander** [comment]
On https://github.com/rzander/ruckzuck/blob/master/RZ.OneGetProvider/RuckZuck.cs I see that it loads an existing URL (void _initRZ, Line 29) from Properties.Settings.Default.Location which is a User Setting (somewhere in a user.config in %LOCALAPPDATA%\apps\2.0\.... )
Question: Do you still have the issue if you logon with a new account ?
Do you see some additional Errors if you enable Debugging in PowerShell `$DebugPreference = 'Continue'`

**Comment by rzander** [comment]
...also try to unregister the packageSource `Unregister-PackageSource -Provider RuckZuck -Name
RuckZuck -Force` as it will set the values back to default...

**Comment by ktrsccm** [comment]
I tried logging in with a new account, confirmed there's nothing in %localappdata%\apps\, and the issue still persists.

I found some older user.config files in "%localappdata%\Zander_Tools" that I deleted and then reinstalled the provider, but this did not help.  

On my account, there doesn't seem to be any other files named user.config in the %localappdata%.  I ran a script to use select-string on all files in %localappdata% with .config extensions to match all or part of "properties.settings.default.location" and came up with nothing. 

I had tried the unregister-packagesource cmdlet previously, though it fails because ruckzuck does not show up in packagesources, only packageproviders. 

Definitely scratching my head at this point :)

**Comment by rzander** [comment]
Do you get any debug output on:
```
$DebugPreference = 'Continue'
Register-PackageSource  -Name RuckZuck -Location "https://test.com" -Provider RuckZuck
Get-PackageSource -Provider RuckZuck
```
..strange behavior...

**Comment by ktrsccm** [comment]
`DEBUG: 00:00:00.0000003 Calling 'RuckZuck::GetDynamicOptions' Provider
DEBUG: 00:00:00.0031387 Calling 'RuckZuck::GetDynamicOptions' Source
DEBUG: 00:00:00.0177456 Calling 'RuckZuck::ResolvePackageSources'
DEBUG: 00:00:00.5112929 RZ112: One or more errors occurred.
DEBUG: 00:00:00.5404007 Calling 'RuckZuck::AddPackageSource' 'RuckZuck','https://test.com','False'
DEBUG: 00:00:00.0000004 Calling 'RuckZuck::GetDynamicOptions' Provider
DEBUG: 00:00:00.0078191 Calling 'RuckZuck::GetDynamicOptions' Source
DEBUG: 00:00:00.0137647 Calling 'RuckZuck::ResolvePackageSources'
DEBUG: 00:00:00.5075126 RZ112: One or more errors occurred.
WARNING: Unable to find package sources.`

**Comment by rzander** [comment]
THX, the message "RZ112" gives me a link from where the error comes…  If you start the latest RuckZuck.exe, click on the Gear-Icon (left bottom), what is the REST-API URL you get ?

**Comment by ktrsccm** [comment]
![image](https://user-images.githubusercontent.com/44708810/55958694-edd63400-5c2e-11e9-86b7-91425b792d10.png)

**Comment by rzander** [comment]
That's an old RuckZuck.exe version, can you please check with V1.7.0.2 … The OneGet Provider and RuckZuck.exe have the same Code to get the REST-API URL. If it's working with RuckZuck.exe it should also work with OneGet Provider... if it's ok with RuckZuck.exe, the Problem must be in the user.config from OneGet (which is located somewhere..)

**Comment by ktrsccm** [comment]
Wow, I have no idea how I got that old version.  The date copied was from yesterday so I assumed it was new.

The new version shows https://cdn.ruckzuck.tools for the REST-API

**Comment by rzander** [comment]
Ok, RuckZuck is able to get the URL... Attached a Version of the OneGet Provider which does reset the location if it does not exist... Do you get the same error as before ? (replace "C:\Program Files\RuckZuck for OneGet\RuckZuckProvider.dll")
[RuckZuckProvider.zip](https://github.com/rzander/ruckzuck/files/3068817/RuckZuckProvider.zip)

**Comment by rzander** [comment]
Another Version which does no longer store any data in a user.config
[RuckZuckProvider.zip](https://github.com/rzander/ruckzuck/files/3068928/RuckZuckProvider.zip)

**Comment by rzander** [comment]
Another version:
[RuckZuckProvider.zip](https://github.com/rzander/ruckzuck/files/3069637/RuckZuckProvider.zip)
The first command you should enter is `$DebugPreference = 'Continue'` to enable verbuse debug messages...

**Comment by ktrsccm** [comment]
Here's what I get with that last .dll

![image](https://user-images.githubusercontent.com/44708810/55983240-4671f500-5c60-11e9-96f8-3a576ea70995.png)

**Comment by rzander** [comment]
Sorry, my fault... if you set the location to http://test.com, RuckZuck will not work ...
jsut close all sessions and run 
```
$DebugPreference = 'Continue'
Get-PackageSource -Provider RuckZuck
```
and you should get "https://cdn.ruckzuck.tools" as location...

**Comment by ktrsccm** [comment]
> DEBUG: 00:00:00.0000003 Trying provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
> DEBUG: 00:00:00.0002320 Trying provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
> DEBUG: 00:00:00.0005011 Trying provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
> DEBUG: 00:00:00.0006934 Trying provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
> DEBUG: 00:00:00.0007196 Attempting loading of assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
> DEBUG: 00:00:00.0008371 Attempting loading of assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
> DEBUG: 00:00:00.0008602 Trying provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
> DEBUG: 00:00:00.0008827 Attempting loading of assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
> DEBUG: 00:00:00.0010057 Attempting loading of assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
> DEBUG: 00:00:00.0010204 Trying provider assembly: C:\Program
> Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
> DEBUG: 00:00:00.0011990 Trying provider assembly: C:\Program Files\RuckZuck for OneGet\RuckZuckProvider.dll
> DEBUG: 00:00:00.0019445 Attempting loading of assembly: C:\Program Files\RuckZuck for OneGet\RuckZuckProvider.dll
> DEBUG: 00:00:00.0020498 Attempting loading of assembly: C:\Program
> Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
> DEBUG: 00:00:00.0022574 Attempting loading of assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
> DEBUG: 00:00:00.0034828 Acquiring providers for assemblyC:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
> DEBUG: 00:00:00.0035069 Acquiring providers for assemblyC:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
> DEBUG: 00:00:00.0035140 Acquiring providers for assemblyC:\Program Files\RuckZuck for OneGet\RuckZuckProvider.dll
> DEBUG: 00:00:00.0036463 Acquiring providers for assemblyC:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
> DEBUG: 00:00:00.0036977 Acquiring providers for assemblyC:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
> DEBUG: 00:00:00.0040265 Acquiring providers for assemblyC:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
> DEBUG: 00:00:00.0041812 Acquiring providers for assemblyC:\Program
> Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
> DEBUG: 00:00:00.0434166 Registering providers via metaproviders for assembly
> Microsoft.PackageManagement.MetaProvider.PowerShell.Internal.PowerShellMetaProvider
> DEBUG: 00:00:00.0941055 Initializing provider 'Programs'
> DEBUG: 00:00:00.0960277 Initializing provider 'WebDownloader'
> DEBUG: 00:00:00.1023754 Initializing provider 'NuGet'
> DEBUG: 00:00:00.1035302 Initializing provider 'msi'
> DEBUG: 00:00:00.1046009 Initializing provider 'zipfile'
> DEBUG: 00:00:00.1070062 Initializing provider 'RuckZuck'
> DEBUG: 00:00:00.1081886 Initializing provider 'Bootstrap'
> DEBUG: 00:00:00.1142135 Initializing provider 'msu'
> DEBUG: 00:00:00.1181340 Provider 'WebDownloader' Initialized
> DEBUG: 00:00:00.1181659 Using Downloader Provider WebDownloader
> DEBUG: 00:00:00.1221915 Calling 'msi::InitializeProvider'
> DEBUG: 00:00:00.1221897 Calling 'Programs::InitializeProvider'
> DEBUG: 00:00:00.1222298 Provider 'msi' Initialized
> DEBUG: 00:00:00.1222327 Provider 'Programs' Initialized
> DEBUG: 00:00:00.1222562 Using Package Provider msi
> DEBUG: 00:00:00.1222546 Using Package Provider Programs
> DEBUG: 00:00:00.1252220 Provider 'zipfile' Initialized
> DEBUG: 00:00:00.1257379 Using Archiver Provider zipfile
> DEBUG: 00:00:00.1449172 Calling 'NuGet'::'InitializeProvider'.
> DEBUG: 00:00:00.1449635 Provider 'NuGet' Initialized
> DEBUG: 00:00:00.1449845 Using Package Provider NuGet
> DEBUG: 00:00:00.1500247 Initialize Bootstrapper
> DEBUG: 00:00:00.1501430 Calling 'msu::InitializeProvider'
> DEBUG: 00:00:00.1501640 Provider 'msu' Initialized
> DEBUG: 00:00:00.1501765 Using Package Provider msu
> DEBUG: 00:00:00.1527648 Trying to register metaprovider
> DEBUG: 00:00:00.1531539 Calling 'WebDownloader::GetFeatures'
> DEBUG: 00:00:00.1535157 Calling 'Programs::GetFeatures'
> DEBUG: 00:00:00.1539395 Calling 'msi::GetFeatures'
> DEBUG: 00:00:00.1546927 Provider 'Bootstrap' Initialized
> DEBUG: 00:00:00.1547071 The provider 'Programs' is imported
> DEBUG: 00:00:00.1547226 Using Package Provider Bootstrap
> DEBUG: 00:00:00.1554310 Calling 'RuckZuck::InitializeProvider'
> DEBUG: 00:00:00.1560203 The provider 'msi' is imported
> DEBUG: 00:00:00.1562713 Calling 'zipfile::GetFeatures'
> DEBUG: 00:00:00.1563185 SUCCESS provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
> DEBUG: 00:00:00.1569546 SUCCESS provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
> DEBUG: 00:00:00.1597969 Initializing PowerShell MetaProvider
> DEBUG: 00:00:00.1613720 Calling 'msu::GetFeatures'
> DEBUG: 00:00:00.1616086 The provider 'msu' is imported
> DEBUG: 00:00:00.1621754 SUCCESS provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
> DEBUG: 00:00:00.1656804 Calling 'Bootstrap::GetFeatures'
> DEBUG: 00:00:00.1670058 The provider 'Bootstrap' is imported
> DEBUG: 00:00:00.1673678 SUCCESS provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
> DEBUG: 00:00:00.1727331 Calling 'NuGet'::'GetFeatures'.
> DEBUG: 00:00:00.1748146 The provider 'NuGet' is imported
> DEBUG: 00:00:00.1764817 SUCCESS provider assembly: C:\Program
> Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
> DEBUG: 00:00:00.1923523 Calling 'WebDownloader::DownloadFile'
> 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409','C:\Users\robertskt\AppData\Local\Temp\Microsoft.PackageMa
> nagement\schnooxe.10x','40000','False'
> DEBUG: 00:00:00.2483907 Attempting to load PowerShell Provider Module [C:\Program
> Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1]
> DEBUG: 00:00:00.4960130 Calling 'WebDownloader::DownloadFile'
> 'https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag','C:\Users\robertskt\AppData\Local\Temp\Micr
> osoft.PackageManagement\bauvren2.lqh','40000','False'
> DEBUG: 00:00:00.5267875 Calling 'WebDownloader::DownloadFile'
> 'https://onegetcdn.azureedge.net/providers/psl-1.0.0.210.package.swidtag','C:\Users\robertskt\AppData\Local\Temp\Micros
> oft.PackageManagement\1jai2z2c.3dh','40000','False'
> DEBUG: 00:00:00.5839254 Calling 'WebDownloader::DownloadFile'
> 'https://onegetcdn.azureedge.net/providers/ChocolateyPrototype-2.8.5.130.package.swidtag','C:\Users\robertskt\AppData\L
> ocal\Temp\Microsoft.PackageManagement\g0oy3yom.sfu','40000','False'
> DEBUG: 00:00:00.8496470 Loaded PowerShell package provider: '[C:\Program
> Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1]'.
> DEBUG: 00:00:00.8524992 Loaded PowerShell Provider: PowerShellGet
> DEBUG: 00:00:00.8535339 Initializing provider 'PowerShellGet'
> DEBUG: 00:00:00.8570843 Calling New() : MethodName = 'InitializeProvider'
> DEBUG: 00:00:00.8608517 INVOKING PowerShell Fn Initialize-Provider with args  that has length 0
> DEBUG: 00:00:00.8932972 In PowerShellGet Provider - 'Initialize-Provider'.
> DEBUG: 00:00:00.8936355 PowerShell Script 'PSModule' Function 'Initialize-Provider' returns null.
> DEBUG: 00:00:00.8945018 Done calling powershell «Initialize-Provider» «PSModule»
> DEBUG: 00:00:00.8945748 Provider 'PowerShellGet' Initialized
> DEBUG: 00:00:00.8945906 Using Package Provider PowerShellGet
> DEBUG: 00:00:00.9002214 Calling New() : MethodName = 'GetFeatures'
> DEBUG: 00:00:00.9010612 INVOKING PowerShell Fn Get-Feature with args  that has length 0
> DEBUG: 00:00:00.9132723 In PowerShellGet Provider - 'Get-Feature'.
> DEBUG: 00:00:00.9249114 Done calling powershell «Get-Feature» «PSModule»
> DEBUG: 00:00:00.9250411 The provider 'PowerShellGet' is imported
> DEBUG: 00:00:00.9265162 SUCCESS provider assembly: C:\Program
> Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
> DEBUG: 00:00:02.0736309 Provider 'RuckZuck' Initialized
> DEBUG: 00:00:02.0736540 Using Package Provider RuckZuck
> DEBUG: 00:00:02.0795971 Calling 'RuckZuck::GetFeatures'
> DEBUG: 00:00:02.0799373 The provider 'RuckZuck' is imported
> DEBUG: 00:00:02.0803839 SUCCESS provider assembly: C:\Program Files\RuckZuck for OneGet\RuckZuckProvider.dll
> DEBUG: 00:00:02.6232420 Calling 'RuckZuck::GetDynamicOptions' Provider
> DEBUG: 00:00:02.6276869 Calling 'RuckZuck::GetDynamicOptions' Source
> DEBUG: 00:00:02.8069496 Calling 'RuckZuck::ResolvePackageSources'
> WARNING: Unable to find package sources.

**Comment by rzander** [comment]
The following Version does have a hardcoded location:
[RuckZuckProvider.zip](https://github.com/rzander/ruckzuck/files/3073526/RuckZuckProvider.zip)
.. so it MUST return "https://ruckzuck.azurewebsites.net"

Are you behind a Proxy ?
