### ISSUE TITLE
Powershell detection rule causing 'this software is not applicable to your device' ConfigMgr 1810

### ISSUE THREAD

**Issue by ensignvorik** [rzander/ruckzuck#46]
Latest version of Ruckzuck for config mgr (Noticed it's below the other versions) 

Confirmed all clients are running Powershell 5. 

Windows 10 clients are 1803 Enterprise. Not tried with any other Win10 versions.

Applications created with Ruckzuck all fail when the detection rule is set to powershell script. If I manually change the detection rule for example to file and version number or MSI code the application installs fine.

Nothing appears in the appdeploy.log at all for the failures.

Have confirmed this by creating application with ruckzuck, and then copying the application, changing the detection method, deploying both, attempting to install with the PS detection first (fails with this software is not applicable to your device' and then done the modified install and that's fine. I've removed any OS requirements from my ruckzuck config files.

Apps in question Firefox, 7-Zip MSI, SumatraPDF

I have another ConfigMgr setup that I will have access too tomorrow that has an older Ruckzuck and is running 2012 R2 and Win 10 clients on 1709 so will try to replicate the issue there too, or see if I can notice what the difference is!

In meantime, any ideas?

**Comment by rzander** [comment]
Can you please check the PowerShell execution policy... 
![image](https://user-images.githubusercontent.com/11909453/56262515-45691980-60df-11e9-83f5-6b0f577ced9b.png) and in PS : ` Get-ExecutionPolicy -l`

**Comment by ensignvorik** [comment]
Thanks, yes there's a collection of machines with this setting set to signed only. Didn't even think of checking this so apologies in advance (maybe worth mentioning it in the troubleshooting doc) \

Will check with customer if this is by design for some reason. Thanks again.
