### ISSUE TITLE
Unable to Uninstall packages with RuckZuck OneGet provider

### ISSUE THREAD

**Issue by darthsinus** [rzander/ruckzuck#47]
We are unable to uninstall packages with the RuckZuck OneGet Provider.

For example: When we run the 'Uninstall-Package -ProviderName RuckZuck "PuTTY"' or 'Uninstall-Package -ProviderName RuckZuck "PuTTY release 0.71 (64-bit)"' we get no error message and the command appears to work fine but the software is not being uninstalled from the system.

If we use the wrong software name then a 'No Package Found' error is returned as expected.

The application was installed with the RuckZuck OneGet provider which worked really well.

We are seeing this behaviour with multiple packages, none of which uninstall when the appropriate command is run, whether they have been installed with the RuckZuck OneGet provider or installed manually and no error messages are produced.

**Comment by rzander** [comment]
I just did a test and I was able to install and uninstall Putty....
![image](https://user-images.githubusercontent.com/11909453/57927570-b3eff180-78ae-11e9-802d-38c6b18a3ebf.png)

As RuckZuck is just running some PowerShell scripts, try to run the Uninstall script for Putty to check if there are any errors...

In general, I do not test the uninstall of a RuckZuck package... so the success rate will be lower than on installation. But please report any packages with issues during uninstall...

**Comment by darthsinus** [comment]
Thanks for looking at this.

I have done some more testing and the problem only occurs when I run a powershell command from a cmd prompt. But only the uninstall fails to work, an install works as expected:

From PowerShell "Install-Package -provider ruckzuck putty" - Works as expected.

From PowerShell "unInstall-Package -provider ruckzuck putty" - Works as expected.

From CMD "powershell.exe Install-Package -ProviderName RuckZuck putty" - Works as expected.

From CMD "powershell.exe Uninstall-Package -ProviderName RuckZuck putty" - Appears to work but does not uninstall the package.

![image](https://user-images.githubusercontent.com/32702390/57931007-4f816200-78af-11e9-8d61-259fd83a169b.png)

I am unable to reproduce this behaviour by installing and uninstalling jquery from nuget so I don't think the issue is with OneGet but don't know enough about the subject to say for sure.

I am attempting to wrap these commands up as SCCM applications to ensure we always deploy the latest version of common software for a minimal time cost. If we can get this working we plan on deploying a RuckZuck Cache container locally to save on bandwidth.

I will try putting each command in to it's own .ps1 file and running those in an SCCM Application Deployment to see if that makes a difference.

**Comment by darthsinus** [comment]
I have tested by creating a .ps1 file containing "Uninstall-Package -ProviderName RuckZuck putty" which is deployed from SCCM. This ends with exit code 0 for success but the application is still not uninstalled.

**Comment by rzander** [comment]
if you have SCCM, you should try the RuckZuck for ConfigMgr Plugin... No need to write your own script, it will create application, deployment type, collections etc for you ... you can create the app with a bootstrap exe (~60KB) where the content is downloaded from the internet or you can download and distribute the sources with sccm...

**Comment by darthsinus** [comment]
We do use the SCCM Plugin, but wanted to reduce the amount of time spent removing old applications and their source files when an application is updated by always deploying the latest available version. I wasn't aware the app could be created with a bootstrap .exe, where can that be configured? I can't see it in the RZ4CM.exe.config file.

**Comment by darthsinus** [comment]
Just fount the method to create a bootstrap.exe, I'll try re-creating a couple of packages to see how we get on. 

Thanks for your help.
