### ISSUE TITLE
Can not install multiple packages in one PS session

### ISSUE THREAD

**Issue by AKugaseelan** [rzander/ruckzuck#49]
If I want to install two or more packages, I can not do it in one PowerShell session. The first package gets installed, and then the second one doesn't throw any errors. It exits without doing anything. I have to close the PowerShell windows and then reopen it, before I am able to install the second application.

**Comment by rzander** [comment]
Ok, I can reproduce it... It's a bug.

**Comment by rzander** [comment]
Fixed in V1.7.0.3
https://github.com/rzander/ruckzuck/commit/f4b92a181396f4cd41aa59fefd3e60b115b42415

**Comment by rzander** [comment]
V1.7.0.3 preview:
[RuckZuckProvider.zip](https://github.com/rzander/ruckzuck/files/3466285/RuckZuckProvider.zip)
