### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by DanielJelinek** [rzander/ruckzuck#5]
Hello Mr. Zander,

first of all, great work, i like this project very much.
I have a general question: Should it be possible to install the imported applications even in a task sequence action ("install application") or is it only possible to install the applications with a deployment to a collection? 

I noticed an general error 16389 in the log when trying to install it in a task sequence. Maybe i did something wrong. My self-created applications are working fine in the TS.

Best Regards and thanks for your work!

Daniel

**Comment by rzander** [comment]
Hi Daniel,

The Applications imported from RuckZuck are "normal" Applications... nothing special. From a previous question I remember some Issues with the PowerShell execution policy. RuckZuck is creating a PowerShell script for the installation; make sure that you have set the execution policy to "Bypass" (ConfigMgr ClientSettings\Computer Agent\Powershell execution policy )

Regards

Roger
