### ISSUE TITLE
OneGetProvider Install specific Version

### ISSUE THREAD

**Issue by abeggled** [rzander/ruckzuck#50]
How can I install a specific version (i.e. 7-Zip 18.06) if version 19.00 is already published in catalog?
If this is not possible know, is there a chance to implement this?

**Comment by rzander** [comment]
I think this is currently not possible. As the RuckZuck REST API does support getting older version 
```Invoke-RestMethod -Uri "https://cdn.ruckzuck.tools/rest/v2/getsoftwares?name=ruckzuck&ver=1.6.2.14&man=Zander%20Tools"``` 
I will try to implement this into the OneGet provider....

**Comment by rzander** [comment]
In V1.7.0.3 you have two new optional parameters on Install-Package:
- Manufacturer (to overwrite the Manufactuer"
- ProductVersion (to select an alternative Version)
