### ISSUE TITLE
 RuckZuck Tools

### ISSUE THREAD

**Issue by dj3ecuador** [rzander/ruckzuck#51]
i can not select more then one app when I try to create new software items. what am I doing wrong?
![Capture](https://user-images.githubusercontent.com/53685157/62420578-8e2ee900-b662-11e9-9b82-c69d9ea5cbfc.PNG)

**Comment by rzander** [comment]
"Create new Software-Item" does allow you to create and upload a new Version of a product to the global repository. The list of Software Items you get, are Products that are installed on your machine but unavailable in the global repository. You can select one, to get the ProductName and Version from your computer but you always have to complete the following Wizzard where you have to define DownloadURL/Hash/Description etc. 

Note that the software will be rejected if thee wizard is not complete or contains wrong informations. Only if you leave your eMail in "Author email", I can send you feedback of what was wrong...

also look at: https://github.com/rzander/ruckzuck/wiki/How-to-create-a-Package-for-the-Repository

Why do you want to multiselect new Software Items ?

**Comment by dj3ecuador** [comment]
I wanted to create one exe or msi
To install multiple applications. I thought that’s what this product 
Could do.

**Comment by rzander** [comment]
not really... You can install multiple application from the repository when using "Instal new Software"... But you cannot crate an single exe that will install a list of apps.

If you want to automate Software installations, you should use RZUpdate.exe (Command Line Tool) or the "RuckZuck Provider for OneGet" (PowerShell) to install multiple applications from the RuckZuck repository.  

What exactly is you use case?

**Comment by dj3ecuador** [comment]
Hi Rodger,

I am looking for a way to install 
Multiple applications “one click”
Create a package that has all the standard apps that I need installed on every machine.

Apps like chrome, drop box, office 365, slack, open VPN and a few more.

Thanks
David

**Comment by rzander** [comment]
With RZUpdate.exe:
```
RZUpdate.exe "Google Chrome";"Dropbox";"Slack";"OpenVPN"
```

With OneGet:
```
$ManagedSW = @("Google Chrome","Dropbox","Slack","OpenVPN")
$ManagedSW | ForEach-Object { Install-Package -ProviderName RuckZuck $_ }
```

>Note: To install Office365 you neet the setup.exe from https://www.microsoft.com/en-us/download/details.aspx?id=49117

> OpenVPN can not be installed silently as you have to approve the TAP Driver which is not signed with a trusted certificate
