### ISSUE TITLE
Webroot detects RUCKZUCK.EXE as "Bad" W32.Malware.Dkvt 

### ISSUE THREAD

**Issue by A9G-Data-Droid** [rzander/ruckzuck#53]
Webroot currently has your GUI binary listed as malware. This will be an ongoing problem unless you work with their engineers to confirm the false positive. I can submit it but this will likely happen every time you release a new version.

> Threat List:
> RUCKZUCK.EXE, W32.Malware.Dkvt, %cache%\,   https://snup.webrootcloudav.com/SkyStoreFileUploader/upload.aspx?MD5=BB33957117685D76232373EA500037B1 BB33957117685D76232373EA500037B1, 
>

**Comment by A9G-Data-Droid** [comment]
Nevermind. I handled it. Note that this may happen again the next time you build a new binary. I would recommend adding a VirusTotal API call step to the build process that will report detection from all AV vendors. That way you can make false positive reports before the final release.

https://developers.virustotal.com/reference

> Thank you for contacting Webroot Support.
> 
> We have researched the logs you have sent in and have whitelisted those files in our back-end database.

**Comment by rzander** [comment]
Thx, I'm using ConfuserEx to compress resources on RuckZuck.exe . If this is making more and more troubles,  I will publish the uncompressed version... I was just nice to keep the tool below 200KB
