### ISSUE TITLE
ruckzuck.exe v 1.7.0.5 not for win 7 ??

### ISSUE THREAD

**Issue by gurikbal** [rzander/ruckzuck#54]
* double click on ruckzuck.exe v 1.7.0.5

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	RuckZuck.exe
  Problem Signature 02:	1.7.0.5
  Problem Signature 03:	5d5d5e2f
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.3130.0
  Problem Signature 06:	5b175e25
  Problem Signature 07:	3bd1
  Problem Signature 08:	14
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

![capture-20190906-083013](https://user-images.githubusercontent.com/36083297/64398016-f1a4a000-d080-11e9-8d01-f0c74dda292f.png)

**Comment by rzander** [comment]
Do you have the PreRequisites installed ?
- .NET 4.6
- PowerShell 5

**Comment by gurikbal** [comment]
i have .NET 4.7.2 installed PowerShell 2.0 (downloading update for)
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-6

**Comment by gurikbal** [comment]
RuckZuck.exe works in win 7 sp1 after updating powershell (Win7-KB3191566-x86.msu)
but it without internet connection gives this error 

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	RuckZuck.exe
  Problem Signature 02:	1.7.0.5
  Problem Signature 03:	5d5d5e2f
  Problem Signature 04:	System
  Problem Signature 05:	4.7.3130.0
  Problem Signature 06:	5b176097
  Problem Signature 07:	a1a
  Problem Signature 08:	b4
  Problem Signature 09:	N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

![capture-20190906-115232](https://user-images.githubusercontent.com/36083297/64405590-258dbe80-d09d-11e9-80a0-c884af74e200.png)

**Comment by rzander** [comment]
Fixed this exception in https://github.com/rzander/ruckzuck/commit/728c8a70a87fc2f79970469af44b1a03dbcaa4ef
