### ISSUE TITLE
Change standard path for SCCM Import

### ISSUE THREAD

**Issue by dpuls** [rzander/ruckzuck#55]
Hello community,

the standard path for a SCCM deployment in my opinion is:
\\localhost\admin$\temp

Where can I change this path for every new RuckZuck Package, I see nothing in the  RZ4CM.exe.config?

Thank
DP

**Comment by rzander** [comment]
In  ..\Microsoft Configuration Manager\AdminConsole\bin\RZ4CM.exe.config
https://github.com/rzander/ruckzuck/wiki/RuckZuck-for-ConfigMgr

To get Updates also set CM_SQLServer, CM_SQLServerDBName ...

**Comment by dpuls** [comment]
CMContentSourceUNC...found it.
Thank you.
