### ISSUE TITLE
Disable OSRequirements?

### ISSUE THREAD

**Issue by StingerGT2** [rzander/ruckzuck#59]
Is there a way to disable the OSRequirements section in the XML file so that the SCCM app OS requirement configuration item is not created?

**Comment by rzander** [comment]
Just remove the OS entries (not the complete section !) in RZ4CM.exe.config:
```XML
            <setting name="OSRequirementsX64" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                    </ArrayOfString>
                </value>
            </setting>
            <setting name="OSRequirementsX86" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                    </ArrayOfString>
                </value>
            </setting>
```

**Comment by StingerGT2** [comment]
That Worked!  Thanks for creating a very useful tool!

1 Last Question do you happen to have a complete list of the latest Operands values for the Operating System that can be used for the OSRequirements XML file section?

**Comment by rzander** [comment]
No, but you can prepare a dummy application with all your OS requirements, export to App and search in object.xml for "RuleExpression" ... There you will find the RuleID's...

**Comment by StingerGT2** [comment]
Great!  That is what I will do!  Thanks!
