### ISSUE TITLE
Git version 2.23.0.windows.1

### ISSUE THREAD

**Issue by Blend2** [rzander/ruckzuck#61]
Der Uninstall String ist neu

$proc  = (Start-Process -FilePath "$($env:ProgramFiles)\Git\unins001.exe" -ArgumentList "/VERYSILENT" -Wait -PassThru);$proc.WaitForExit();$ExitCode = $proc.ExitCode

Gruss Daniel L.

**Comment by rzander** [comment]
Danke Dani, habs angepasst... Bitte Issue nicht schliessen solange das Problem nicht gefixt ist... ;-) 👍
