### ISSUE TITLE
Most already installed applications are not detected

### ISSUE THREAD

**Issue by Nama** [rzander/ruckzuck#64]
I ran Ruckzuck.exe and it showed up only 5 applications to update.
But Logitech Gaming Software didn't show up. Manually installing LGS replaced the old version.
I don't know anymore which application was effected, too.

So, do I need to reinstall every software I have with Ruckzuck?

**Comment by rzander** [comment]
RuckZuck has a huge mapping table to map all older Version (in your case Logitech Gaming Software) to the latest Version... As not every version is known, it will register all unknown version when you start RuckZuck.exe ... but as the whole process may take a moment you will not get a result, the first time you start RuckZuck.exe. You may have to wait 30min (that is how long the results are cached) until it should detect the outdated Version.   That's in theory, it often happens that ProductNames, Manufacturer ect. have changed and the auto mapping is not able to match your old version to the latest one... if this is the casse, send me ProductName, Manufacturer and Version of your "old" Version and I will fix the AutoMappingRules...

Short answer, No. RuckZuck should detect Updates even if the Software was not installed with RuckZuck.

**Comment by Nama** [comment]
Thank you for the answer!
I only know, that it was the version 9.00. I don't have any other infos (since I updated it already).

**Comment by rzander** [comment]
Version 9.00.42 was added at 20.10.2019 ... That's the only Version wit 9.00 I could find...
