### ISSUE TITLE
Gimp ab Version 2.10.12 neuer Parameter

### ISSUE THREAD

**Issue by Blend2** [rzander/ruckzuck#65]
Hoi Roger

Gimp braucht ab der Version 2.10.12 zusätzlich den Parameter "/ALLUSERS" um Silent installiert zu werden.

Gruss Dani

NEU:

cd $PSScriptRoot;
$proc = (Start-Process -FilePath "gimp-2.10.14-setup.exe" -ArgumentList "/ALLUSERS /SP- /VERYSILENT /NORESTART" -Wait -PassThru); $proc.WaitForExit(); $ExitCode = $proc.ExitCode;
Exit($($ExitCode))

**Comment by rzander** [comment]
Danke, habs angepasst... Dauert aber möglicherweise bis das in allen Caches aktualisiert ist...
