### ISSUE TITLE
Admin permissions?

### ISSUE THREAD

**Issue by damntoken2** [rzander/ruckzuck#66]
RuckZuck UI seems cool for self-service software deployment with onsite repository.
Unfortunately it needs admin permissions to run - any ideas how to fix this?

**Comment by damntoken2** [comment]
Tried these out: https://www.raymond.cc/blog/task-scheduler-bypass-uac-prompt/ 
But not working. 
Not sure why, maybe because I use UAC, so it asks for any admin account password, not just "yes/no". Basically authentication beats confirmation.

**Comment by rzander** [comment]
If a user has access to RuckZuck.exe running as admin, he can make himself a local Admin... So don't do that... If you want to update computer automatically, you can use a Scheduled Task with RZUpdate.exe or the OneGet Provider (PowerShell) to automate update installation... To manage a list of Device you can use https://github.com/rzander/devcdr which integrates also with RuckZuck...
