### ISSUE TITLE
RuckZuck Cache Server with OneGet Provider

### ISSUE THREAD

**Issue by amehtadoh** [rzander/ruckzuck#67]
Are there additional steps required for configuring the RuckZuck Cache docker image to provide caching for the OneGet Provider? Installations through the ruckzuck exe cache as expected, but not when using the OneGet provider through install-package in PoSH. The cache server url has been added to the registry.

**Comment by rzander** [comment]
Have you found the answer ?

**Comment by amehtadoh** [comment]
Hey Roger,

Thanks for checking up on this - the issue actually resolved itself and is correctly caching.

Thanks for the ongoing work on this, it’s a great product.

Many thanks,

Aled

Aled Mehta
Field Engineer

Telephone: +44 (0) 208 987 1150  
Support Desk: +44 (0) 208 987 1170 
Email: aled.mehta@doherty.co.uk
Web: www.doherty.co.uk 
Address: 3 Water Lane, London, TW9 1TJ

________________________________
