### ISSUE TITLE
How to access previous versions in the database?

### ISSUE THREAD

**Issue by ProfileX** [rzander/ruckzuck#69]
Is it possible to view previous versions in the database? We're trying to automate the uninstall of some apps like CCleaner & VirtualBox, and it would be great to see the detection & uninstall details for old apps. I tried some commands like this but I've only been able to query the newest version in the catalog:

Invoke-RestMethod -Uri "https://cdn.ruckzuck.tools/rest/v2/getsoftwares?shortname=VirtualBox&ver=6.0.8"

Hi, sorry if this has been covered somewhere but I didn't see it.

**Comment by rzander** [comment]
You where close... but you cannot use *shortname* in combination with *ver*

Try:
```PowerShell
$url = Invoke-RestMethod -Uri "https://ruckzuck.tools/rest/v2/geturl"
Invoke-RestMethod -Uri "$($url)/rest/v2/getsoftwares?name=ccleaner&man=piriform&ver=5.54"
```

There is currently no option to list all older versions, but ccleaner does start with ver=5.51and VirtualBox with ver=5.2.22

**Comment by ProfileX** [comment]
Excellent, thanks. Each app name and version will take a little trial & error, but some lines similar to this will allow us to discover what's in the DB: 

$url = Invoke-RestMethod -Uri "https://ruckzuck.tools/rest/v2/geturl"
$Name = "ccleaner"
$Manufacturer = "piriform"
For($i = 51; $i -le 99; $i++) {
    $Version = "5.$i"
    $Result = $null
    $Result = Invoke-RestMethod -Uri "$($url)/rest/v2/getsoftwares?name=$Name&man=$Manufacturer&ver=$Version" -ErrorAction SilentlyContinue
    If($Result -ne $null) {
        "`n$Version"
        $Result.PsDetection
        $Result.PsUninstall
    }
}



$url = Invoke-RestMethod -Uri "https://ruckzuck.tools/rest/v2/geturl"
$Name = "Oracle VM VirtualBox"
$Manufacturer = "Oracle Corporation"
For($i = 0; $i -le 99; $i++) {
    $Version = "6.0.$i"
    $NameAndVersion = "$Name $Version"
    $Result = $null
    $Result = Invoke-RestMethod -Uri "$($url)/rest/v2/getsoftwares?name=$NameAndVersion&man=$Manufacturer&ver=$Version" -ErrorAction SilentlyContinue
    If($Result -ne $null) {
        "`n$Version"
        $Result.PsDetection
        $Result.PsUninstall
    }
}

**Comment by rzander** [comment]
Before you do this kind of try and error on other products, let me know, I'can send you an export like:
[export.zip](https://github.com/rzander/ruckzuck/files/3868058/export.zip)

**Comment by ProfileX** [comment]
Yes, that would be very helpful! My company has not been enforcing software installation policies or keeping versions updated, but are getting things corrected so there is a lot of cleanup coming my way. I could even make a donation with your sponsor button :)

**Comment by ProfileX** [comment]
I think I misunderstood your previous reply, when I read it I thought you meant "I can send you an export of all products in the database". But now that this is marked as close I'm guessing you may have meant "I can send you an export of each time you request one". Either way is fine, I just don't want to bother you with multiple requests. The next two that I need are Adobe Reader and Mozilla Firefox. Thanks!

**Comment by rzander** [comment]
[export2.zip](https://github.com/rzander/ruckzuck/files/3888223/export2.zip)
In case of you need a free Inventory to get all the uninstall strings: -> https://github.com/rzander/devcdr
