### ISSUE TITLE
RuckZuck for ConfigMgr - Cannot find type [RZ2CM12.PSRZ4ConfigMgr]

### ISSUE THREAD

**Issue by kevinsa73** [rzander/ruckzuck#7]
I have RuckZuck for ConfigMgr and it is working when I run the GUI. I aplogize if this is not the right place to post this. I couldn't find issues posted specifically around RuckZuck for ConfigMgr.

I am trying to use PowerShell to update existing CM applications using your example script.

The 1st error I was getting was:
Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft
Configuration Manager\AdminConsole\bin\RZ4ConfigMgr.exe' or one of its dependencies. The system cannot find the file specified."

It looks like the name of the EXE has changed since your article on scripting the updates. 

I changed the line that read:
[System.Reflection.Assembly]::LoadFrom((Join-Path $(Split-Path $env:SMS_ADMIN_UI_PATH) RZ4ConfigMgr.exe)) | Out-Null

To:
[System.Reflection.Assembly]::LoadFrom((Join-Path $(Split-Path $env:SMS_ADMIN_UI_PATH) RZ4CM.exe)) | Out-Null

And the error related to loading the assembly went away.

Now I get this error from the New-Object portion of the line when running the script:
New-Object : Cannot find type [RZ2CM12.PSRZ4ConfigMgr]: verify that the assembly containing this type is loaded.

This is the line generating the error:
(Get-CMApplication | Where-Object LocalizedCategoryInstanceNames -eq {RuckZuck}).SDMPackageXML | % { ([xml]$_).AppMgmtDigest.Application.CustomProperties.Property | ? { $_.Name -eq "Shortname" } | select -ExpandProperty Value } | % { $RZ = New-Object RZ2CM12.PSRZ4ConfigMgr; $RZ.Productname = "$($_)"; $RZ.Run(); }

Did the syntax of the assembly change or am I doing something else wrong?

**Comment by rzander** [comment]
The current Version (1.5.1.8) does not have that PowerShell cmdlet anymore... 

Can you give me some background informations why you want to do this from PowerShell ?

If this is a real requirement, I can create a separate CmdLet... The "old" Version did not detect updates from the GUI so PowerShel lwas the only Option...

**Comment by kevinsa73** [comment]
It was primarily for the ability to run it via a scheduled task to automate the process.

Is there any way to run the current version silently via script? 

Also, is there a way to have SCCM applications that just get updated when a new version comes out instead of a new application being created? 

We would like to deploy an application and then update the source and criteria so it gets auto-updated on the clients during the application deployment cycle. I am open to suggestion if you have a better idea...

**Comment by rzander** [comment]
No, there is no silent Option at the moment.  

You want to distribute the Apps without testing ? You should consider that Applications are testet from the RuckZuck standalone tool but not from ConfigMgr... and they all depend from Internet downloads which can fail or the URLs may change...   So I don't think it's a good idea to (automatically) update existing applications... 

You can auto distribute the Content to the DP's (You can specify a DP Group Name in the .config File).

If you are using User based Collections, just define an AD Group (in worst case "Domain Users") in the .config file as default member and all the users are able to get the SW from SoftwareCenter... 

Once you have Feedback that the SW is running, you can supersed the "old" App or create a required deployment to all Clients with the "old" Version...

If you want to Auto update your Clients , you can run RZUpdate.exe (e.g. from a ConfigMgr Package) to get RuckZuck updates from the Internet... but the same here: at your own risk ;-)
https://github.com/rzander/ruckzuck/releases/download/1.5.2.0/RZUpdate.exe

**Comment by kevinsa73** [comment]
I think I understand now. Thanks for the info.
