### ISSUE TITLE
Download size

### ISSUE THREAD

**Issue by AlehKliauzo** [rzander/ruckzuck#72]
Currently the only way to get download size without downloading software is to send a HEAD request to file URL and check Content-Length in response headers. Would be great if download size was part of catalog and software info JSONs.

**Comment by rzander** [comment]
Implemented in https://github.com/rzander/ruckzuck/commit/468d9c0258d10cb8b2fbaeafdd824e28dcb1b5b4
Note: No UI for the FileSize at the moment, but all new Packages will include the size in the JSON
