### ISSUE TITLE
File hash + X509 signature

### ISSUE THREAD

**Issue by AlehKliauzo** [rzander/ruckzuck#73]
After downloading a file over a network we want to make sure that we got the file we expected and verify its integrity and we'll use a hash function like MD5 or something from SHA family to do that. If the file is signed we can also verify the signature or certificate, but that should be an additional option, it shouldn't replace file integrity check. So that File entries in software info JSON can look something like:
"HashType": MD5/SHA-x
"FileHash": %filehash%
"X509Signature": %signature% for signed files, null otherwise

**Comment by rzander** [comment]
If the file has an Authenticode Signature,  we can verify the integrity of the file by validating [winverifytrust](https://docs.microsoft.com/en-us/windows/win32/api/wintrust/nf-wintrust-winverifytrust?redirectedfrom=MSDN). Up to now, it did just check if the file has a signature but it did not verifiy the integrity of the signature.

This allows to install even a newer Version from the vendor as long as the downloaded Files are signed with the same certificate. 

RuckZuck detect's if a user has a *newer* Version installed and reports this information back so we can track Software-Updates.
If the integrity check would rely on file hashes, it would result in a failed download. These errors are also tracked, but there is a huge amount of false-positives messages, which makes it difficult to identify a broken download. 
I know the origin of your request has ConfigMgr background, where you want to be sure that the version you've downloaded does match with the version you package. But RuckZuck depends on feedback where RZ4CM and RZ4Intune users do technically not return any valuable information to make this repository up to date...

**Comment by rzander** [comment]
Implemented in https://github.com/rzander/ruckzuck/commit/19c856d92f6a7efc94db160fb0cce1ce5317102d

**Comment by rzander** [comment]
Additional Fix: https://github.com/rzander/ruckzuck/commit/fcbd39f3c57fe221cbbc2e0a202e2b6eefd5d78c as we also want to check the signature, not only the integrity....
