### ISSUE TITLE
RZ4Intune.ps1: Problem with special characters in short name

### ISSUE THREAD

**Issue by tfragner** [rzander/ruckzuck#74]
There is an URL encoding problem with certain packages (e.g. Notepad++(x64))

If the package short name includes certain characters (in this case "+") the generated URL at line 1213 is not properly encoded.

```powershell
$rzSW = Invoke-RestMethod -Uri "$($url)/rest/v2/getsoftwares?shortname=$($ShortName)"
```

If I understand the problem correct a possible solution would be:

```powershell
 $rzSW = Invoke-RestMethod -Uri "$($url)/rest/v2/getsoftwares?shortname=$([System.Web.HttpUtility]::UrlEncode($ShortName))" 
```

**Comment by rzander** [comment]
Fixed and updated the binaries in https://github.com/rzander/ruckzuck/releases/tag/1.7.1.2
There are some more Issues in the queue... I will make a stable Release V1.7.1.3 as soon as possible...
