### ISSUE TITLE
RZ4Intune - Updating apps in Intune

### ISSUE THREAD

**Issue by sebawern** [rzander/ruckzuck#75]
The documentation says RZ4Intune will connect to Intune by using Graph API to check for outdated RuckZuck-Applications. When I start RZ4Intune, it always says **there are currently no updates available**.  I know for a fact that there is newer version of Visual Studio Code available in RuckZuck by looking at the repository.

Is this feature work in progress right now, or am I doing something wrong? The notes field is populated with the metadata for Ruckzuck.

**Comment by rzander** [comment]
To detect updates in Intune, the old Version of the App in Intune must be created from RZ4Intune... But I agree, the current Version has a Bug... Something has changed as this was working before :-(
It's still a "preview" Version...

**Comment by rzander** [comment]
Problem fixed: https://github.com/rzander/ruckzuck/commit/96f75a661bc4dc4b5ace57dddd9f2cf9d714b4fa
 
EXE updated in https://github.com/rzander/ruckzuck/releases/tag/1.7.1.2

The Security Scope for Graph was wrong... Now I know why passing the AuthToken to PowerShell resulted in AccessDenied :-) = another thing to fix....
