### ISSUE TITLE
Ruckzuck for Intune script fails to upload application

### ISSUE THREAD

**Issue by beirlaenl** [rzander/ruckzuck#76]
Whenever I try to install an application the script starts with the following error:

```
Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid DateTime."
At C:\Users\User1\AppData\Local\Temp\intunewin\RZ4Intune.ps1:1207 char:89
+ ... e" = "application/json"; "Authorization" = "Bearer $($args[1])" ; "Ex ...
+                                                          ~~~~~~~~                                                         
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException 
+ FullyQualifiedErrorId : FormatException 
```

It then proceeds to create the .intunewin application but after that the script throws another error and closes without uploading the application:

```
Testing if SourceFile 'C:\Users\User1\AppData\Local\Temp\intunewin\googlechromestandaloneenterprise64.intunewin' Path is valid...

Creating JSON data to pass to the service...


Creating application in Intune...

Aborting with exception: System.Management.Automation.MethodInvocationException: Exception calling "Serialize" with "2" argument(s): "Object Graph cannot be null.
Parameter name: graph" ---> System.ArgumentNullException: Object Graph cannot be null.
Parameter name: graph
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

I logged in using global admin credentials and gave permission to Ruckzuck for Intune when I was asked.

**Comment by rzander** [comment]
What Tiem format are you using ? RZ4Intune will send the AuthToken ExpireDate as a parameter to powershell... You can use TaskMgr and add the column CommandLine to show the parameters... It seems that PowerShell does not understand that date format...

**Comment by rzander** [comment]
Will change the code to enforce "Universal Sortable" Date format:
https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#UniversalSortable

**Comment by rzander** [comment]
Updated the .EXE in https://github.com/rzander/ruckzuck/releases/tag/1.7.1.2
Can you Test if it's working now ?

**Comment by beirlaenl** [comment]
I'm using automatic time settings in Windows. It's a 24 hour clock notation 
with UTC+01:00 Brussels, Copenhagen, Madrid, Paris

This is the parameter that is shown in the TaskMgr CommandLine column:

`powershell.exe" -executionpolicy bypass -file "Google Chrome" "eyJOeXAiOiJKVIQiLCJub25jZS161k5sZUFuempqTVVpTVjRXMHhGbmFyQ013TXcIQOpWaIFnOGFJZERWSDFncW8iLCJh`

**Comment by rzander** [comment]
seems that TaskMgr does cut the command line... anyway, can you test with the latest .EXE ?

**Comment by beirlaenl** [comment]
Just tested the latest .exe and everything seems to work now.
Huge thanks!

**Comment by rzander** [comment]
Ok, so it's fixed with https://github.com/rzander/ruckzuck/commit/17318d0d706f5478f41ed54577176941e6c4d588
