### ISSUE TITLE
Intune update behaviour

### ISSUE THREAD

**Issue by tfragner** [rzander/ruckzuck#77]
I have a question regarding Intune. Since #75 I find updates for packages. So far so good. What I don't understand is why the update generates a completely new package. These days RuckZuck found an update for Firefox and the result in Intune is like the image below:

![intune-ruckzuck](https://user-images.githubusercontent.com/15823379/70245230-083cbf00-1776-11ea-80fc-bc1f629c448a.png)

Is this behaviour intended or should the original package be updated?

**Comment by rzander** [comment]
You have now the option to test the new version before you release it in Prod....
I think it's too dangerous to just replace/update an existing app as there may be required deployments active...  And also for the case that the new Version has Issues and you have to go back to the old Version.

**Comment by tfragner** [comment]
Now I understand. I was already thinking in this direction. Thanks for the explanation. 

So the workflow on updates is:

- update package
- assign users for testing purposes
- remove assignments for the old version
- add assignments for production use

**Comment by rzander** [comment]
That's how I would do it... 👍

**Comment by tfragner** [comment]
Thanks for your help 👍
