### ISSUE TITLE
REST API wiki

### ISSUE THREAD

**Issue by AlehKliauzo** [rzander/ruckzuck#79]
Hi, I've updated REST API wiki page with entities returned by API and purpose of certain properties (according to my knowledge). Would like to hear you thoughts: 
https://github.com/AlehKliauzo/ruckzuck-wiki/blob/master/REST-API.md

**Comment by rzander** [comment]
Thanks, I just copied your Section.. Is that ok ?

**Comment by AlehKliauzo** [comment]
Sure
