### ISSUE TITLE
All Applications don't work

### ISSUE THREAD

**Issue by FranzSchenk** [rzander/ruckzuck#8]
Most recent version 1.5.18, application import in SCCM works fine, but all applications fail on client systems.

Have the same errors for every application I try in appenforce.log:

<![LOG[+++ Application not discovered with script detection. [AppDT Id: ScopeId_9BE47109-D5F4-4CF4-AEE4-91ED9BE72F28/DeploymentType_87c15570-bada-4870-a7b9-900b35ed2074, Revision: 1]]LOG]!><time="18:27:30.442-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="scripthandler.cpp:500">
<![LOG[    App enforcement environment: 
 Context: Machine
 Command line: powershell.exe -ExecutionPolicy Bypass -File install.ps1
 Allow user interaction: No
 UI mode: 0
 User token: null
 Session Id: 2
 Content path: C:\windows\ccmcache\g
 Working directory: ]LOG]!><time="18:27:30.443-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appcontext.cpp:85">
<![LOG[    Prepared working directory: C:\windows\ccmcache\g]LOG]!><time="18:27:30.444-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appcontext.cpp:189">
<![LOG[Found executable file powershell.exe with complete path C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe]LOG]!><time="18:27:30.446-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="executility.cpp:188">
<![LOG[    Prepared command line: "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -File install.ps1]LOG]!><time="18:27:30.446-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appcontext.cpp:338">
<![LOG[    Executing Command line: "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -File install.ps1 with user context]LOG]!><time="18:27:30.447-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appexcnlib.cpp:203">
<![LOG[    Working directory C:\windows\ccmcache\g]LOG]!><time="18:27:30.447-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appexcnlib.cpp:217">
<![LOG[    Post install behavior is BasedOnExitCode]LOG]!><time="18:27:30.449-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appcommon.cpp:1092">
<![LOG[    Waiting for process 4616 to finish.  Timeout = 120 minutes.]LOG]!><time="18:27:30.451-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appexcnlib.cpp:1997">
<![LOG[    Process 4616 terminated with exitcode: 4294770688]LOG]!><time="18:27:30.570-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appexcnlib.cpp:2006">
<![LOG[    Looking for exit code -196608 in exit codes table...]LOG]!><time="18:27:30.570-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appexcnlib.cpp:506">
<![LOG[    **Unmatched exit code (4294770688)** is considered an execution failure.]LOG]!><time="18:27:30.571-120" date="07-19-2017" component="AppEnforce" context="" type="2" thread="4116" file="appexcnlib.cpp:592">
<![LOG[++++++ App enforcement completed (0 seconds) for App DT "Install_X64" [ScopeId_9BE47109-D5F4-4CF4-AEE4-91ED9BE72F28/DeploymentType_87c15570-bada-4870-a7b9-900b35ed2074], Revision: 1, User SID: ] ++++++]LOG]!><time="18:27:30.572-120" date="07-19-2017" component="AppEnforce" context="" type="1" thread="4116" file="appprovider.cpp:2450">

**Comment by rzander** [comment]
Have you configured a PowerShell execution Policy ? As you see in the install command, it calls
`powershell.exe -ExecutionPolicy Bypass -File install.ps1`
Are you able to run the command manually ?

**Comment by FranzSchenk** [comment]
Yes, the PowerShell Execution Policy is configured to "Bypass"

But I think I have found the problem: Have imported several applications in one step with the SCCM RuckZuck console extension. RuckZuck told me that all packages where imported successfully. and all SCCM objects where created successfully. But the content directories of the imported applications where empty! (for example \\s022\cm_swapplication$\7-Zip 16.04 (x64) 16.04 X64_RZ520796).

Have deleted one application with all releated SCCM objects and reimported this selected application (Adobe Reader 11). And this time, the source files are present in the content directory, and the client installation of the app also works.

Will be at the customer site nect week, and will retry this bulk import of more than one apllication at once.

**Comment by rzander** [comment]
I will check if I can improve the download validation... theoretically it should check the signature or the hash of the file but it seems that it does not :-(

**Comment by FranzSchenk** [comment]
Thats a good idea!

Have re-downloaded all the apps that we need, one by one this time. And I couldn't reproduce the problem, all content is successfully downloaded this time :-)
