### ISSUE TITLE
Favorites apps?

### ISSUE THREAD

**Issue by juhacz** [rzander/ruckzuck#80]
I see the favorites button in the program, but I don't see any way to build a list of my favorite programs. If this is not possible, it could be most useful, which would make working with the program easier.
Improvement I see in this way that I build a list of my favorite applications, then they do not have to search for them every time by entering the name, only I come to the appropriate section and clicking on the selected application I install it. Alternatively, with one click I can install all my favorite applications, or only those favorites that I haven't installed yet.

**Comment by rzander** [comment]
Button changed to "Support" as it has nothing to do with personal Favorites...
