### ISSUE TITLE
Problems since .13 update

### ISSUE THREAD

**Issue by dvenus** [rzander/ruckzuck#81]
Hi!

Since the .13 update I have gotten no updates and am not able to get a list of programs to install. I am on Windows 7.. Does it just not work on W7 anymore or am I missing something?

Thanks! Dave

**Comment by rzander** [comment]
You mean 1.6.2.13 ? Yes, that's too old (had a notification for 3Month on the Web Page !)
Get the latest Version and Update to PowerShell5... it should theoretically work with Win7 but it's also time to get rid of Win7....

**Comment by dvenus** [comment]
hi,sorry meant 1.7.1.3. have you tried against powershell core 6.2.x? thanks for the quick reply! Dave Venus



Sent from my Sprint Samsung Galaxy S9.



-------- Original message --------

**Comment by rzander** [comment]
It requires System.Management.Automation.dll from the Global Assembly Cache... Not sure if powershell core does deliver that...

**Comment by rzander** [comment]
RZ Requires .NET 4.7 or higher... PowerShell Core is currently not supported.
