### ISSUE TITLE
Language choice for installers

### ISSUE THREAD

**Issue by ltGuillaume** [rzander/ruckzuck#82]
Is there any way to fix the following when using RuckZuck?

- When installing Adobe Reader on a non-English OS, it's still installed in English
- When updating PeaZip, which was previously configured to non-English, the installer resets it to English

**Comment by rzander** [comment]
Language is a difficult topic as everyone has different preferences...
* "Adobe Reader DC MUI" includes different languages , if you update "AdobeReader DC" it will keep the installed language.
> based on https://helpx.adobe.com/reader/faq.html:
Adobe Acrobat Reader MUI is Adobe's Multilingual User Interface version of Reader, which lets you roll out the same worldwide image of Reader with a single installation. Local users can then select a user interface language, or it can be set by group policy for organizational units.

* RZ does not remove or clean any settings for PeaZip. It seems that the installer does reset the settings during upgrade. You may have to ask the Vendor to fix the setup to keep previous settings.

**Comment by ltGuillaume** [comment]
Thanks for the quick reply.

- Concerning Reader, I still have to check what would happen if one installs a language-specific version via Adobe.com, then updates via RuckZuck, but MUI will do the trick, thanks.
- I'll do so, thx for checking!

**Comment by rzander** [comment]
If a client has AdobeReader DC (MUI) installed, RZ will only download the .MSP File which is language independant... So it should keep the installed language (in theory) ....

**Comment by ltGuillaume** [comment]
Thanks!

**Comment by ltGuillaume** [comment]
PeaZip has been updated to v7.1.1, which should fix the issue described here (see https://sourceforge.net/p/peazip/tickets/539/).

**Comment by rzander** [comment]
PeaZip V7.1.1 is now published...

**Comment by ltGuillaume** [comment]
Great, just tested by updating via RuckZuck, language settings are indeed preserved now.
