### ISSUE TITLE
ruckzuck with powershell

### ISSUE THREAD

**Issue by LThissen** [rzander/ruckzuck#83]
Hi,

I'm currently using Ruckzuck (which is awesome) via the REST API and I have a question regarding the property psprereq.
how could i use the value of this property with sccm ?
if this value is "[Environment]::Is64BitProcess" or a powershell script like "testpath ....." for example, is there an easy way to add this as a requirement within the deploymenttype ?

thanks in advance

 ps : I love what you did with ruckzuck :)

Ludovic

**Comment by rzander** [comment]
A Deployment-Type Prerequisite in MECM can not be PowerShell... so there is no way to convert the psprereq to configmgr...  
You can (theoretically) create a Global-Condition based on PowerShell.. but a **GLOBAL**-Condition is **GLOBAL** an **ALL** Clients in your Environment will check that script... -> **NOT** a good idea...

You know "RuckZuck for ConfigMgr" -> https://rzander.azurewebsites.net/import-ruckzuck-applications-to-configuration-manager-2012   ... no need to access the REST API ;-)

**Comment by LThissen** [comment]
ok thanks, indeed, I do know RuckRuck for CM but we want some specific operation that RZ for CM doesn't do.
why could we find in that property a powershell script if it's not usable in SCCM ?
how was it meant to work ?

**Comment by rzander** [comment]
RuckZuck is independant of MECM... That's why the architecture of RZ is different and will not match 100% to ConfigMgr or Intune... You may have to ask Microsoft why ConfigMgr does not have PreRequisite detectetion based on PowerShell scripts...

**Comment by LThissen** [comment]
Ok, I understand, anyways thanks for your answers. :)
