### ISSUE TITLE
What happens when you press "Finish" during installation?

### ISSUE THREAD

**Issue by ltGuillaume** [rzander/ruckzuck#86]
It looks like queued installations are aborted. Perhaps even the current installation isn't properly finished (should the installation files be cleaned up afterwards perhaps)?

Wouldn't it be best to leave the queue opened, even when the user presses "Finish" in the main window, in the case of on-going/queued installations?

**Comment by rzander** [comment]
Would it be helpful to have a Prompt if there pending installations like:
"minimize" or "terminate and Exit" ?!
I think there are cases where you want to terminate and close the tool...

**Comment by ltGuillaume** [comment]
That's maybe true, yeah. Yes, anything that prevents aborting the queue without notifying the user would be an improvement imho. I do think that closing the main window via finish while the queue continues to be processed would be nicest (you as a user are done, it's just that RuckZuck still has some operations queued).

**Comment by rzander** [comment]
Implemented: https://github.com/rzander/ruckzuck/commit/8a2808bc96f1b6ba0c0c3c13f5ae3c7e1bf8a88a
