### ISSUE TITLE
ConfigMgr - Config Setting for Log file creation

### ISSUE THREAD

**Issue by DaveBobFred** [rzander/ruckzuck#87]
When installing the created applications we like to have a log file created with the installation output.

Can a log file setting within the ruckzuck config file be created so it adds the location and filename to the created 'installation program' field.

**Comment by rzander** [comment]
What kind of Information do you want to see in the log ? 
What about the ConfigMgr Audit Messages, it's a built-in logging...  ? ->  Any Information missing there ?

**Comment by DaveBobFred** [comment]
Apologies if I wasn't clear and I've just realised i'm asking this is in relation to the msiexec command. msiexec has the /L flag where you can then state a location and we use this as a quick and easy way to see if an application deployment has been successful on individual machines.

I understand that the Start-Process Cmdlet has the -RedirectStandardOutput parameter but I don't know if this would work for my needs.

**Comment by rzander** [comment]
No need to check a log file as the detection method of an application tells you if the app is there or not... ?!? I don't think that an MSI or most EXE setup will return some output if you trigger them by `start-process` ... It's still not clear to me what exactly you want to achieve with the log..

The Packages in RuckZuck are not all MSI (most are not) and some MSI's are wrapped into an EXE. 
It would require a lot effort to implement a command-line parser to allow custom command lines... But at the moment I don't see a real benefit.
