### ISSUE TITLE
Is it possible to install 3rd party app to remote computer via client center app V:1.0.6.1

### ISSUE THREAD

**Issue by ismailkocaeli** [rzander/ruckzuck#88]
Dear Rzander,

Is it possible to install a 3rd party app to a remote computer via the Client Center for Configuration Manager?
&
Is it possible to give a demo license key?

Thanks
Ismail

**Comment by ismailkocaeli** [comment]
Sorry, I opened the issue under  the wrong subject.

**Comment by rzander** [comment]
Yes, you can trigger an installation on a remote client...
Another option is to install the RuckZuck OneGet Provider (for Win10), then you can connect a remote device by PowerShell an trigger an installation from there: https://github.com/rzander/ruckzuck/wiki/RuckZuck-OneGet-Provider

There is no Licensed-Version; Donators will get a key to enable some additional features: https://github.com/rzander/sccmclictr/wiki/2)-Requirements#free-vs-donators-version
