### ISSUE TITLE
RuckZuck doen't create deployment

### ISSUE THREAD

**Issue by bLackCat-79** [rzander/ruckzuck#89]
Hi,

I have ruckzuck installed for sccm, my settings look correct (according to me) but when I install software, it doens't create a deployment.

Can you help me please?

            <setting name="CreateDeployments" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="DPGroup" serializeAs="String">
                <value>Telkom</value>
            </setting>
            <setting name="DefaultADGroup" serializeAs="String">
                <value>TELKOM\Domain Users</value>

**Comment by rzander** [comment]
Just to verify...
1) Was the User Collection created successfully
1.1) Does the User-Collection have a direct Membership (TELKOM\Domain Users)
1.2) Was the User collection moved to a Folder (Default = RuckZuck)
2) Do you have any errors in %TEMP%\RZError.log ?

**Comment by bLackCat-79** [comment]
Hello Rzander,

Thanks for the quick reply!

1. Telkom\Domain Users is my AD group for all users.
1.2 The default folder is there and the app is installed in it

2. I don't see an RZError.log, but I do see know he created a deployment group UAI_Brave

Is this a wrong config of me that he makes a new group?

**Comment by rzander** [comment]
1.1) Does the User-Collection (UAI_Brave) have a direct Membership (TELKOM\Domain Users) ?
1.2) Was the User collection (UAI_Brave) moved to a Folder (Default = RuckZuck) ?
I try to figure out where in the process it failed, that's why I need to know point 1.1 and 1.2 ...
Can you send the complete config file ?

**Comment by bLackCat-79** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
            <section name="RuckZuck_Tool.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
        </sectionGroup>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="RuckZuck_Tool.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
    </sectionGroup>
    </configSections>
    <connectionStrings/>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6"/>
    </startup>
    <userSettings>
      <RuckZuck_Tool.Properties.Settings>
        <setting name="UpgradeSettings" serializeAs="String">
          <value>True</value>
        </setting>
        <setting name="UpdExlusion" serializeAs="Xml">
          <value>
            <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema" />
          </value>
        </setting>
        <setting name="UserKey" serializeAs="String">
          <value />
        </setting>
        <setting name="UserPW" serializeAs="String">
          <value />
        </setting>
        <setting name="DisableBroadcast" serializeAs="String">
          <value>True</value>
        </setting>
        <setting name="CustomerID" serializeAs="String">
          <value />
        </setting>
        <setting name="ShowAbout" serializeAs="String">
          <value>True</value>
        </setting>
      </RuckZuck_Tool.Properties.Settings>
    </userSettings>
    <applicationSettings>
        <RuckZuck_Tool.Properties.Settings>
            <setting name="CM_SQLServer" serializeAs="String">
                <value>TEL-SQL-01</value>
            </setting>
            <setting name="CM_SQLServerDBName" serializeAs="String">
                <value>CM_TEL</value>
            </setting>
            <setting name="LimitingUserCollectionID" serializeAs="String">
                <value>TEL000AA</value>
            </setting>
            <setting name="UpdateSettings" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CreateDeployments" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="DPGroup" serializeAs="String">
                <value>"Telkom"</value>
            </setting>
            <setting name="DefaultADGroup" serializeAs="String">
                <value>TELKOM\Domain Users</value>
            </setting>
            <setting name="OSRequirementsX64" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>Windows/All_x64_Windows_7_Client</string>
                        <string>Windows/All_x64_Windows_8.1_Client</string>
                        <string>Windows/All_x64_Windows_10_and_higher_Clients</string>
                        <string>Windows/All_x64_Windows_Server_2016</string>
                    </ArrayOfString>
                </value>
            </setting>
            <setting name="OSRequirementsX86" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>Windows/All_x86_Windows_7_Client</string>
                        <string>Windows/All_x86_Windows_8.1_Client</string>
                        <string>Windows/All_x86_Windows_10_and_higher_Clients</string>
                    </ArrayOfString>
                </value>
            </setting>
            <setting name="PrimaryUserRequired" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="CM_Server" serializeAs="String">
                <value>TEL-SCM-01</value>
            </setting>
            <setting name="CMContentSourceUNC" serializeAs="String">
                <value>\\tel-scm-01\admin$\temp</value>
            </setting>
            <setting name="CMSecurityScope" serializeAs="String">
                <value>SMS00ALL</value>
            </setting>
            <setting name="UpdateExistingApplications" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CollectionFolder" serializeAs="String">
                <value>RuckZuck</value>
            </setting>
            <setting name="AppFolder" serializeAs="String">
                <value>RuckZuck</value>
            </setting>
            <setting name="DefaultAppLanguage" serializeAs="String">
                <value>EN</value>
            </setting>
            <setting name="CollPrefix_DRI" serializeAs="String">
                <value>DRI_</value>
            </setting>
            <setting name="CollPrefix_URI" serializeAs="String">
                <value>URI_</value>
            </setting>
            <setting name="CollPrefix_UAI" serializeAs="String">
                <value>UAI_</value>
            </setting>
        </RuckZuck_Tool.Properties.Settings>
    </applicationSettings>
</configuration>
`

**Comment by bLackCat-79** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
            <section name="RuckZuck_Tool.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
        </sectionGroup>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="RuckZuck_Tool.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
    </sectionGroup>
    </configSections>
    <connectionStrings/>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6"/>
    </startup>
    <userSettings>
      <RuckZuck_Tool.Properties.Settings>
        <setting name="UpgradeSettings" serializeAs="String">
          <value>True</value>
        </setting>
        <setting name="UpdExlusion" serializeAs="Xml">
          <value>
            <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema" />
          </value>
        </setting>
        <setting name="UserKey" serializeAs="String">
          <value />
        </setting>
        <setting name="UserPW" serializeAs="String">
          <value />
        </setting>
        <setting name="DisableBroadcast" serializeAs="String">
          <value>True</value>
        </setting>
        <setting name="CustomerID" serializeAs="String">
          <value />
        </setting>
        <setting name="ShowAbout" serializeAs="String">
          <value>True</value>
        </setting>
      </RuckZuck_Tool.Properties.Settings>
    </userSettings>
    <applicationSettings>
        <RuckZuck_Tool.Properties.Settings>
            <setting name="CM_SQLServer" serializeAs="String">
                <value>TEL-SQL-01</value>
            </setting>
            <setting name="CM_SQLServerDBName" serializeAs="String">
                <value>CM_TEL</value>
            </setting>
            <setting name="LimitingUserCollectionID" serializeAs="String">
                <value>TEL000AA</value>
            </setting>
            <setting name="UpdateSettings" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CreateDeployments" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="DPGroup" serializeAs="String">
                <value>"Telkom"</value>
            </setting>
            <setting name="DefaultADGroup" serializeAs="String">
                <value>TELKOM\Domain Users</value>
            </setting>
            <setting name="OSRequirementsX64" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>Windows/All_x64_Windows_7_Client</string>
                        <string>Windows/All_x64_Windows_8.1_Client</string>
                        <string>Windows/All_x64_Windows_10_and_higher_Clients</string>
                        <string>Windows/All_x64_Windows_Server_2016</string>
                    </ArrayOfString>
                </value>
            </setting>
            <setting name="OSRequirementsX86" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>Windows/All_x86_Windows_7_Client</string>
                        <string>Windows/All_x86_Windows_8.1_Client</string>
                        <string>Windows/All_x86_Windows_10_and_higher_Clients</string>
                    </ArrayOfString>
                </value>
            </setting>
            <setting name="PrimaryUserRequired" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="CM_Server" serializeAs="String">
                <value>TEL-SCM-01</value>
            </setting>
            <setting name="CMContentSourceUNC" serializeAs="String">
                <value>\\tel-scm-01\admin$\temp</value>
            </setting>
            <setting name="CMSecurityScope" serializeAs="String">
                <value>SMS00ALL</value>
            </setting>
            <setting name="UpdateExistingApplications" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CollectionFolder" serializeAs="String">
                <value>RuckZuck</value>
            </setting>
            <setting name="AppFolder" serializeAs="String">
                <value>RuckZuck</value>
            </setting>
            <setting name="DefaultAppLanguage" serializeAs="String">
                <value>EN</value>
            </setting>
            <setting name="CollPrefix_DRI" serializeAs="String">
                <value>DRI_</value>
            </setting>
            <setting name="CollPrefix_URI" serializeAs="String">
                <value>URI_</value>
            </setting>
            <setting name="CollPrefix_UAI" serializeAs="String">
                <value>UAI_</value>
            </setting>
        </RuckZuck_Tool.Properties.Settings>
    </applicationSettings>
</configuration>

**Comment by bLackCat-79** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
            <section name="RuckZuck_Tool.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
        </sectionGroup>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="RuckZuck_Tool.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
    </sectionGroup>
    </configSections>
    <connectionStrings/>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6"/>
    </startup>
    <userSettings>
      <RuckZuck_Tool.Properties.Settings>
        <setting name="UpgradeSettings" serializeAs="String">
          <value>True</value>
        </setting>
        <setting name="UpdExlusion" serializeAs="Xml">
          <value>
            <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema" />
          </value>
        </setting>
        <setting name="UserKey" serializeAs="String">
          <value />
        </setting>
        <setting name="UserPW" serializeAs="String">
          <value />
        </setting>
        <setting name="DisableBroadcast" serializeAs="String">
          <value>True</value>
        </setting>
        <setting name="CustomerID" serializeAs="String">
          <value />
        </setting>
        <setting name="ShowAbout" serializeAs="String">
          <value>True</value>
        </setting>
      </RuckZuck_Tool.Properties.Settings>
    </userSettings>
    <applicationSettings>
        <RuckZuck_Tool.Properties.Settings>
            <setting name="CM_SQLServer" serializeAs="String">
                <value>TEL-SQL-01</value>
            </setting>
            <setting name="CM_SQLServerDBName" serializeAs="String">
                <value>CM_TEL</value>
            </setting>
            <setting name="LimitingUserCollectionID" serializeAs="String">
                <value>TEL000AA</value>
            </setting>
            <setting name="UpdateSettings" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CreateDeployments" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="DPGroup" serializeAs="String">
                <value>"Telkom"</value>
            </setting>
            <setting name="DefaultADGroup" serializeAs="String">
                <value>TELKOM\Domain Users</value>
            </setting>
            <setting name="OSRequirementsX64" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>Windows/All_x64_Windows_7_Client</string>
                        <string>Windows/All_x64_Windows_8.1_Client</string>
                        <string>Windows/All_x64_Windows_10_and_higher_Clients</string>
                        <string>Windows/All_x64_Windows_Server_2016</string>
                    </ArrayOfString>
                </value>
            </setting>
            <setting name="OSRequirementsX86" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>Windows/All_x86_Windows_7_Client</string>
                        <string>Windows/All_x86_Windows_8.1_Client</string>
                        <string>Windows/All_x86_Windows_10_and_higher_Clients</string>
                    </ArrayOfString>
                </value>
            </setting>
            <setting name="PrimaryUserRequired" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="CM_Server" serializeAs="String">
                <value>TEL-SCM-01</value>
            </setting>
            <setting name="CMContentSourceUNC" serializeAs="String">
                <value>\\tel-scm-01\admin$\temp</value>
            </setting>
            <setting name="CMSecurityScope" serializeAs="String">
                <value>SMS00ALL</value>
            </setting>
            <setting name="UpdateExistingApplications" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CollectionFolder" serializeAs="String">
                <value>RuckZuck</value>
            </setting>
            <setting name="AppFolder" serializeAs="String">
                <value>RuckZuck</value>
            </setting>
            <setting name="DefaultAppLanguage" serializeAs="String">
                <value>EN</value>
            </setting>
            <setting name="CollPrefix_DRI" serializeAs="String">
                <value>DRI_</value>
            </setting>
            <setting name="CollPrefix_URI" serializeAs="String">
                <value>URI_</value>
            </setting>
            <setting name="CollPrefix_UAI" serializeAs="String">
                <value>UAI_</value>
            </setting>
        </RuckZuck_Tool.Properties.Settings>
    </applicationSettings>
</configuration>
`

**Comment by bLackCat-79** [comment]
1.1) Does the User-Collection (UAI_Brave) have a direct Membership (TELKOM\Domain Users) ?
--> No
1.2) Was the User collection (UAI_Brave) moved to a Folder (Default = RuckZuck) ?
--> Yes

**Comment by rzander** [comment]
- Is your limiting Collection "TEL000AA" a User/Group Collection that contains "TELKOM\Domain Users" ?
- DPGroup "Telkom" in XML has double-quotes an the name... Remove the double-quotes
- The "CMContentSourceUNC" should not point to "xxx\admin$\temp", you will loose your sources as soon as someone is cleaning up admin$\Temp...
- Do you really have a Security Scope with the name "SMS00ALL" ? Otherwise do not set a value -> XML: `<value></value>`

Some additional Point to check:
- Was the Application created ?
- Does the Application have a DeploymentType ?
- Is the content of the App deployed to the DP Group "Telkom" ?
- If you create a deployment manually, will you see the App is Software Center ?

**Comment by bLackCat-79** [comment]
Ok, I see he makes a collection name called UAI_.... He puts the Limiting collection to my group "All Users and Groups" but no members in the UAI_ group and the software doen't comes up in software center.

Only if I deploy it manually I can get it there?

**Comment by bLackCat-79** [comment]
using this config now:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
            <section name="RuckZuck_Tool.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
        </sectionGroup>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="RuckZuck_Tool.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
    </sectionGroup>
    </configSections>
    <connectionStrings/>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6"/>
    </startup>
    <userSettings>
      <RuckZuck_Tool.Properties.Settings>
        <setting name="UpgradeSettings" serializeAs="String">
          <value>True</value>
        </setting>
        <setting name="UpdExlusion" serializeAs="Xml">
          <value>
            <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema" />
          </value>
        </setting>
        <setting name="UserKey" serializeAs="String">
          <value />
        </setting>
        <setting name="UserPW" serializeAs="String">
          <value />
        </setting>
        <setting name="DisableBroadcast" serializeAs="String">
          <value>True</value>
        </setting>
        <setting name="CustomerID" serializeAs="String">
          <value />
        </setting>
        <setting name="ShowAbout" serializeAs="String">
          <value>True</value>
        </setting>
      </RuckZuck_Tool.Properties.Settings>
    </userSettings>
    <applicationSettings>
        <RuckZuck_Tool.Properties.Settings>
            <setting name="CM_SQLServer" serializeAs="String">
                <value>TEL-SQL-01</value>
            </setting>
            <setting name="CM_SQLServerDBName" serializeAs="String">
                <value>CM_TEL</value>
            </setting>
            <setting name="LimitingUserCollectionID" serializeAs="String">
                <value>TEL000AA</value>
            </setting>
            <setting name="UpdateSettings" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CreateDeployments" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="DPGroup" serializeAs="String">
                <value>All DP's</value>
            </setting>
            <setting name="DefaultADGroup" serializeAs="String">
                <value>Telkom\Domain Users</value>
            </setting>
            <setting name="OSRequirementsX64" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>Windows/All_x64_Windows_7_Client</string>
                        <string>Windows/All_x64_Windows_8.1_Client</string>
                        <string>Windows/All_x64_Windows_10_and_higher_Clients</string>
                        <string>Windows/All_x64_Windows_Server_2016</string>
                    </ArrayOfString>
                </value>
            </setting>
            <setting name="OSRequirementsX86" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>Windows/All_x86_Windows_7_Client</string>
                        <string>Windows/All_x86_Windows_8.1_Client</string>
                        <string>Windows/All_x86_Windows_10_and_higher_Clients</string>
                    </ArrayOfString>
                </value>
            </setting>
            <setting name="PrimaryUserRequired" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="CM_Server" serializeAs="String">
                <value>tel-scm-01</value>
            </setting>
            <setting name="CMContentSourceUNC" serializeAs="String">
                <value>\\localhost\admin$\temp</value>
            </setting>
            <setting name="CMSecurityScope" serializeAs="String">
                <value></value>
            </setting>
            <setting name="UpdateExistingApplications" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CollectionFolder" serializeAs="String">
                <value></value>
            </setting>
            <setting name="AppFolder" serializeAs="String">
                <value></value>
            </setting>
            <setting name="DefaultAppLanguage" serializeAs="String">
                <value>EN</value>
            </setting>
            <setting name="CollPrefix_DRI" serializeAs="String">
                <value>DRI_</value>
            </setting>
            <setting name="CollPrefix_URI" serializeAs="String">
                <value>URI_</value>
            </setting>
            <setting name="CollPrefix_UAI" serializeAs="String">
                <value>UAI_</value>
            </setting>
        </RuckZuck_Tool.Properties.Settings>
    </applicationSettings>
</configuration>

**Comment by bLackCat-79** [comment]
Even with the default settings (except I changes the SQL server name, db and SCM server name) He creates collection groups without memebers.

**Comment by rzander** [comment]
What is the ConfigMgr Branch/Version do you have ? CMCB 1910 ?
As you do not have a %TEMP%\RZError.txt, the only reason to not create a deployment is:
- Application already has a deployment
- "CreateDeployments" Property in XML is not True..
- ConfigMgr is not throwing an Error when creating the deployment was failed

When you create an App, do you see a status "Creating Deployment..." (right after "Creating User Collection...") ?

**Comment by bLackCat-79** [comment]
I do have an RZError now:
13/05/2020 11:54:37;F81185Object reference not set to an instance of an object.
13/05/2020 11:56:21;F81185Object reference not set to an instance of an object.

I am using 1910 current branch

**Comment by bLackCat-79** [comment]
I added 
`            <setting name="CollectionName" serializeAs="String">
                <value>Telkom</value>
            </setting>
`

But removed it again.
The application does create an app, makes a collection group, but doens't add members to it

**Comment by bLackCat-79** [comment]
![afbeelding](https://user-images.githubusercontent.com/56641399/81814093-989edd00-9528-11ea-8249-1865b6bc3e1b.png)

If I change the membership rules to query and add members he will do it, but I don't think it is itentionally made that I have to do all this after manually?

I must do mention, I am no SCCM specialist, so it might be that some other things are wrong configured.

**Comment by bLackCat-79** [comment]
Mmmm after rediscovery of my forrests it seems to work,...
