### ISSUE TITLE
Progress Telerik Fiddler

### ISSUE THREAD

**Issue by Blend2** [rzander/ruckzuck#9]
Hoi Roger

Die neuste Fiddler Version (4.6.20172.31233) wird in das AppData installiert. Wird die Software als SCCM Applikation installiert, ist diese unter C:\Windows\SysWOW64\config\systemprofile\AppData\Local\Programs\Fiddler zu finden und für den User nicht als solche sichtbar. Folglich ist auch der Uninstall String falsch.

Gruss Dani

**Comment by rzander** [comment]
Uninstall string is fixed. If you have an idea how to install per machine let me know....

**Comment by Blend2** [comment]
One option is to move the HKCU registry key to HKLM. 

HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\Fiddler2
HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Fiddler2

Then you have to copy the application icon from C:\Windows\SysWOW64\config\systemprofile\AppData\Local\Programs\Fiddler to the startmenu C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Fiddler

This works for all users and sccm inventory too. Its just a workaround :)

Regards,
Dani

**Comment by rzander** [comment]
run the Application as User in ConfigMgr to fix your issue...
