### ISSUE TITLE
Unable to install anything "Requirements not valid. Installation will not start."

### ISSUE THREAD

**Issue by victorclaessen** [rzander/ruckzuck#90]
Hi,

I've been using RuckZuck for a while. It's great!

I now run into a problem while running 1.7.1.4 on a Windows 10 x86 machine. For every software item that I've tried to install, the RuckZuck just says "Requirements not valid. Installation will not start." without any further hint as to what may be the problem. The client version gives similar output. 

Can you help me to debug? I've looked in vain for a verbose log option.

**Comment by rzander** [comment]
It seems that you are the last one on this planet with a x86 client, and no one is creating ruckzuck packages for x86 devices... You can edit, fix and upload a x86 version of a package if you want, but I will not be able to test it...

**Comment by rzander** [comment]
Well, there is a Notepad++ 32bit Version, but the RuckZuck package is made for x64 Devices...
The Detection-Method contains a "WOW6432NODE" Registry Key and the Uninstall-String is referencing "Program Files (x86)".. these do not exist on a x86 Device. You can fix these two properties, change the Architecture Attribute to "X86" and upload a the real X86 Version of Notepad++.... But the same will happen on the next version...

**Comment by victorclaessen** [comment]
Yes, well that defeats the purpose of the program, meaning it's more work than it saves. I guess for the few machines that are still used in x86 it's not worth it. I will close this issue.

Perhaps it would be a nice addition to the program if it were to warn anyone trying to execute it on a 32 bit platform, just in case they did not see the warning on the homepage ;-).
