### ISSUE TITLE
osd sccm

### ISSUE THREAD

**Issue by alexey-polischuk** [rzander/ruckzuck#92]
Hi, Roger.
Tell me the application created through ruckzuck can be added to osd?

**Comment by rzander** [comment]
Applications create with ruckzuck are "normal" applications... no secrets.
- Some applications will run as user and these apps cannot install during OSD. 
- Also check 
![image](https://user-images.githubusercontent.com/11909453/84396589-ae262600-abfe-11ea-879d-e317375e4bc1.png)
- RuckZuck apps will run PowerShell, make sure PowerShell is allowed to run during OSD (ExecutionPolicy)
- Check if the content of the app is assigned to DP's an successfully replicated
- ...
