### ISSUE TITLE
RZ4ConfigMGR -there are currently no updates available

### ISSUE THREAD

**Issue by Debugger4** [rzander/ruckzuck#97]
Hi
I have little problem with the conf mgr. I installed it and configured to my own settings (database etc)
The problem is that RZ4CM cant find updates. i have like 200-300 software in the lot
I can install and create new software but it cant find any updates.
Only error i got was this: F239E1 The ConnectionString property has not been initialized.
Any suggestion for this?
Thank you

**Comment by rzander** [comment]
RZ4CM only detect updates if the App was created with RZ4CM... You have to configure a connection to the SQL Server in the .config file (https://github.com/rzander/ruckzuck/wiki/RuckZuck-for-ConfigMgr#configuration)
- CM_SQLServer and CM_SQLServerDBName
- you must have read access to the SQL Database
- check if you have a %TEMP%\RZError.txt file with some more details....

**Comment by taaniellin** [comment]
Thank you for the answer. i had a little misunderstanding then with the software detection. 
I assumed the RZ4CM can detect all the data that ConfigMGr can provide.
I apologize for that.
Also im curious about the software repository. Does the software detect automatically newer software or users help with that?

Thank you very much for that application 👍

**Comment by rzander** [comment]
Standalone RuckZuck.exe does detect updates even if they where not installed with Ruckzuck. RZ4CM and RZ4Intune will only update Software that was imported with RuckZuck.
All Updates must be packaged in the Repository (no magic) and everyone can contribute to keep the Repository up to date...  The RuckZuck Backend is able to detect if Users/Devices have a newer versions than in the repository. This helps to detect updated Products.. but it may take some time on rarely used software... and same here, "someone" has to update the package....

**Comment by taaniellin** [comment]
Sorry to re-open it but i tried that RZ4CM again. i installed Chromium version 84 few days back and now is out the version 85 etc.
My RZ4CM cant find the update.

**Comment by rzander** [comment]
Do you see the new chromium when you open RZ4CM ? The metadata is cached, it may take a moment until you see it.. also delete %temp%\rzcat.josn which is the local cached repository metadata...

**Comment by taaniellin** [comment]
Yeah i can see it and also i deleted json file but no luck.

**Comment by rzander** [comment]
What is the Optional reference of your Application you expect and update ?
![image](https://user-images.githubusercontent.com/11909453/91561785-72b51100-e93c-11ea-8849-6cbaa2546bf9.png)

Can you run the following SQL query (with the same users that open RZ4CM), to get all RuckZuck apps, just to verify you have enough rights to detect updates...
```SQL
;WITH XMLNAMESPACES ( DEFAULT 'http://schemas.microsoft.com/SystemCenterConfigurationManager/2009/AppMgmtDigest') 
SELECT RZID, Shortname, Bootstrap, [Version] FROM  ( SELECT  SDMPackageDigest.value('(/AppMgmtDigest/Application/SoftwareVersion)[1]', 'nvarchar(MAX)') as [Version], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Bootstrap"]/@Value)[1]', 'nvarchar(MAX)') [Bootstrap], SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="Shortname"]/@Value)[1]', 'nvarchar(MAX)') [Shortname],  RIGHT(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="SWID"]/@Value)[1]', 'nvarchar(MAX)'), LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomProperties/Property[@Name="SWID"]/@Value)[1]', 'nvarchar(MAX)')) - 2) AS RZID, vCI.CI_ID FROM v_ConfigurationItems as vCI WHERE CIType_ID = 10 and IsLatest = 1 and LEN(SDMPackageDigest.value('(/AppMgmtDigest/Application/CustomId)[1]', 'nvarchar(MAX)')) > 2  ) as app WHERE RZID is not null
```

**Comment by taaniellin** [comment]
RZ20219918

I'll try that and report you back.

**Comment by rzander** [comment]
RZ20219918 is the Version 84.0.4147.105 and it's marked as outdated... so you should get an update on that one...

**Comment by rzander** [comment]
Any News on this Issue ?

**Comment by taaniellin** [comment]
Hey
Sorry for waiting but i was away and still am, i can try it next week, is it okay that til then the case is opened?
