### ISSUE TITLE
add functionality to rzupdate to allow users to search for packages from the commandline

### ISSUE THREAD

**Issue by demdante** [rzander/ruckzuck#99]
Hello.  I wanted to offer a suggestion that I think would greatly enhance the functionality of the rzupdate command line utility.  As far as I am aware, rzupdate is only able to install and update applications, but that requires that the user have prior knowledge as to what packages are available for rzupdate to install/update.  In other words, it does not currently have any functionality for querying available packages from within the tool itself, which I think really limits the tools usability.  The feature that I am suggesting would function similarly to the chocolatey command line tool's command "choco search:"

![image](https://user-images.githubusercontent.com/64720591/92045965-59afc400-ed71-11ea-871f-b61a90440b2c.png)

**Comment by rzander** [comment]
RZUpdate.exe will be replaced with [RZGet.exe]( https://github.com/rzander/ruckzuck/releases/download/1.7.1.5/RZGet.exe)
RZGet does already have a search parameter which does list the full repository. I agree that it would be helpful search for a keyword...

**Comment by rzander** [comment]
Updated RZGet.exe in https://github.com/rzander/ruckzuck/releases/tag/1.7.1.5
New Search parameters:
```
Search:
Show full catalog JSON: RZGet.exe search
Search for a keyword: RZGet.exe search zip
Search SW in a category: RZGet.exe search --categories compression
Search for installed SW: RZGet.exe search --isinstalled true
Search for a manufacturer: RZGet.exe search --manufacturer zander
Search for a shortname and return PowerShell Object: RZGet.exe search --shortname ruckzuck | convertfrom-json
```
